### ISSUE TITLE
rpcclient: Missing `gettxoutproof`

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcd#1002]
_From @FrozenPrincess on March 5, 2017 20:44_

Would be nice to support this rpc command

_Copied from original issue: btcsuite/btcrpcclient#119_

**Comment by jakesyl** [comment]
Seeing as this issue was on client and `gettxoutproof` is now [supported](https://github.com/btcsuite/btcd/blob/e4f59022a387f27253674d3a389047a23615b0f1/btcjson/chainsvrcmds_test.go#L830) closing. Feel free to reopen @FrozenPrincess
