### ISSUE TITLE
rpcclient: GetTransaction includeWatchOnly

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcd#1004]
_From @cpacia on March 17, 2017 20:58_

I have need to access watch only transactions but the GetTransaction function currently passes nil into the btcjson NewGetTransactionCmd constructor (meaning do not return watch only). Is there any objection to a PR exposing the the bool in the GetTransaction and GetTransactionAsync parameters?

_Copied from original issue: btcsuite/btcrpcclient#121_

**Comment by davecgh** [comment]
_From @jrick on March 17, 2017 21:1_

sounds fine to me.

**Comment by davecgh** [comment]
_From @jrick on March 17, 2017 21:3_

although we have traditionally used multiple functions when optional parameters can be passed, in this case we'd need to do the same. don't change the signature of GetTransaction(Async).

**Comment by r-medina** [comment]
this seems like low hanging fruit... gonna take this one if that's alright

**Comment by r-medina** [comment]
@jrick correct me if im wrong but the work in this repo is very trivial (these functions arent tested)

**Comment by onyb** [comment]
Resolved in #1592.
