### ISSUE TITLE
rpcclient: addwitnessaddress is missing

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcd#1006]
_From @FrozenPrincess on August 14, 2017 23:40_

With segwit activation just around the corner, it's probably a good time to support this rpc command

_Copied from original issue: btcsuite/btcrpcclient#130_

**Comment by ysangkok** [comment]
is this fixed with https://github.com/btcsuite/btcd/commit/91e5ba1a80082d436cc35965d74e0a41be7f2d99 ?

**Comment by davecgh** [comment]
That commit only adds it to btcjson.  It still is not available in `rpcclient`.

**Comment by jakesyl** [comment]
This is now [present](https://github.com/btcsuite/btcd/blob/e2d9cf4b55083056a458a86289d9a0651a00a02b/rpcclient/wallet.go#L1031)
