### ISSUE TITLE
Windows msi installer 2 years behind

### ISSUE THREAD

**Issue by Luscha** [btcsuite/btcd#1023]
The windows msi installer install btcd v0.12.0-beta, which is a version released in november 2015

**Comment by jcvernaleo** [comment]
I have no access to windows so while I have no problem generating windows exes based on the go cross-compiler, I have no idea how one generates an msi.  Can it be done from a UNIX box or a github action?  If so I'm happy to add it back in for the next release (too late for 0.21.0) but I need someone else to step in who actually knows about windows here.

**Comment by jcvernaleo** [comment]
See #1710, we do not provide msi any more.  If someone feels like adding it to our build script I'm happy to review, but not being a windows guy, not something I'm likely to do myself.
