### ISSUE TITLE
Source won't build

### ISSUE THREAD

**Issue by MJeorrett** [btcsuite/btcd#1026]
There is a bug in the source which prevents it from building i.e. when I try to install as per instructions in readme.md I get the following:
```bash
go install . ./cmd/...
# github.com/btcsuite/btcd
.\log.go:121: too many arguments in call to rotator.New
        have (*io.PipeReader, string, number, bool, number)
        want (string, int64, bool, int)
.\log.go:127: not enough arguments in call to r.Run
        have ()
        want (io.Reader)
```

Seems trivial to fix by replacing the referenced lines in log.go with the following:
121: r, err := rotator.New(logFile, 10*1024, false, 3)
127: go r.Run(pr)

**Comment by jrick** [comment]
The rotator package was updated and btcd is still pinning the older version.  Check the readme for instructions on how to use glide to restore the vendored deps.

**Comment by davecgh** [comment]
I updated the code for the latest version of the `logrotator` package, but I would like to point out that @jrick is correct.  The appropriate way to build from source is to follow the README in terms of using glide to ensure all of the dependencies are pinned to the correct versions.
