### ISSUE TITLE
rpcclient: txinwitness encoding incompatible with core

### ISSUE THREAD

**Issue by trippysalmon** [btcsuite/btcd#1036]
I was trying to interface with a core 0.14.2 node today and I encountered some issues when I used `GetRawTransactionVerbose`.

The error was: 

`json: cannot unmarshal array into Go struct field Vin.txinwitness of type string`

In core the witnesses are encoded in an array of strings, while btcd (according to roasbeef) encodes it as a single string with a white space character to separate them.

The fix for my particular project was simple, I just had to add some []'s to the `Vin` struct and modify the MarshalJSON method. Here's the commit that fixed it for me: [0dde330](https://github.com/trippysalmon/btcd/commit/0dde330128a5fdd92a928f509c139d5f3d412d81)

I'm sure there's a lot more to do than just what I did in my commit that's why I'm not making a PR out of this.

Example txid where the error occurs: 1b6c640fd147521fdf9cbf19a5f7e623a417f2db5732406011ae16583e622447

**Comment by davecgh** [comment]
Thanks for the report.  Would you mind trying with PR #1038?

Here is the (redacted) output from `btcctl` via `btcd` with it:

```
$ btcctl getrawtransaction 1b6c640fd147521fdf9cbf19a5f7e623a417f2db5732406011ae16583e622447 1
{
  "hex": "...",
  "txid": "1b6c640fd147521fdf9cbf19a5f7e623a417f2db5732406011ae16583e622447",
  "hash": "c11853dc8a97c23a7fd9044769169ca48e4cd993ab5990ea119d12e17372dede",
  "size": 490,
  "vsize": 408,
  "version": 2,
  "locktime": 482515,
  "vin": [
    {
      "txid": "33db9796ec969c1f429fdd5786cdd2ce09bdd31b7ba6b42628c273379e6ac0e1",
      "vout": 1,
      "scriptSig": {
        "asm": "00141d70506a9507e5511113ef52ca99675ec06a28ff",
        "hex": "1600141d70506a9507e5511113ef52ca99675ec06a28ff"
      },
      "txinwitness": [   "3045022100e9d8641a76e60c1dfb0e50e3edf0210e38088229c30b6ba73d229a99005cd95602201625adf47c4107cebf9aa0f018e3f18bfda78cb0237693ad58e0f7341234f63501",
        "03729c246fa3c81b482d2270d7972d6f3e1ba2ebdeda9d04a7f6c0cc74b0a7ca4f"
      ],
      "sequence": 4294967294
    }
  ],
  "vout": [
    ...
  ],
  "blockhash": "00000000000000000014657d2048833cad40dbf7386437764f99d7ac6c7b267d",
  ...
}
```

**Comment by trippysalmon** [comment]
Just tested #1038 and it works, nice :)

Thanks for the quick response!

**Comment by davecgh** [comment]
Thanks for testing and following up.
