### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by sparkyperreras** [btcsuite/btcd#1064]
I am trying to check a block using the btcctl getblock command, unfortunately it seems that I am not authorized to do it. Please see the command I have used as well as the response.

btcctl getblock 000000000000000051d2e759c63a26e247f185ecb7926ed7a6624bc31c2a717b true
401 Unauthorized.

**Comment by davecgh** [comment]
That means you don't have `btcctl` configured with the correct RPC username and password.

**Comment by sparkyperreras** [comment]
BIG thanks! It's working now.
