### ISSUE TITLE
[btcec] Generating deterministic signatures (RFC6979)

### ISSUE THREAD

**Issue by nustiueudinastea** [btcsuite/btcd#1065]
I am trying to generate an RFC6979 signature for a random test message, but the resulting signature  doesn't verify in the core bitcoin client or several online JS signature tools (exp http://www.coinig.com). My question is: is the signature generated using the btcec package compatible with the bitcoin core client?

Here is the code snippet that I am using the generate the signature:
```
package main

import (
	"encoding/base64"
	"fmt"

	"github.com/btcsuite/btcd/btcec"
	"github.com/btcsuite/btcd/chaincfg"
	"github.com/btcsuite/btcd/chaincfg/chainhash"
	"github.com/btcsuite/btcutil"
)

func main() {
	wifkey, err := btcutil.DecodeWIF("L1ZbYV76EcfwgdsqkhBzBuYWLDXE1s7wpDJiKqXCmGV8Z2BqTagJ")
	if err != nil {
		panic(err)
	}
	fmt.Println("Private: ", wifkey.String())

	privKey := wifkey.PrivKey
	pubKey := privKey.PubKey()

	pk, err := btcutil.NewAddressPubKey(pubKey.SerializeCompressed(), &chaincfg.MainNetParams)
	if err != nil {
		panic(err)
	}
	fmt.Println("Address: ", pk.EncodeAddress())

	message := "test message"
	messageHash := chainhash.DoubleHashB([]byte(message))

	signature, err := btcec.SignCompact(btcec.S256(), privKey, messageHash, true)
	if err != nil {
		panic(err)
	}

	fmt.Println("Signature: ", base64.StdEncoding.EncodeToString(signature))
}
```

ps: Thanks so much for the phenomenal btcsuite!

**Comment by davecgh** [comment]
You're not signing the correct message.  The `verifymessage` requires the signed message to be the concatenation of `Bitcoin Signed Message:\n` and the user-provided message both of which preceded by a varint describing their length.

```Go
	var buf bytes.Buffer
	wire.WriteVarString(&buf, 0, "Bitcoin Signed Message:\n")
	wire.WriteVarString(&buf, 0, message)
	messageHash := chainhash.DoubleHashB(buf.Bytes())
```

**Comment by nustiueudinastea** [comment]
That totally escaped me. Thanks for your help @davecgh!
