### ISSUE TITLE
Pruning support?

### ISSUE THREAD

**Issue by anacrolix** [btcsuite/btcd#1069]
#533 mentions pruning will be possible when several PRs are merged, which they are. What is the status of this feature? Is there any other way I can reduce the disk usage of running btcd?

**Comment by atamgp** [comment]
Hi, I am also interested to know what the planning is concerning pruning support and if it conceptually will be the same as the official node implementation with same limitations compared to non-pruning.

**Comment by zaptrem** [comment]
Has this been implemented?

**Comment by MrAlexWeber** [comment]
From a [comment on #533](https://github.com/btcsuite/btcd/issues/533#issuecomment-150871631):

> The work in PRs #380, #491, and #492 make infrastructure changes that will ultimately allow it to be supported.

**Comment by shilch** [comment]
Bump

**Comment by shilch** [comment]
Bump @davecgh

**Comment by stevenroose** [comment]
I might be interested in working on this. Especially with segwit, witness data should be prunable.

**Comment by HildisviniOttar** [comment]
The major limitation with bitcoind is `-prune` also disables `-txindex` for use of rpc `getrawtransaction`. If btcd could enable block pruning whilst still supporting fetching raw transactions, it would be very compelling.

**Comment by kcalvinalvin** [comment]
@

**Comment by stevenroose** [comment]
Yaay! How's utreexo going??
