### ISSUE TITLE
Build error: github.com/btcsuite/btcd/txscript

### ISSUE THREAD

**Issue by daqing** [btcsuite/btcd#1074]
```
# github.com/btcsuite/btcd/txscript
txscript/standard.go:447:8: undefined: btcutil.AddressWitnessPubKeyHash
txscript/standard.go:453:8: undefined: btcutil.AddressWitnessScriptHash
txscript/standard.go:555:16: undefined: btcutil.NewAddressWitnessPubKeyHash
txscript/standard.go:590:16: undefined: btcutil.NewAddressWitnessScriptHash
```

when building the latest btcd code (`commit 8cea3866d`), I got the above error.

**Comment by jrick** [comment]
did you run `glide install`? check the full build instructions in the readme too if you haven't yet.

**Comment by daqing** [comment]
@jrick Yes, I did. The problem still exists after running `glide install`

**Comment by daqing** [comment]
![screen shot 2017-11-23 at 9 16 15 am](https://user-images.githubusercontent.com/8126/33155843-fc8a027a-d02e-11e7-999b-df7176e46a7b.png)

**Comment by daqing** [comment]
fixed in latest code.
