### ISSUE TITLE
Update btcd Blog Post Link

### ISSUE THREAD

**Issue by aunyks** [btcsuite/btcd#1077]
It appears that the link to a blog post that introduces btcd (https://blog.conformal.com/btcd-not-your-moms-bitcoin-daemon/) is broken. Would you like to remove all instances of the link, or redirect readers somewhere else?

**Comment by xaur** [comment]
Just opened the link, looks ok.

**Comment by aunyks** [comment]
@xaur Lol, thanks for replying to this thread. Looks like it's working for me now too 🤷‍♂️

**Comment by s-tikhomirov** [comment]
The page has a broken certificate now (`NET::ERR_CERT_DATE_INVALID`).
