### ISSUE TITLE
rpcclient: Missing custom command support

### ISSUE THREAD

**Issue by hlandau** [btcsuite/btcd#1083]
btcjson has support for defining and registering custom commands. However, rpcclient lacks any corresponding support, which undermines the ability to actually make use of this.

`(*Client).sendCmd` could be used to send arbitrary `btcjson` commands, including custom ones, but it's not exported. Exporting a similar interface would be desirable.

**Comment by IvRRimum** [comment]
Emm.. technically there is `RawRequest` method. Will test it if it works and report back.

**Comment by JeremyRand** [comment]
Is there any reason why `(*Client).sendCmd` isn't exported?  Would a PR be accepted that changes it to an exported function?

**Comment by JeremyRand** [comment]
I have a patch for this; PR should be incoming within a few days.
