### ISSUE TITLE
[RPC] getblock command has been changed

### ISSUE THREAD

**Issue by wenweih** [btcsuite/btcd#1096]
I met the same error as #1088 when call ```GetBlockVerboseTx``` method  

The getblock command is ```getblock "blockhash" ( verbosity ) ``` now. the  **verbosity**  can be one of the 0, 1, 2  [Command: getblock](https://chainquery.com/bitcoin-api/getblock)

But in btcd 
```golang
func (c *Client) GetBlockVerboseTx(blockHash *chainhash.Hash) (*btcjson.GetBlockVerboseResult, error) {
	return c.GetBlockVerboseTxAsync(blockHash).Receive()
}
``` 

and the c.GetBlockVerboseTxAsync method is
```golang
func (c *Client) GetBlockVerboseTxAsync(blockHash *chainhash.Hash) FutureGetBlockVerboseResult {
	hash := ""
	if blockHash != nil {
		hash = blockHash.String()
	}

	cmd := btcjson.NewGetBlockCmd(hash, btcjson.Bool(true), btcjson.Bool(true))
	return c.sendCmd(cmd)
}
```
**cmd := btcjson.NewGetBlockCmd(hash, btcjson.Bool(true), btcjson.Bool(true))**
```golang
func NewGetBlockCmd(hash string, verbose, verboseTx *bool) *GetBlockCmd {
	return &GetBlockCmd{
		Hash:      hash,
		Verbose:   verbose,
		VerboseTx: verboseTx,
	}
}
```  
[https://bitcoin.org/en/developer-reference#getblock](https://bitcoin.org/en/developer-reference#getblock)

**Comment by asidorochev** [comment]
My fix for that issue: https://github.com/btcsuite/btcd/pull/1112

**Comment by wenweih** [comment]
@asidorochev cool
