### ISSUE TITLE
Json-rpc fails with “No connection could be made because the target machine actively refused it”

### ISSUE THREAD

**Issue by salvador-dali** [btcsuite/btcd#1101]
Playing around with litecoin json-rpc running on windows (the API is the same as bitcoin, so I am using [bitcoin's][1] references).

My `litecoin.conf` has the following data:

    rpcuser=user
    rpcpassword=pass
    txindex=1

Based on the [documentation][2] I started the core client as `.\litecoind.exe -server`, and it looks like it works just fine because I can run various commands from another window (`.\litecoin-cli.exe getblockcount` and many other work as expected).

Now I wanted to make some json-rpc calls and I tried [Go's library][3] which bitcoin's developers recommend. I used the [example from that library's github][4] and the only modifications which I introduced were my `user` and `pass` in the definition of the `ConnConfig`.

The code fails during the execution of [client.GetBlockCount()][5] with an error: 

> Post http://localhost:8332: dial tcp [::1]:8332: connectex: No
> connection could be made because the target machine actively refused
> it.

I think that the problem is with json-rpc server but I have no idea how to verify that it works properly. Any idea how to fix it?

  [1]: https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list
  [2]: https://en.bitcoin.it/wiki/API_reference_(JSON-RPC)#JSON-RPC
  [3]: https://en.bitcoin.it/wiki/API_reference_(JSON-RPC)#Go
  [4]: https://github.com/btcsuite/btcd/blob/master/rpcclient/examples/bitcoincorehttp/main.go
  [5]: https://github.com/btcsuite/btcd/blob/master/rpcclient/examples/bitcoincorehttp/main.go#L33

**Comment by jleskovar** [comment]
Try port 8334 (or 18334 on test net)

**Comment by jleskovar** [comment]
Sorry, I think I misread your question. If you are using the btcd implementation, the RPC ports are 8334/18334, but it looks like you are using the btcd go library to talk to an LTC RPC server. The error you are getting is indicating that there is no process listening on the port you are trying to connect to. You will need to find which port LTC runs its RPC server on, and update your program accordingly.

**Comment by salvador-dali** [comment]
Thank you very much. You are right, the problem is resolved and the port is `9332`
