### ISSUE TITLE
goleveldb not up-to-date in glide?

### ISSUE THREAD

**Issue by abraithwaite** [btcsuite/btcd#1102]
This is the current fork of goleveldb in master:

https://github.com/btcsuite/goleveldb/commit/7834afc9e8cd15233b6c3d97e12674a31ca24602

However, it doesn't seem to include the performance fix (which you suggested):

https://github.com/syndtr/goleveldb/commit/a49846ec464c03848e727868e3f3f5a0220d2774

https://github.com/btcsuite/goleveldb/blob/7834afc9e8cd15233b6c3d97e12674a31ca24602/leveldb/util/hash.go

Found while investigating slowness bootstrapping a full node. :-)

**Comment by abraithwaite** [comment]
Applying the patch reduces the time spent in GC from 50% to 30% on my platform, FWIW.

**Comment by abraithwaite** [comment]
Suppose this project is dormant.  Oh well, thanks for the great libraries for working with the blockchain anyway!

**Comment by jcvernaleo** [comment]
@abraithwaite btcd is definitely not dormant.  This time of year with holidays people tend to be busy and don't always respond to things too quickly though.

Also, generally we've been pretty conservative with leveldb versions.

**Comment by abraithwaite** [comment]
Good to hear!  Understand about the holidays.  Just assumed based on the activity.  Apologies.

I was hoping that this patch could be applied to the vendored leveldb though, considering that it appears davecgh suggested it! :-)

https://github.com/syndtr/goleveldb/issues/141

**Comment by red010b37** [comment]
Just as a FYI I see that that there is now a PR to upgrade to dep - I don't know how relevant this is anymore?

https://github.com/btcsuite/btcd/pull/1130

**Comment by jakesyl** [comment]
addressed in #1575
