### ISSUE TITLE
Having issues with using btcctl

### ISSUE THREAD

**Issue by torkelrogstad** [btcsuite/btcd#1109]
`btcctl` is not working on my setup. I've ensured that `rpcpass` and `rpcuser` are the same in both config files. 

All commands issued with `btcctl` leads to the following error message:
```bash
Post https://localhost:8334: dial tcp 127.0.0.1:8334: getsockopt: connection refused
```

I'm running Go 1.9, and Ubuntu 16.04.

**Comment by Roasbeef** [comment]
Issue just looks to be that you're attempting to use the wrong port to connect to.

**Comment by vinhyenvodoi98** [comment]
I still have this error how to fix port ?

**Comment by alainjr10** [comment]
I had a similar situation. for some reason, btcd was using a different port (8332) and btcctl was attempting to use 8334. to address this, you can pass the rpc server flag when running btcctl.
Something like `btcctl —-rpcserver=127.0.0.1:8332` (assuming port 8332 is what btcd node is using).
Alternatively, you could add the rpclisten  to the btcd.conf file with the desired port, in this case, 8334.
So you add `rpclisten=:8334` to btcd.conf, and you will be able to access btcctl with no issues
