### ISSUE TITLE
Can not restart btcd, Unable to start server

### ISSUE THREAD

**Issue by shamatar** [btcsuite/btcd#1123]
Good day, maintainers.

Following the recent merged pull request and another closed issue about the same problem:

I've assembled a docker container with the latest commit

Cloning into 'github.com/btcsuite/btcd'...
commit 0ef0d8c59b58ccfc8ac814dd6dac3990d4a16be2
Author: Jim Posen <jim.posen@gmail.com>
Date:   Fri Feb 9 08:34:30 2018 -0800

    blockchain: Initialize database with genesis block.

    This fixes a bug introduced by #1066.

Removed database, restarted sync from zero, than restarted a btcd, received the same error 
```
BTCD: Unable to start server on [:8333]: assertion failed: initChainState: Expected first entry in block index to be genesis block, found 00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048
```

**Comment by jrick** [comment]
I'm unable to reproduce under my dev environment.  The referenced commit fixed the issue for me.

@jimpo any ideas?

**Comment by jimpo** [comment]
Hmm, I tested and as long as the database is wiped I am also unable to produce with the latest commit.
