### ISSUE TITLE
Has any one successfully build this for GPU execution ?

### ISSUE THREAD

**Issue by pankajagarwal** [btcsuite/btcd#1143]
Wondering if someone has already updated btcd fork to run on gpu instead of cpu ?

**Comment by stevenroose** [comment]
How so? What would that accomplish? This is not mining software :)

Are you suggesting GPU-based signature and SHA-256 calculations? Would that a noticeable impact on performance?

**Comment by pankajagarwal** [comment]
@stevenroose per my digging the code is slicing/distributing initial sync work based on vcpu's and i was wondering if we can do the distribution based on gpu core's instead as that will speed up the same by a very high magnitude. Unfortunately, there's not much documentation on using gpu's with code written in go.

Also, i noticed when doing the sync from a bitcoind node, the btcd connection is marked as misbehaving a lot of times and the same get's banned for certain duration.

**Comment by stevenroose** [comment]
(That could be a separate issue though; sorry to go off-topic.)

Do you have any details about why exactly it is flagged as misbehaving?

**Comment by stevenroose** [comment]
@pankajagarwal Does Bitcoin Core have anything of this sort?

**Comment by pankajagarwal** [comment]
I have not looked into botcoind code much and but will possibly dig more on the weekend. There's definately a bug in there as i have the subnet whitelisted from where btcd is connecting and it's not suppose to ban that peer node at all. My initial thoughts were btcd is going too fast and asking for too much data which is what's causing it but increasing the sendbytes and receivebytes limit 10 times from default didn't had any improvement in the sync speed.

**Comment by Roasbeef** [comment]
As far as I know, no. GPU mining Bitcoin is no longer profitable.
