### ISSUE TITLE
[peer] Passing nil to stopHash in PushGet*Msg causes undocumented panic

### ISSUE THREAD

**Issue by IngCr3at1on** [btcsuite/btcd#1159]
So silly me I was hoping maybe if I passed nil as a stop hash the peer would just keep sending blocks (nope :smile:).

I'd suggest either:

* add a test case with nil as the stophash and add an error check.
* document in the comments that a nil stopHash will result in a panic.

---

I was about to submit a PR for the first case then realized it would be better to discuss the options first.

**Comment by dajohi** [comment]
Please paste the panic w/ trace.

**Comment by IngCr3at1on** [comment]
@dajohi I'll have to grab it later (at work right), I followed the trace though and confirmed it is specifically the stopHash value being accessed when it's nil. Will update this issue tonight.

**Comment by IngCr3at1on** [comment]
adding the following test case can reproduce it:
```
	if err := p2.PushGetBlocksMsg(nil, nil); err != nil {
		t.Errorf("this will never be called because of a panic")
		return
	}
```
```
--- FAIL: TestOutboundPeer (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45a5c4]

goroutine 68 [running]:
testing.tRunner.func1(0xc4201081e0)
	/usr/lib/go/src/testing/testing.go:742 +0x29d
panic(0x5f2fc0, 0x871850)
	/usr/lib/go/src/runtime/panic.go:502 +0x229
github.com/btcsuite/btcd/wire.NewMsgGetBlocks(...)
	/home/ing/ply/go/src/github.com/btcsuite/btcd/wire/msggetblocks.go:137
github.com/btcsuite/btcd/peer.(*Peer).PushGetBlocksMsg(0xc420490840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ing/ply/go/src/github.com/btcsuite/btcd/peer/peer.go:922 +0x27d
github.com/btcsuite/btcd/peer_test.TestOutboundPeer(0xc4201081e0)
	/home/ing/ply/go/src/github.com/btcsuite/btcd/peer/peer_test.go:696 +0xf9b
testing.tRunner(0xc4201081e0, 0x764128)
	/usr/lib/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:824 +0x2e0
exit status 2
FAIL	github.com/btcsuite/btcd/peer	0.051s
```
also
```
	if err := p2.PushGetHeadersMsg(nil, nil); err != nil {
		t.Errorf("this will never be called because of a panic")
		return
	}
```
```
--- FAIL: TestOutboundPeer (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45a5c4]

goroutine 99 [running]:
testing.tRunner.func1(0xc4201082d0)
	/usr/lib/go/src/testing/testing.go:742 +0x29d
panic(0x5f2fc0, 0x871850)
	/usr/lib/go/src/runtime/panic.go:502 +0x229
github.com/btcsuite/btcd/peer.(*Peer).PushGetHeadersMsg(0xc420443600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ing/ply/go/src/github.com/btcsuite/btcd/peer/peer.go:967 +0x23d
github.com/btcsuite/btcd/peer_test.TestOutboundPeer(0xc4201082d0)
	/home/ing/ply/go/src/github.com/btcsuite/btcd/peer/peer_test.go:700 +0x105e
testing.tRunner(0xc4201082d0, 0x764128)
	/usr/lib/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:824 +0x2e0
exit status 2
FAIL	github.com/btcsuite/btcd/peer	0.048s
```

---

these are obviously both super minor but imho warrant a documentation update at minimum (if not handling).

**Comment by dajohi** [comment]
use &chainhash.Hash{} as the stopHash

**Comment by IngCr3at1on** [comment]
@dajohi you misunderstand the point of this issue... I understand _now_ that nil is not a valid stopHash, as I mentioned originally I was originally expecting the behavior to be different (IE: my original hope was that if I didn't pass a stopHash the other peer would continue to send, obviously this is not the case); after generating the panic I dug into this a bit and discovered the tests and have already gotten around this issue locally...

I'm suggesting that either a panic guard be added to stop that panic from occuring (and error instead) or that the documentation be updated to actually advise people of this behavior because as it stands there is _nothing_ to actually discourage someone from attempting the same thing I did.

---

That's why the title specifically says that it causes an `undocumented panic`.

If you disagree and feel like users should have to figure this out on their own I'll gladly close this issue but generally speaking I would consider documentation or a proper error for that to be good practice.

**Comment by dajohi** [comment]
I'll vote that no change is needed, but I will let others decide.

The documentation states:
```
PushGetHeadersMsg sends a getblocks message for the
provided block locator and stop hash. It will ignore
back-to-back duplicate requests.

This function is safe for concurrent access. 
```

The function wants a block locator and a stop hash.  You are sending `nil`.  Why aren't you following the documentation by sending a block locator and a stop hash?

**Comment by dajohi** [comment]
The function takes pointers to memory in which a locator and a stophash exist to do its operations.  By sending nil, you are not providing valid memory.  This is why &chainhash.Hash{} is used; to provide a valid memory address  to a zeroed out chainhash.

**Comment by IngCr3at1on** [comment]
@dajohi I've answered that question a couple of times at this point so I would ask instead why is it that the blockLocator can accept a nil arg while the stopHash cannot when the documentation does not mention special handling for nil in either case.

As a person consuming this package I obviously found the current documentation to be confusing and was trying to improve it for future users. I'm sorry if his isn't welcome.

**Comment by IngCr3at1on** [comment]
@dajohi personally I think either would be fine I just thought it was confusing. As I said initially I had written code to error if someone passed nil cause I was just going to create a PR but it occurred to me there were other ways to address it that warranted an actual discussion before submitting a PR.

**Comment by nmarley** [comment]
Personally I'd have to agree with @dajohi . The documentation doesn't say anything about passing a nil, so I'm not sure this would be expected behaviour. Maybe the possibility of adding a line which states `passing a nil will result in a panic`, but this seems superfluous to me.

Also, where would it stop? Should other functions which accept pointers also document what happens when a `nil` is passed? Should the effects of passing other types (such as `interface{}`) be addressed as well?

**Comment by IngCr3at1on** [comment]
Documenting where a nil value will cause a panic is standard behavior in the stl (you can find examples of it everywhere); https://golang.org/pkg/io/#CopyBuffer

**Comment by stevenroose** [comment]
@IngCr3at1on To be fair, when the documentation says `for the provided X and Y`, it means that it expects them to always be provided. I think it's quite consistent throughout the btcd codebase that when nils are accepted or when possibly nil is returned, it is explicitly documented. When it isn't, you should never use nils.

I agree with @dajohi that this doesn't need a change.

**Comment by IngCr3at1on** [comment]
I'm just closing this issue, clearly I'm the only person who sees this as a problem (I am totally surprised at this though since either handling a nil pointer so it doesn't panic or explicitly documenting that it will is pretty much standard practice in all languages). Sorry for bothering everyone.
