### ISSUE TITLE
serverPeer.OnFilterAdd bug

### ISSUE THREAD

**Issue by stephenlyu** [btcsuite/btcd#1167]
`func (sp *serverPeer) OnFilterAdd(_ *peer.Peer, msg *wire.MsgFilterAdd) {
	// Disconnect and/or ban depending on the node bloom services flag and
	// negotiated protocol version.
	if !sp.enforceNodeBloomFlag(msg.Command()) {
		return
	}

	if sp.filter.IsLoaded() {
		peerLog.Debugf("%s sent a filteradd request with no filter "+
			"loaded -- disconnecting", sp)
		sp.Disconnect()
		return
	}

	sp.filter.Add(msg.Data)
}`

`if sp.filter.IsLoaded() { ` SHOULD be `if !sp.filter.IsLoaded() { `

**Comment by stevenroose** [comment]
This should be fixed in https://github.com/btcsuite/btcd/pull/1169.
