### ISSUE TITLE
wire/msgtx - NewMsgTx func has no LockTime assigned 

### ISSUE THREAD

**Issue by annjieching** [btcsuite/btcd#1173]
Hi everyone. I am coming from another work that references this repo, debugging there, and wondering if this could be a problem: 

btcsuite/btcd/wire/msgtx.go:892:898 ==> 
```
func NewMsgTx(version int32) *MsgTx {
	return &MsgTx{
		Version: version,
		TxIn:    make([]*TxIn, 0, defaultTxInOutAlloc),
		TxOut:   make([]*TxOut, 0, defaultTxInOutAlloc),
	}}
```

btcsuite/btcd/wire/msgtx.go:289:294 ==> 
```
type MsgTx struct {
	Version  int32
	TxIn     []*TxIn
	TxOut    []*TxOut
	LockTime uint32 // not referenced in NewMsgTx above 
}
```

I think it just implies that LockTime is allocated to zero under NewMsgTx?
I'm new to Go, so please help me understand if this is actually fine. Thank you!

**Comment by dajohi** [comment]
Yes, Go will initialize LockTime to 0.

**Comment by annjieching** [comment]
Thanks!
