### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by gracenoah** [btcsuite/btcd#1177]
* Recently the number of merges per month has fallen to 1.
* I have 5 open pull requests with no comments open since February.
* The tests are now failing on master an no one's fixing them.

What's the game plan? Are the owners of the repo willing to let someone else take over maintenance? Are there any active forks that we should switch to instead?

I'm interested only in the bitcoin rpc client, so I'm not interested in maintaining the rest of this codebase. I haven't found a better Go bitcoin rpc client and if one is created, I'll switch to using it, but for now I'm stuck with this one and my fork is 5 commits ahead of upstream now.

**Comment by abitrolly** [comment]
May I suggest that maintenance stalled because of lack of funds?

**Comment by stevenroose** [comment]
@gracenoah Are you interested in the RPC client for usage with the Satoshi client (Core)? In that case, I think it would make sense to fork the code and take out only that bit. It's a mess to keep the compatibility with Core in this repo and it should actually not be in the first place.

As for lack of contributions. Yeah, there are very few contributors. The lead maintainer, @davecgh seems to not have been paying any attention for over a month, which is very unusual. Let's hope he's enjoying some sun and will be back soon :)

**Comment by Roasbeef** [comment]
Not dead, I'll be starting to take over as a co-maintainer. First order of business is to merge back in all the features/improvements/fixes that has been committed in my roasbeef/btcd fork over the past year or so.

**Comment by gggin** [comment]
`ListSinceBlock` RPC in rpcclient is not compatible with the newest bitcoin-core, Is there sth that I do not know?

**Comment by stevenroose** [comment]
I started working at a [fork of the client just for Core](https://github.com/stevenroose/go-bitcoin-core-rpc) but quit since I didn't need it anymore. 

It could be taken by anyone that wants and complete it. I think most of the porting (removing all btcd-specific things) is done, just update to latest API will be the most work still to be done.
