### ISSUE TITLE
How to accept RPC connections outside the localhost

### ISSUE THREAD

**Issue by DinoStray** [btcsuite/btcd#1179]
If I want to allow the client/daemon to accept RPC connections outside the localhost, what should I do?
In bitcoind, we have the config parameter like "rpcallowip=xxx".
but I can't find it in btcd.

**Comment by tb00** [comment]
Check if the RPC server listens on localhost only, which is the default behavior.
See [rpclisten in sample-btcd.conf](https://github.com/btcsuite/btcd/blob/master/sample-btcd.conf#L193)  or use `--rpclisten=` on the command line. Make sure that you do not disable TLS, it can only be disabled if RPC is bound to localhost.
Hope this helps.

**Comment by DinoStray** [comment]
OK, I got it
