### ISSUE TITLE
Supporting multiple RPC clients on one btcd instance

### ISSUE THREAD

**Issue by neogeno** [btcsuite/btcd#1190]
Hello,

If I launch btcd with command line options to increase RPC clients, like changing the --rpcmaxclients to = 50 and --rpcmaxwebsockets=50, will there be any issues I need to be aware of that could make all the clients slow down? I notice that when many clients are connected at the moment they all slow down to a crawl. 

For example is it OK to connect many LND nodes to one BTCD server? what other considerations do I need to do like allocating memory or CPU resources to make this work without a huge slowdown in performance for syncing the chains?

Thank you.

**Comment by Roasbeef** [comment]
It's possible as is already to support multiple RPC clients. btcd will allocate a dedicated goroutine for each client. If each has a ton of rescans going however, then things may slow down a bit. In the future we may move to using the BIP 158 filters internally for rescanning which should improve the performance of the rescan by quite a good bit.
