### ISSUE TITLE
Automatic RPC Configuration

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcd#120]
When `btcd` starts without a config file present, it should ideally copy the sample configuration into place along with automatically generating a reasonably secure RPC username and password and populating it into the config file.

Further, a configuration file should be created and copied into place for `btcctl` as well, or perhaps `btcctl` should do this when it starts up as well.  In either case, the credentials should be automatically configured.

I suspect this also means `btcctl` will need a way to specify a different username and password for `btcd` and `btcwallet` which are selected based on the `--wallet` flag since they might not be the same.

The end result of this should be the RPC server is running on localhost only with `btcctl` already setup to work without any need for further user configuration.

**Comment by stevenroose** [comment]
Is this fixed by #609?

**Comment by davecgh** [comment]
Yes, it is.  Thanks!
