### ISSUE TITLE
how to use btcd to extract btc TX history?

### ISSUE THREAD

**Issue by lzl124631x** [btcsuite/btcd#1202]
I want to extract btc TX history for invesigation. I tried with `btcd` but failed.

I downloaded BTC fullnode already. I want to use `btcd` as a lib to read the TXs. But it seemed to force me to use `ffldb`.  If I hardcode it to use "leveldb", it says "not supported".

My OS: Windows 10

**Comment by lzl124631x** [comment]
How to read the leveldb files in `{btcRoot}\blocks\index` using btcd?

**Comment by Roasbeef** [comment]
You can use the RPC: `getrawtransaction`. Or you can manually construct the database in a program, and read the files directly.
