### ISSUE TITLE
btcec: Implement Schnorr signatures

### ISSUE THREAD

**Issue by stevenroose** [btcsuite/btcd#1212]
According to the proposed BIP: https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki

I was thinking that it would make sense for btcec to be a separate repo. It could have a separate branch where we can support experimental crypto that is not accepted standard yet, like CT-related things, f.e. The upcoming versioning improvements in Go should make it less of an issue to have it as a separate repo as well.

**Comment by Roasbeef** [comment]
What's the gain to extract `btcec` to a diff repo? In the past it was, but then we combined everything into a single repo as otherwise PR's touching diff packages was a major pain.

**Comment by stevenroose** [comment]
> In the past it was, but then we combined everything into a single repo as otherwise PR's touching diff packages was a major pain. 

That issue should be resolved with a good dependency manager. dep or vgo will most probably make that a non-issue. I would think an argument in favor is that it allows for easier experimentation with not-yet-softforked crypto stuffs without bothering btcd development.

Also, cryptographic primitives that are related to Bitcoin, but not consensus-critical, could be added there, but btcd doesn't need them. F.e. tools to construct Schnorr multisigs or discrete log contracts. Basically all layer 2 crypto that btcd doesn't necessarily need.

**Comment by hbakhtiyor** [comment]
https://github.com/hbakhtiyor/schnorr/ implemented, feedback appreciate

**Comment by benjyz** [comment]
@stevenroose agreed, separate crypto package would be nice. any new thoughts, also with regards to schnorr?

**Comment by gcsfred2** [comment]
PR's touching diff packages is a major pain. Consider adding Schnorr and/or EdDSA to btcsuite/btcd ( 
btcec).

**Comment by Roasbeef** [comment]
The main blocker here that we were working on was to first switch over all field operations to used fixed sized limbs rather than big ints, as we'll gain quite a performance increase in the process. Once that's in place, the next step would be to implement proper constant time signing using the field elements (which #1667 doesn't use).

**Comment by Roasbeef** [comment]
The related project `dcrd` has implemented a lot of what we'll need for this, so we can either use their modules directly or copy things over. They have a schnorr implementation as well, but it deviates from BIP 340.
