### ISSUE TITLE
Unable to send raw transaction to testnet

### ISSUE THREAD

**Issue by mybestcool** [btcsuite/btcd#1225]
form addr: 2NBkVZ8wra5zvgcJLVJeB9dCubGsuf5L549
to addr：mjvkLjbL3Na9PAfSPGMSDa4pK4KEdr9DXX

failed....

----------------------------------------------------------
from addr:mjvkLjbL3Na9PAfSPGMSDa4pK4KEdr9DXX
to addr: 2NBkVZ8wra5zvgcJLVJeB9dCubGsuf5L549

passed...

-----------------------------------------------------------

i guess it does not support P2SH-P2WPKH

**Comment by Roasbeef** [comment]
How are you attempting to send this transaction?

**Comment by mybestcool** [comment]
i wrote a fun like this...
`func (c *RPCClient) CreateRawTransaction(inputs []btcjson.RawTxInput, amounts map[string]btcutil.Amount, privKeysWIF []string) (*wire.MsgTx, error) {
	if len(inputs) == 0 || len(amounts) == 0 || len(privKeysWIF) == 0 {
		return nil, errors.New("invalid params")
	}

	mtx := wire.NewMsgTx(wire.TxVersion)

	inputScripts := make(map[wire.OutPoint][]byte)
	redeemScripts := make(map[string][]byte)

	for _, input := range inputs {
		txHash, err := chainhash.NewHashFromStr(input.Txid)
		if err != nil {
			return nil, err
		}

		prevOut := wire.NewOutPoint(txHash, input.Vout)
		txIn := wire.NewTxIn(prevOut, []byte{}, nil)
		//txIn.Sequence = wire.MaxTxInSequenceNum - 1

		script, err := DecodeFromHexString(input.ScriptPubKey)
		if err != nil {
			return nil, err
		}
		inputScripts[txIn.PreviousOutPoint] = script

		redeemScript, err := DecodeFromHexString(input.RedeemScript)
		if err != nil {
			return nil, err
		}

		addr, err := btcutil.NewAddressScriptHash(redeemScript, GetNetParams())
		if err != nil {
			return nil, err
		}

		redeemScripts[addr.EncodeAddress()] = redeemScript

		mtx.AddTxIn(txIn)
	}

	// 转出帐号 支持 AddressPubKeyHash、AddressScriptHash
	for saddr, amount := range amounts {
		addr, err := DecodeAddress(saddr)
		if err != nil {
			return nil, err
		}

		switch addr.(type) {
		case *btcutil.AddressPubKeyHash:
		case *btcutil.AddressScriptHash:
		default:
			return nil, fmt.Errorf("Invalid address or key:%v", btcjson.ErrRPCInvalidAddressOrKey)
		}

		pkScript, err := txscript.PayToAddrScript(addr)
		if err != nil {
			return nil, fmt.Errorf("Failed to generate pay-to-address script")
		}

		txOut := wire.NewTxOut(int64(amount), pkScript)
		mtx.AddTxOut(txOut)
	}

	var keys map[string]*btcutil.WIF
	keys = make(map[string]*btcutil.WIF)
	for _, key := range privKeysWIF {
		wif, err := WIFKeyFromString(key)
		if err != nil {
			return nil, err
		}

		addr, err := btcutil.NewAddressPubKey(wif.SerializePubKey(), GetNetParams())
		if err != nil {
			return nil, err
		}
		addr2, err := btcutil.NewAddressWitnessPubKeyHash(btcutil.Hash160(wif.SerializePubKey()), GetNetParams())
		if err != nil {
			return nil, err
		}

		addrStr := addr.EncodeAddress()
		addrStr2 := addr2.EncodeAddress()

		keys[addrStr] = wif
		keys[addrStr2] = wif
	}

	// mtx.LockTime = uint32(*c.LockTime)
	hashType := txscript.SigHashAll

	getKey := txscript.KeyClosure(func(addr btcutil.Address) (*btcec.PrivateKey, bool, error) {
		addrStr := addr.EncodeAddress()
		wif, ok := keys[addrStr]
		if !ok {
			return nil, false, errors.New("no key for address")
		}

		return wif.PrivKey, wif.CompressPubKey, nil
	})

	getScript := txscript.ScriptClosure(func(addr btcutil.Address) ([]byte, error) {
		// If keys were provided then we can only use the
		// redeem scripts provided with our inputs, too.
		addrStr := addr.EncodeAddress()
		script, ok := redeemScripts[addrStr]
		if !ok {
			return nil, errors.New("no script for address")
		}
		return script, nil
	})

	for i, txIn := range mtx.TxIn {
		// 公钥
		prevOutScript, ok := inputScripts[txIn.PreviousOutPoint]
		if !ok {
			return nil, fmt.Errorf("%v not found", txIn.PreviousOutPoint)
		}

		// SigHashSingle inputs can only be signed if there's a
		// corresponding output. However this could be already signed,
		// so we always verify the output.
		if (hashType&txscript.SigHashSingle) !=
			txscript.SigHashSingle || i < len(mtx.TxOut) {

			script, err := txscript.SignTxOutput(GetNetParams(),
				mtx, i, prevOutScript, hashType, getKey, getScript, txIn.SignatureScript)

			if err != nil {
				return nil, err
			}

			txIn.SignatureScript = script
		}

		// 这个是本地函数，签名失败就直接退出
		vm, err := txscript.NewEngine(prevOutScript, mtx, i, txscript.StandardVerifyFlags, nil, nil, 0)
		if err == nil {
			err = vm.Execute()
		}

		if err != nil {
			return mtx, err
		}
	}

	return mtx, nil
}`

and use it like this ...
`
func TestBTCClientTransaction(t *testing.T) {
	client, err := NewRPCClient("localhost:18332", "user", "pass")
	if err != nil {
		t.Error(err)
	}

	defer client.Close()

	// sss, err := base64.StdEncoding.DecodeString("RzBEAiAnKIQQL/FADNWV99xlneBlRkAW+zmgDk4zcWo6DUM6wQIgfCTRkjzlAzucakZ4Prny2wtu7tivnn501bTOzqmDud8BIQNdxItBrXLLPPhCE7SkZ2lAa+8owOVTgtSrktSkzE4+aBYAFO+sRetN30R7lr5RsmGEm8HUnRQM")
	// ddd := hex.EncodeToString(sss)
	// fmt.Println("-----:", ddd)

	// -
	var inputs []btcjson.RawTxInput
	var amounts map[string]btcutil.Amount
	var privKeysWIF []string

	pub, err := hex.DecodeString("035dc48b41ad72cb3cf84213b4a46769406bef28c0e55382d4ab92d4a4cc4e3e68")
	if err != nil {
		t.Error(err)
	}
	pubhash := btcutil.Hash160(pub)
	fmt.Println("pubkey hash:", hex.EncodeToString(pubhash))

	remaddr, err := btcutil.NewAddressWitnessPubKeyHash(pubhash, GetNetParams())
	if err != nil {
		t.Error(err)
	}
	fmt.Println("witness pubkey addr:", remaddr.EncodeAddress())

	remscript, err := txscript.PayToAddrScript(remaddr)
	if err != nil {
		t.Error(err)
	}
	fmt.Println("witness script:", hex.EncodeToString(remscript))

	shaddr, err := btcutil.NewAddressScriptHash(remscript, GetNetParams())
	if err != nil {
		t.Error(err)
	}
	fmt.Println("script addr:", shaddr.EncodeAddress())

	script, err := txscript.PayToAddrScript(shaddr)
	if err != nil {
		t.Error(err)
	}
	fmt.Println("script script:", hex.EncodeToString(script))

	inputs = append(inputs, btcjson.RawTxInput{
		Txid:         "3388f23dd5fd1834c69006ef3c7e8240081c2663d0d0923db516f3418162925d",
		Vout:         1,
		ScriptPubKey: "a9140a91dc7509ad79b7232ec3cd56596a67611d903487",
		RedeemScript: "0014efac45eb4ddf447b96be51b261849bc1d49d140c", //0014efac45eb4ddf447b96be51b261849bc1d49d140c
	})

	amounts = make(map[string]btcutil.Amount)
	amounts["2MtD7Up8UiNwB1UXsc4gLtezRnifaBigpR2"] = btcutil.Amount(100000000)
	amounts["mjvkLjbL3Na9PAfSPGMSDa4pK4KEdr9DXX"] = btcutil.Amount(9900000)

	privKeysWIF = append(privKeysWIF, "cRHCyHcKecEVhLooc7Tcwff5yYPvJ6CHBMHhF8hf37PVQ3AJrXWT")

	tx, err := client.CreateRawTransaction(inputs, amounts, privKeysWIF)
	if err != nil {
		t.Error(err)
	}

	txbytes, err := json.MarshalIndent(tx, "", "\t")
	if err != nil {
		t.Error(err)
	}
	fmt.Println("Block Chain: tx info:", string(txbytes))
}`

**Comment by huahuayu** [comment]
@mybestcool did you success send btc, can you please share the code?
