### ISSUE TITLE
SegWit support

### ISSUE THREAD

**Issue by ccgllc-rbtc** [btcsuite/btcd#1226]
Does the current code support segwit?  If so, is there a release available prior to that support?

Background:  I'm considering creating yet another bitcoin clone that would intentional not have segwit in order to maximinze miner transaction fee payments and prevent lighting type networks from being developed for it.  I much prefer Golang over CPP, so this codebase would be a natural jumping off point.

**Comment by Roasbeef** [comment]
Yes, we already support segwit. We haven't done a release in some time, but plan to do one soon. The functionality is already available in master. 

> not have segwit in order to maximinze miner transaction fee payments and prevent lighting type networks from being developed for it.

I recommend you not fall victim to dogma, and instead examine these technical improvements independent of any sort of "factions".
