### ISSUE TITLE
Should be 'database.Tx' here?

### ISSUE THREAD

**Issue by daqing** [btcsuite/btcd#1260]
https://github.com/btcsuite/btcd/blob/f899737d7f2764dc13e4d01ff00108ec58f766a9/database/ffldb/db.go#L953

// ... implements the database.Tx interface

**Comment by Roasbeef** [comment]
Looks like it! Want to make a PR to fix it?

**Comment by jakesyl** [comment]
Can be closed once #1260 is merged
