### ISSUE TITLE
blockchain/indexers/manager.go

### ISSUE THREAD

**Issue by YuchuanGu** [btcsuite/btcd#1261]
```
			var block *vvsutil.Block
			err := m.db.View(func(dbTx database.Tx) error {
				blockBytes, err := dbTx.FetchBlock(hash)
				if err != nil {
					return err
				}
				block, err := vvsutil.NewBlockFromBytes(blockBytes)
				if err != nil {
					return err
				}
				block.SetHeight(height)
				return err
			})
```
The line `block, err := vvsutil.NewBlockFromBytes(blockBytes)`
should be `block, err = vvsutil.NewBlockFromBytes(blockBytes)`

**Comment by fxer** [comment]
Could this be why my btcd instance is now only adding orphan blocks after this message in the logs?

> ```2018-08-23 07:03:15.147 [INF] CHAN: REORGANIZE: Block 00000000000000000021ea06a6616014a8b0f37ce35a187fec281110b9d8ced3 is causing a reorganize.```
