### ISSUE TITLE
Remote DoS vulnerability

### ISSUE THREAD

**Issue by guidovranken** [btcsuite/btcd#1262]
I've identified an issue in btcd that allows anyone to reliably take down a btcd instance with little effort and bandwidth.

Would you like to be informed about this issue privately, or should I write the details here?

**Comment by Roasbeef** [comment]
Hi @guidovranken you can shoot me an email at laolu32 at gmail.com using [this key](https://pgp.mit.edu/pks/lookup?op=get&search=0x964EA263DD637C21) for encryption. Thanks!

**Comment by guidovranken** [comment]
E-mail sent. You can close this issue if you have received it.

**Comment by guidovranken** [comment]
Resolved.
