### ISSUE TITLE
SendFrom function err, account 1 not found  account

### ISSUE THREAD

**Issue by johnsneakers** [btcsuite/btcd#1269]
my step:
i am new and i run btcd in siment
i add some account (use CreateNewAccount function)
i used ListAccounts function check add new account succ
i generate btc to account A
now i want to transfer btc from A to B:

client.SendFrom("A","b account address", 0.1)
err: -32603: account 1 not found  account

Is it wrong?

**Comment by johnsneakers** [comment]
@Roasbeef  can u help me

**Comment by johnsneakers** [comment]
{"result":null,"error":{"code":-32603,"message":"account 1 not found"},"id":9}

**Comment by smartynovych** [comment]
SendMany function has the same error code and message
32603
account 1 not found

**Comment by Roasbeef** [comment]
You need to make this call against btcwallet, not btcd (which doesn't actually have a wallet).
