### ISSUE TITLE
 http: TLS handshake error from 127.0.0.1:53262:

### ISSUE THREAD

**Issue by ImmanuelSegol** [btcsuite/btcd#1271]
Hi,
When trying out the WebSocket example(nodejs) from [https://github.com/btcsuite/btcd/blob/master/docs/json_rpc_api.md#ExampleCode](url)  I get these errors.

This error appears in the btcd terminal window: 
`http: TLS handshake error from 127.0.0.1:53262: read tcp4 127.0.0.1:18334->127.0.0.1:53262: wsarecv: An existing connection was forcibly closed by the remote host.`

This error appears in the nodejs terminal after running the program.
`ERROR:Error: write EPROTO 101057795:error:1414D17A:SSL routines:tls12_check_peer_sigalg:wrong curve:openssl\ssl\t1_lib.c:1097:`

**Comment by ImmanuelSegol** [comment]
Here is my conf files.
**btcd.conf**
`[Application Options]
rpcuser=user
rpcpass=user
rpclimituser=limituser
rpclimitpass=limituser
testnet=1`

**btcctl.conf**
`[Application Options]
rpcuser=user
rpcpass=user
testnet=1`

**Comment by Roasbeef** [comment]
It looks like you need to update your version of node, it's a set of out of date cipher suites. Alternatively, you can generate a new cert which targets a narrower set of cipher suites.

**Comment by ImmanuelSegol** [comment]
> It looks like you need to update your version of node, it's a set of out of date cipher suites. Alternatively, you can generate a new cert which targets a narrower set of cipher suites.

Yeah, that was the problem there was apparently a bug in node >10.0.0, thanks for the reply anyway!
