### ISSUE TITLE
rpc interface ImportAddress  isn't satisfied for the latest bitcoin doc.

### ISSUE THREAD

**Issue by antimoth** [btcsuite/btcd#1275]
will #1126  be merged?

**Comment by guobingithub** [comment]
when I call ImportAddressRescanAsync , I got an error just  like  err: -1: JSON value is not a string as expected.  

Do you know why?  Can you help me for this problem, thanks very much.

**Comment by antimoth** [comment]
> when I call ImportAddressRescanAsync , I got an error just like err: -1: JSON value is not a string as expected.
> 
> Do you know why? Can you help me for this problem, thanks very much.

you may not specify the account argument. 
see https://bitcoin.org/en/developer-reference#importaddress

**Comment by Roasbeef** [comment]
Fixed by #1129.
