### ISSUE TITLE
how to config the data sync path which store the chain data

### ISSUE THREAD

**Issue by huahuayu** [btcsuite/btcd#1285]
It's should not be an issue, but I don't know how to do it after I read the doc.

1. I have installed btcd in ubuntu server

2. now I want to sync bitcoin testnet data, and put the data in a specific dir where I mounted a disk. 

3. from https://godoc.org/github.com/btcsuite/btcd … I know I can use `btcd --testnet` to run as testnet node, but I don't know how to config the sync dir to store the chain data, do you know how to do it?

**Comment by huahuayu** [comment]
have got it, below command to specify the data dir
`-b, --datadir=            Directory to store data`

**Comment by PirosB3** [comment]
@huahuayu can you confirm that this issue can be closed? thanks
