### ISSUE TITLE
generate bitcoin keypair 

### ISSUE THREAD

**Issue by huahuayu** [btcsuite/btcd#1308]
I am new to btcd, I already get the testnet node up, firstly I want to generate a key pair and store it in database, but I searched in btcsuite repository/google didn't find valuable info, I read the go doc about rpcclient , there's a method called [create new account](https://godoc.org/github.com/btcsuite/btcd/rpcclient#Client.CreateNewAccount), but it doesn't return the key pair 

so how can I generate a keypair

there's another project claimed that can generate keypair https://github.com/vsergeev/btckeygenie/blob/master/btckey/btckey.go but I think btcd should can do it too

**Comment by huahuayu** [comment]
as per my understanding, to generate a keypair is an offline process, no need to connect to blockchain.

**Comment by obarat** [comment]
You wan't to generate public/private keys to be able to receive and send bitcoin?  If so, btcd does not support this functionality by design.  This is supported by btcwallet https://github.com/btcsuite/btcwallet

**Comment by Roasbeef** [comment]
Checkout `bteec`, you can use that package to generate keys (offline or online).

**Comment by l0k1verloren** [comment]
There is some subset of possible numbers in a 32 byte private key that is not a valid key, but mostly, EC private keys are just a random string of 32 bytes. The btcec library can generate these and there is numerous libraries around the place and I believe even that you can generate a raw (hex format) key using openssl. The distinctive element of bitcoin asymmetric cryptography is the secp256k1 koblitz curve. This applies to signatures, not to the key pair.

I'm not sure where to find a good tool for generating keys and using them manually (offline even) to generate a transaction script signature, but Piotr Narewski's https://github.com/piotrnar/gocoin other golang bitcoin client has specifically got tools for keys and transactions from air-gapped machines.
