### ISSUE TITLE
Compatibility issue when serializing partial transaction

### ISSUE THREAD

**Issue by RHavar** [btcsuite/btcd#1312]
Let's do something like this:
```
	addr, err := btcutil.DecodeAddress("2NAEGYWL2VhiXjvXjhe3QoGY8vo8zLumEAt", nil)
	if err != nil {
		panic(err)
	}

	tx := wire.MsgTx{}
	tx.AddTxOut(wire.NewTxOut(amount, addr.ScriptAddress()))
        fmt.Println(HexifyTransaction(&tx))

func HexifyTransaction(tx *wire.MsgTx) string {
	byteBuffer := bytes.Buffer{}
	if err := tx.Serialize(&byteBuffer); err != nil {
		panic(err)
	}

	return hex.EncodeToString(byteBuffer.Bytes())
}

```

Should give us something like: `00000000000180778e060000000014ba4bdb0b07d67bc60f59c1f4fe5417056525497400000000`

but when that gets passed to core, that'll give us `-22: TX decode failed`.

**Comment by Roasbeef** [comment]
Fixed on IRC.

**Comment by RHavar** [comment]
What does 'Fixed on IRC' mean? 

(Also FWIW this issue effects all the RPC calls that deal with transactions with no inputs (e.g. FundRawTransaction, CreateRawTransaction ) as it can't serialize/deserialze them)

**Comment by Roasbeef** [comment]
Fixed as in I gave you a gist showing how you should properly decode the partial transaction? btcd doesn't have a `fundrawtransaction` method since it isn't a wallet, same goes for the other method. For create raw tx, it expects a full transaction to be present.
