### ISSUE TITLE
wif key to public address

### ISSUE THREAD

**Issue by huahuayu** [btcsuite/btcd#1319]
Hi, I have some wif keys(like 91iHr29SGJ8sSX17zsUexbRQDMrVpVDh9HD51trJa9ystzzhq3j) generated by bitcoind-cli and I need get public address(like this mzzX7tLWMT3qYwhUrTL6qJHXPntriU1JNd) from the wif key, how can I do it?

I have checked with btcd code, didn't find the way, does anyone knows?

**Comment by Roasbeef** [comment]
Checkout the `txscript` package.
