### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by kuronyago** [btcsuite/btcd#1320]
- "This project is currently under active development and is in a Beta state. It is extremely stable and has been in production use since October 2013.", but last release date - 21 Nov 2015

please add the latest and actual releases

**Comment by Roasbeef** [comment]
The release can be found under the release page. That sentence refers to the lineage of btcd.

**Comment by wpaulino** [comment]
A new `btcd` release is in the works! We plan to get some additional features in before doing so first.

Building from master should be fine in the interim. Note that the current master includes some new changes with regards to dependency management - `btcd` has replaced `glide` with [go modules](https://github.com/golang/go/wiki/Modules).
