### ISSUE TITLE
(Question) How to make payment transaction?

### ISSUE THREAD

**Issue by polderudo** [btcsuite/btcd#1322]
Hello
can some give an complete example on how to make a payment transaction using the btcsuite?
What i basicly like  to do (on the testnet for now):

- I have a transaction: f3a38acecbd9faaaebc8cb8fd88cb535388060f35923b60e6a7f185b4bb35a4f
(https://live.blockcypher.com/btc-testnet/tx/f3a38acecbd9faaaebc8cb8fd88cb535388060f35923b60e6a7f185b4bb35a4f/)

- Move those 0.005 BTC from n18HgZaBAT3r7PmdLE6jxxHUCQbi65neiQ to mmdRgCxgLTNnh16dJMkuHqxmh4Kh2tDrCv

- WIF String from n18HgZaBAT3r7PmdLE6jxxHUCQbi65neiQ is 'cNtsnL67rYr3r2nX6vyZrDrBGk4cKbvcMKS6wmfnzRwCCYiA4Soj'

The only information i found till now is 'https://www.thepolyglotdeveloper.com/2018/03/create-sign-bitcoin-transactions-golang/' but using that code as a basis and the tx as a UTXO does not work. I always get "Missing inputs" as an error.

I'm using https://hub.docker.com/r/kylemanna/bitcoind/ as a fullnode, which is fully synced and i am able to read incoming transactions from this node via rpcclient.

Just for info: I'm new to bitcoin and tried this for days now, but i seem to miss something. Also the information on the internt seems very little for creating transactions with go.

**Comment by totaloutput** [comment]
can you copy/paste your error (command line and output of the command)?
I run the code from the link you post above, it worked fine...

`{"txid":"4e8378675bcf6a389c8cfe246094aafa44249e48ab88a40e6fda3bf0f44f916a","source_address":"1MMMMSUb1piy2ufrSguNUdFmAcvqrQF8M5","destination_address":"1KKKK6N21XKo48zWKuQKXdvSsCf95ibHFa","amount":91234,"unsignedtx":"0100000001484d40d45b9ea0d652fca8258ab7caa42541eb52975857f96fb50cd732c8b4810000000000ffffffff0162640100000000001976a914df3bd30160e6c6145baaf2c88a8844c13a00d1d588ac00000000","signedtx":"01000000016a914ff4f03bda6f0ea488ab489e2444faaa946024fe8c9c386acf5b6778834e000000008b483045022100904dbeddeecccf6391ac92922381ae006bf244c002f42e195daa0a9837a4b5820220461677f9dbb7d9580e268ac486cfeb4b9d87bfdd6d4e7b1be09b8e6f5cc0a70701410414e301b2328f17442c0b8310d787bf3d8a404cfbd0704f135b6ad4b2d3ee751310f981926e53a6e8c39bd7d3fefd576c543cce493cbac06388f2651d1aacbfcdffffffff0162640100000000001976a914c8e90996c7c6080ee06284600c684ed904d14c5c88ac00000000"}
`

**Comment by farukterzioglu** [comment]
@polderudo I came accross to your issue. 
I used that blog post to learn but I also couldn't be able to use an existing tx as input.  

In my fork of btcwallet https://github.com/farukterzioglu/btcwallet-posdated I am trying sth similar to your purpose. 
I created an additional rpc method 'transfertransaction' to transfer an existing tx to address 'SkWussHPKDiEX7TVi8Ugm6LUQ7wzLkbrvk' as;
`btcctl -C .\btcctl.conf --wallet transfertransaction SkWussHPKDiEX7TVi8Ugm6LUQ7wzLkbrvk 0c5e7a918c3ebcf22eb7a3a69908a6abbcaff7c3629b0ef682912adb9227b5aa`

So far I succeed to transfer that tx. You may want to check.

`{
  "txid": "2278a5b06937058f2422b592581a161aa57b077dda0ca267d9b10a3d53796f13",
  "version": 1,
  "locktime": 0,
  "vin": [
    {
      "txid": "fb8aac681cfc55f83573c282a8e009f0cf2ebc239929a00fa7c4ffcd23ed5209",
      "vout": 0,
      "scriptSig": {
        "asm": "3045022100d6174a9c53f32dbc72d02ecc43cf479e13a2ae5ed38ad69af0dfd078c77414e3022070509e9ec5a9a98fa701b63aee42a1da89d3f411275cb27691230effa40cb95501 0340fd72ded60b2a8fc988cb4e36b04624ef38441eff3306c92c64a5ffb1747cb0",
        "hex": "483045022100d6174a9c53f32dbc72d02ecc43cf479e13a2ae5ed38ad69af0dfd078c77414e3022070509e9ec5a9a98fa701b63aee42a1da89d3f411275cb27691230effa40cb95501210340fd72ded60b2a8fc988cb4e36b04624ef38441eff3306c92c64a5ffb1747cb0"
      },
      "sequence": 4294967295
    },
    {
      "txid": "0c5e7a918c3ebcf22eb7a3a69908a6abbcaff7c3629b0ef682912adb9227b5aa",
      "vout": 0,
      "scriptSig": {
        "asm": "3045022100ae7e6ab3783ea5766e15a3b635aa5d70e3b0ef5dbf2bd891d1b64fe23246713e0220608597be9c63f951023fc0a3d070d990292e44fa3ffe2d35dce55c95690a3fad01 0340fd72ded60b2a8fc988cb4e36b04624ef38441eff3306c92c64a5ffb1747cb0",
        "hex": "483045022100ae7e6ab3783ea5766e15a3b635aa5d70e3b0ef5dbf2bd891d1b64fe23246713e0220608597be9c63f951023fc0a3d070d990292e44fa3ffe2d35dce55c95690a3fad01210340fd72ded60b2a8fc988cb4e36b04624ef38441eff3306c92c64a5ffb1747cb0"
      },
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 50,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 febbff618b28f876432b4a5bcf6c77acacae7ed9 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a914febbff618b28f876432b4a5bcf6c77acacae7ed988ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "SkWussHPKDiEX7TVi8Ugm6LUQ7wzLkbrvk"
        ]
      }
    },
    {
      "value": 49.99999627,
      "n": 1,
      "scriptPubKey": {
        "asm": "0 68fddaa302a01216c8ece12e5b0a017a01d83423",
        "hex": "001468fddaa302a01216c8ece12e5b0a017a01d83423",
        "reqSigs": 1,
        "type": "witness_v0_keyhash",
        "addresses": [
          "sb1qdr7a4gcz5qfpdj8vuyh9kzsp0gqasdprdazm8g"
        ]
      }
    }
  ]
}`

**Comment by Roasbeef** [comment]
You'll need to manually generate a signature for the transaction using the `txscript` and `btcec` packages.
