### ISSUE TITLE
rpcclient.Client doesn't reuse network connections

### ISSUE THREAD

**Issue by weirdgiraffe** [btcsuite/btcd#1323]
Establishing a connection is one of the most long running operation in HTTP and enabling connection reuse will increase the speed drastically. I propose to remove this line of code:

https://github.com/btcsuite/btcd/blob/2a560b2036bee5e3679ec2133eb6520b2f195213/rpcclient/infrastructure.go#L819

I've tracked this line up to initial commit and haven't found any explanation why Client needs to close the connection explicitly, but performance gain is huge. Here is an example test:

```
package main

import (
	"log"
	"testing"

	"github.com/btcsuite/btcd/rpcclient"
)

func TestSpeed(t *testing.T) {
	// Connect to local bitcoin core RPC server using HTTP POST mode.
	connCfg := &rpcclient.ConnConfig{
		Host:         "localhost:8332",
		User:         "username",
		Pass:         "password",
		HTTPPostMode: true,    // Bitcoin core only supports HTTP POST mode
		DisableTLS:   true,    // Bitcoin core does not provide TLS by default
	}

	client, err := rpcclient.New(connCfg, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer client.Shutdown()

	// Get the current block count.
	blockCount, err := client.GetBlockCount()
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Block count: %d", blockCount)

	for i := blockCount - 100; i < blockCount; i++ {
		hash, err := client.GetBlockHash(i)
		if err != nil {
			log.Fatal(err)
		}
		log.Printf("Block hash: %v", hash)
	}
}
```
This example test runs on my machine with the following numbers:

with `Close == false`:
```
❯ go test example_test.go
ok      command-line-arguments  3.204s
```

with `Close == true`:
```
❯ go test example_test.go
ok      command-line-arguments  10.252s
```

**Comment by totaloutput** [comment]
I think for infrastructure layer of code, it's safer to close and reconnect for each command. For the specific usecase like you showed above to retrieve 100 blocks, it's perfectly fine for the client to optimize the performance, keep the connection open until the batch of the operations finish.
Keeping the connection always on will have some other complications, for example:
How long the keep alive will be? (this might be an easy answer, we just need to be clear about it).
Will there be possibility for someone else to hijack the connection that other process previously established? (I don't have a specific scenario, but it's always good to consider it at infrastructure layer).

**Comment by weirdgiraffe** [comment]
Than maybe we should move it to the config, setting close connections as default still being able to optimize for batch jobs?

**Comment by weirdgiraffe** [comment]
And another think to consider is that HTTP 1.1 reused connections by default. So loose thoughts about maybe and if are not the proper arguments, because in this case we are playing against protocol defaults and it should be a reason for that.

**Comment by totaloutput** [comment]
@weirdgiraffe on one side, I like the idea of keeping the connection open to optimize the performance, on the other side, I'm worried about connection leak. Putting a "httpReq.Close = true" in every "sendPostRequest" is a way to keep it clean because connection should be closed after every request. Now if we want to keep it open, where do we put the close then? will there be cases that the client dies then we leak connection? I like the idea of move it to config, the batch jobs can enable it whenever is needed.

**Comment by Roasbeef** [comment]
> 		HTTPPostMode: true,    // Bitcoin core only supports HTTP POST mode


This is actually a _bitcoind_ issue. They don't support key-alive for RPC connections, so you're forced to issue a _new_ connection for each request. 

For btcd, you should instead use the web sockets mode.

**Comment by weirdgiraffe** [comment]
Just to be up to date. Quick googling gave me that: https://github.com/bitcoin/bitcoin/pull/5436
