### ISSUE TITLE
How to access IsCurrent() functionality?

### ISSUE THREAD

**Issue by jordansaints** [btcsuite/btcd#1327]
I have a need to have my app query the current sync status of the underlying btcd full node. Looking through the existing code, I discovered the `IsCurrent()` method, which seems to be exactly what I need.

I cannot seem to find a way to access that method through the rpcclient API however—it seems the method is implemented on the btcd chain/netsync side things only and not exposed any higher. Can anyone recommend for me a way to access this method? Is there some other package I must import and configure against btcd that I can use? Or can I query btcd directly somehow?

Thanks in advance for your help :)

Here are the references that I found to `IsCurrent()` that seemed promising, but all appear internal to btcd's blockchain management and not available to query from the rpcclient directly:

https://github.com/btcsuite/btcd/blob/86fed781132ac890ee03e906e4ecd5d6fa180c64/netsync/manager.go#L1424 Accessing this method through the netsync package seems the most promising. Is there a way to set up a new syncmanager and point it to my btcd client?

https://github.com/btcsuite/btcd/blob/86fed781132ac890ee03e906e4ecd5d6fa180c64/rpcadapters.go#L241 It looks like the rpcadapters are intended for adapt the btcd for btcd-specific RPC requests, rather than to be used by the rpcclient.

https://github.com/btcsuite/btcd/blob/f899737d7f2764dc13e4d01ff00108ec58f766a9/blockchain/chain.go#L1225 This one looks good, but is there a way I can access the instance of the `Blockchain` struct used by btcd to query this? I doubt it, but figured I'd list it.

**Comment by totaloutput** [comment]
@jordansaints can you use "getbestblock" to get the current node's height, then use "getpeerinfo" to get all the "currentheight" of all the peers, then if your current height is the same as  the highest height in peers, you are connecting to the node that IsCurrent.


 https://github.com/btcsuite/btcd/blob/master/docs/json_rpc_api.md#getbestblock
https://github.com/btcsuite/btcd/blob/master/docs/json_rpc_api.md#getpeerinfo

**Comment by jordansaints** [comment]
@totaloutput thanks for your reply! That is actually exactly how I ended up implementing it 😄  I assume that is sort of how `IsCurrent()` works under the hood too, but I didn't dig further.

I'm okay with that solution, so I'll go ahead and close this for now. If anyone has an even simpler way to do it feel free to reopen :)
