### ISSUE TITLE
Provide getaddressinfo in rpcclient

### ISSUE THREAD

**Issue by BitonicEelis** [btcsuite/btcd#1336]
[`validateaddress`](https://bitcoin-rpc.github.io/en/doc/0.17.99/rpc/util/validateaddress/) is deprecated and will be removed. Clients must transition to [`getaddressinfo`](https://bitcoin-rpc.github.io/en/doc/0.17.99/rpc/wallet/getaddressinfo/), but that one is not yet provided by rpcclient.

**Comment by onyb** [comment]
Fixed in #1633.
