### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by enorrmann** [btcsuite/btcd#1338]
BTCD: Version 0.12.0-beta
Linux 4.18.0-10-generic Ubuntu x86_64 x86_64 x86_64 GNU/Linux

log file [HERE](https://www.dropbox.com/s/mohw95jzcvncokf/btcd.zip?dl=1)

initial sync via tor fails with panic

this is std output

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x785bc3]

goroutine 52 [running]:
github.com/btcsuite/btcd/database/ffldb.rollbackOnPanic(0xc43ac6e120)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/database/ffldb/db.go:1831 +0x77
panic(0x9a0f40, 0xeb36a0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/btcsuite/btcd/blockchain/indexers.dbStoreFilterIdxEntry(0xc03660, 0xc43ac6e120, 0xe84e70, 0x10, 0x10, 0xc42c816000, 0xc4310be8e0, 0x20, 0x20, 0x0, ...)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/blockchain/indexers/cfindex.go:68 +0xb3
github.com/btcsuite/btcd/blockchain/indexers.storeFilter(0xc03660, 0xc43ac6e120, 0xc432b44150, 0xc43009ae70, 0xc43009ae00, 0x0, 0x0)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/blockchain/indexers/cfindex.go:179 +0x2b1
github.com/btcsuite/btcd/blockchain/indexers.(*CfIndex).ConnectBlock(0xc420120360, 0xc03660, 0xc43ac6e120, 0xc432b44150, 0xc4209e2000, 0x15a, 0x15a, 0x0, 0x0)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/blockchain/indexers/cfindex.go:225 +0x1b7
github.com/btcsuite/btcd/blockchain/indexers.dbIndexConnectBlock(0xc03660, 0xc43ac6e120, 0xc01260, 0xc420120360, 0xc432b44150, 0xc4209e2000, 0x15a, 0x15a, 0x274b, 0x0)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/blockchain/indexers/manager.go:89 +0x142
github.com/btcsuite/btcd/blockchain/indexers.(*Manager).ConnectBlock(0xc4203a5560, 0xc03660, 0xc43ac6e120, 0xc432b44150, 0xc4209e2000, 0x15a, 0x15a, 0x0, 0xc42fcf7850)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/blockchain/indexers/manager.go:508 +0xc4
github.com/btcsuite/btcd/blockchain.(*BlockChain).connectBlock.func1(0xc03660, 0xc43ac6e120, 0xc43ac6e120, 0x0)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/blockchain/chain.go:644 +0x1fb
github.com/btcsuite/btcd/database/ffldb.(*db).Update(0xc4200ac000, 0xc431f8d220, 0x0, 0x0)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/database/ffldb/db.go:1888 +0x9b
github.com/btcsuite/btcd/blockchain.(*BlockChain).connectBlock(0xc420083500, 0xc439509f10, 0xc432b44150, 0xc42a6c1a70, 0xc4209e2000, 0x15a, 0x15a, 0xc420081400, 0xc4406199c0)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/blockchain/chain.go:611 +0x323
github.com/btcsuite/btcd/blockchain.(*BlockChain).connectBestChain(0xc420083500, 0xc439509f10, 0xc432b44150, 0x0, 0x0, 0x0, 0xc440619ad8)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/blockchain/chain.go:1145 +0x1f8
github.com/btcsuite/btcd/blockchain.(*BlockChain).maybeAcceptBlock(0xc420083500, 0xc432b44150, 0x0, 0x0, 0x0, 0xec86e0)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/blockchain/accept.go:79 +0x207
github.com/btcsuite/btcd/blockchain.(*BlockChain).ProcessBlock(0xc420083500, 0xc432b44150, 0xc400000000, 0xc4405b0000, 0x0, 0x0)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/blockchain/process.go:228 +0x2b5
github.com/btcsuite/btcd/netsync.(*SyncManager).handleBlockMsg(0xc420186370, 0xc42c414160)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/netsync/manager.go:569 +0x205
github.com/btcsuite/btcd/netsync.(*SyncManager).blockHandler(0xc420186370)
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/netsync/manager.go:1166 +0x548
created by github.com/btcsuite/btcd/netsync.(*SyncManager).Start
	/home/enorrmann/gocode/src/github.com/btcsuite/btcd/netsync/manager.go:1388 +0xe3

**Comment by deafboy** [comment]
Same issue. 

```
[bitcoin@lnd ~]$ uname -a
Linux lnd 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[bitcoin@lnd ~]$ aptitude search golang | grep "i  "
i  golang-1.10-go - Go programming language compiler, linker, compiled stdlib

```


```
[bitcoin@lnd ~]$ btcd
2018-11-07 16:06:50.626 [INF] BTCD: Version 0.12.0-beta
2018-11-07 16:06:50.626 [INF] BTCD: Loading block database from '/home/bitcoin/.btcd/data/mainnet/blocks_ffldb'
2018-11-07 16:06:51.697 [INF] BCDB: Detected unclean shutdown - Repairing...
2018-11-07 16:06:51.724 [INF] BCDB: Database sync complete
2018-11-07 16:06:51.724 [INF] BTCD: Block database loaded
2018-11-07 16:06:51.747 [INF] INDX: Transaction index is enabled
2018-11-07 16:06:51.747 [INF] INDX: Committed filter index is enabled
2018-11-07 16:06:51.747 [INF] CHAN: Loading block index...
2018-11-07 16:07:00.988 [INF] CHAN: Upgrading utxo set to v2.  This will take a while...
2018-11-07 16:07:16.156 [INF] CHAN: Migrated 127243 utxos (127243 total)
2018-11-07 16:07:40.801 [INF] CHAN: Done upgrading utxo set.  Total utxos: 127243 in 39 seconds
2018-11-07 16:07:42.399 [INF] CHAN: Chain state (height 549080, hash 0000000000000000002534354a0789d021910c4def80c705e36a33820c6166c7, totaltx 354655492, work 1219234695174167169256704477)
2018-11-07 16:07:45.646 [INF] RPCS: RPC server listening on 127.0.0.1:8334
2018-11-07 16:07:46.879 [INF] AMGR: Loaded 58562 addresses from file '/home/bitcoin/.btcd/data/mainnet/peers.json'
2018-11-07 16:07:46.879 [INF] CMGR: Server listening on [::]:8333
2018-11-07 16:07:46.879 [INF] CMGR: Server listening on 0.0.0.0:8333
2018-11-07 16:07:46.880 [INF] SYNC: New valid peer 188.65.213.21:43144 (inbound) (/nodes.bitcoin-russia.ru:0.0.1f/)
2018-11-07 16:07:46.880 [INF] SYNC: New valid peer 136.243.139.96:19776 (inbound) (/bitnodes.earn.com:0.1/)
2018-11-07 16:07:46.881 [INF] SYNC: New valid peer 94.237.44.67:13647 (inbound) (/bitnodes.earn.com:0.1/)
2018-11-07 16:07:46.881 [INF] SYNC: Lost peer 136.243.139.96:19776 (inbound)
2018-11-07 16:07:46.882 [INF] CMGR: 40 addresses found from DNS seed seed.bitcoin.sipa.be
2018-11-07 16:07:46.882 [INF] SYNC: New valid peer 136.243.139.96:25727 (inbound) (/bitnodes.earn.com:0.1/)
2018-11-07 16:07:46.883 [INF] CMGR: 38 addresses found from DNS seed seed.bitcoin.jonasschnelli.ch
2018-11-07 16:07:46.884 [INF] CMGR: 38 addresses found from DNS seed dnsseed.bitcoin.dashjr.org
2018-11-07 16:07:46.903 [INF] CMGR: 40 addresses found from DNS seed seed.bitnodes.io
2018-11-07 16:07:46.927 [INF] CMGR: 25 addresses found from DNS seed seed.bitcoinstats.com
2018-11-07 16:07:46.998 [INF] CMGR: 33 addresses found from DNS seed dnsseed.bluematt.me
2018-11-07 16:07:47.009 [INF] SYNC: New valid peer 94.45.222.216:8333 (outbound) (/Satoshi:0.16.0/)
2018-11-07 16:07:47.009 [INF] SYNC: Syncing to block height 549152 from peer 94.45.222.216:8333
2018-11-07 16:07:47.093 [INF] SYNC: New valid peer 31.146.211.4:8333 (outbound) (/Satoshi:0.14.2/)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x785bf3]

goroutine 52 [running]:
github.com/btcsuite/btcd/database/ffldb.rollbackOnPanic(0xc420060510)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/database/ffldb/db.go:1831 +0x77
panic(0x9aad80, 0xeb86c0)
        /usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
github.com/btcsuite/btcd/blockchain/indexers.dbStoreFilterIdxEntry(0xc0fbc0, 0xc420060510, 0xe89e70, 0x10, 0x10, 0xc42105a760, 0xc431f9a380, 0x20, 0x20, 0x0, ...)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/blockchain/indexers/cfindex.go:68 +0xb3
github.com/btcsuite/btcd/blockchain/indexers.storeFilter(0xc0fbc0, 0xc420060510, 0xc426376310, 0xc421156900, 0xc421156900, 0x0, 0x0)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/blockchain/indexers/cfindex.go:179 +0x2b1
github.com/btcsuite/btcd/blockchain/indexers.(*CfIndex).ConnectBlock(0xc42011c4c0, 0xc0fbc0, 0xc420060510, 0xc426376310, 0xeeb300, 0x0, 0x0, 0x0, 0x0)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/blockchain/indexers/cfindex.go:225 +0x1b7
github.com/btcsuite/btcd/blockchain/indexers.dbIndexConnectBlock(0xc0fbc0, 0xc420060510, 0xc0d6c0, 0xc42011c4c0, 0xc426376310, 0xeeb300, 0x0, 0x0, 0x0, 0x0)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/blockchain/indexers/manager.go:89 +0x142
github.com/btcsuite/btcd/blockchain/indexers.(*Manager).ConnectBlock(0xc420099560, 0xc0fbc0, 0xc420060510, 0xc426376310, 0xeeb300, 0x0, 0x0, 0x0, 0xc431c67850)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/blockchain/indexers/manager.go:508 +0xc4
github.com/btcsuite/btcd/blockchain.(*BlockChain).connectBlock.func1(0xc0fbc0, 0xc420060510, 0xc420060510, 0x0)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/blockchain/chain.go:644 +0x1fb
github.com/btcsuite/btcd/database/ffldb.(*db).Update(0xc4200a8380, 0xc4291caaa0, 0x0, 0x0)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/database/ffldb/db.go:1888 +0x9b
github.com/btcsuite/btcd/blockchain.(*BlockChain).connectBlock(0xc42007f500, 0xc426376540, 0xc426376310, 0xc421156750, 0xeeb300, 0x0, 0x0, 0xece4e0, 0xc431c679c0)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/blockchain/chain.go:611 +0x323
github.com/btcsuite/btcd/blockchain.(*BlockChain).connectBestChain(0xc42007f500, 0xc426376540, 0xc426376310, 0x0, 0x0, 0x0, 0xc431c67ad8)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/blockchain/chain.go:1145 +0x1f8
github.com/btcsuite/btcd/blockchain.(*BlockChain).maybeAcceptBlock(0xc42007f500, 0xc426376310, 0xffffffff00000000, 0x0, 0x0, 0xecd760)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/blockchain/accept.go:79 +0x207
github.com/btcsuite/btcd/blockchain.(*BlockChain).ProcessBlock(0xc42007f500, 0xc426376310, 0xc400000000, 0xc431b80000, 0x0, 0x0)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/blockchain/process.go:228 +0x2b5
github.com/btcsuite/btcd/netsync.(*SyncManager).handleBlockMsg(0xc4201842c0, 0xc42e26a9c0)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/netsync/manager.go:569 +0x205
github.com/btcsuite/btcd/netsync.(*SyncManager).blockHandler(0xc4201842c0)
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/netsync/manager.go:1166 +0x548
created by github.com/btcsuite/btcd/netsync.(*SyncManager).Start
        /home/bitcoin/.go/src/github.com/btcsuite/btcd/netsync/manager.go:1388 +0xe3
[bitcoin@lnd ~]$

```

**Comment by deafboy** [comment]
Same result for builds compiled using go 1.9 and 1.8

**Comment by deafboy** [comment]
Got an answer from roasbeef on IRC

@enorrmann If you're migrating the existing .btcd from the roasbeef's fork, you need to drop cfindex using --dropcfindex

**Comment by Roasbeef** [comment]
You need to drop the old index, and stop using my fork.
