### ISSUE TITLE
does btcd has a corresponding CLI tool?

### ISSUE THREAD

**Issue by lzl124631x** [btcsuite/btcd#1340]
I've been using `bitcoin-cli` to call RPC API in bitcoind. Do we have a cli tool?

**Comment by jordansaints** [comment]
You are probably looking for `btcctl`, which is documented (albeit poorly) here: https://github.com/btcsuite/btcd/tree/master/docs#BtcctlConfig.

After installing and running `btcd` you'll be able to run `btcctl -h` to print out all CLI commands available to you.

**Comment by l0k1verloren** [comment]
Note that btcd can also talk to btcdwallet, and indeed, to any bitcoin api compliant full cryptocurrency node. As for documentation I have found thus far that the server is more the problem. Point btcctl at btcwallet, in either spv or full mode, and you'll find many of the RPC calls don't work. Enough to build a wallet off it but especially all the account related stuff is unimplemented.

**Comment by Roasbeef** [comment]
Yep `btcd` uses `btcctl`.

**Comment by lzl124631x** [comment]
Thanks!
