### ISSUE TITLE
Initial sync failing

### ISSUE THREAD

**Issue by murrayn** [btcsuite/btcd#1345]
This is happening on FreeBSD 11.2

>2018-11-13 21:52:04.957 [INF] SYNC: Processed 17 blocks in the last 10.03s (15319 transactions, height 383403, 2015-11-13 15:54:13 +0000 UTC)
> 2018-11-13 21:52:07.474 [ERR] SYNC: Failed to process block 0000000000000000018e70b947981081bfbf21f27e5a89ad8ed2666478925f36: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=1642878): checksum mismatch, want=0xb5a62e96 got=0xa4be33a1 [file=829449.ldb]
> panic: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=1642878): checksum mismatch, want=0xb5a62e96 got=0xa4be33a1 [file=829449.ldb]
> 
> goroutine 69 [running]:
> github.com/btcsuite/btcd/netsync.(*SyncManager).handleBlockMsg(0xc0000da4d0, 0xc006f2b5a0)
>         /home/murray/gocode/src/github.com/btcsuite/btcd/netsync/manager.go:584 +0x1408
> github.com/btcsuite/btcd/netsync.(*SyncManager).blockHandler(0xc0000da4d0)
>         /home/murray/gocode/src/github.com/btcsuite/btcd/netsync/manager.go:1166 +0x51b
> created by github.com/btcsuite/btcd/netsync.(*SyncManager).Start
>         /home/murray/gocode/src/github.com/btcsuite/btcd/netsync/manager.go:1388 +0xde
>

**Comment by Roasbeef** [comment]
Looks like you have disk corruption.

**Comment by murrayn** [comment]
FWIW, I ran a comprehensive disk (SSD) test with no apparent issues.

**Comment by starius** [comment]
I also have this.
