### ISSUE TITLE
It is still happening "unable to generate payment script for unsupported address type *btcutil.AddressPubKeyHash"

### ISSUE THREAD

**Issue by ubrals** [btcsuite/btcd#1351]
Hi, @davecgh 
According to your answer in https://github.com/btcsuite/btcd/issues/971#issuecomment-319056742 , this hould be related to version of software. I have just downloaded and installed the latest version btcd and btcutil available in github:
btcd --version
btcd version 0.12.0-beta

and btcutil I think it is BTCUTIL_0_5_0

When I either run or build my code, I get:
`txscript.PayToAddrScript(): unable to generate payment script for unsupported address type *btcutil.AddressPubKeyHash`

btcd and btcwallet are both running in a simnet

Here is my code:
`package main

import "fmt"
import "github.com/btcsuite/btcd/chaincfg"
import "github.com/btcsuite/btcd/txscript"
import "github.com/btcsuite/btcutil"

func main() {

addressStr := "SRosrhqp65VKFJK7nfkaBNJwrdg9e9RVrt"

address, err := btcutil.DecodeAddress(addressStr, &chaincfg.MainNetParams)
if err != nil {
    fmt.Println("btcutil.DecodeAddress():" , err)
    return
}
fmt.Println("address:" , address.EncodeAddress() )

fmt.Println("txscript.PayToAddrScript():" )
script, err := txscript.PayToAddrScript(address)
if err != nil {
    fmt.Println("txscript.PayToAddrScript():" , err)
    return
}
fmt.Printf("Script Hex: %x\n", script)

disasm, err := txscript.DisasmString(script)
if err != nil {
    fmt.Println(err)
    return
}
fmt.Println("Script Disassembly:", disasm)
}
`

Can you help me with that?

Does anybody know how to fix or workaround this?

thank you,

**Comment by Roasbeef** [comment]
Ensure you have the package manager you're using set up properly. Also typically, IRC is a better place to ask for help with test programs.
