### ISSUE TITLE
Unable to sign partially signed multisig transaction (test provided)

### ISSUE THREAD

**Issue by konfortes** [btcsuite/btcd#1358]
Hey guys,
I'm using a nodejs backend to build and partially sign a transaction (using bitcoin-js client), now I need to provide 1 more signature using btcd.
I'm using SignTxOutput to sign but it fails with error:  "can't sign unknown transactions"

`txHex := "01000000011e1c088453836f05e1e459530c97d311c2566dbc6a1a56db3840f1b276d3c6cc00000000b6004730440220663b9fd4d98a2bb92e377001bdb5ee462713f654721b6419c1b3cc9d0207608a022021df563c14dc14a51378ee824a688cdfdc874d08be7501307ed58dca4b287dd70100004c69522102609cf6b2bcd434da599366fbf7f242b7cf5d2a04ac5a7174b49f89ce3224cf922102baa30c3573be41a78bb3325cfc612da400e730033b4ed74e37d3654f9a7d19c02102d2a6172cb43b8b05a14ef5042e3d931debad92e3a4afa4864df1d5042f02167553aeffffffff02e80300000000000017a91411f129817330dc542bf0089385432eba3cd9da1f87324ebf000000000017a914d3ca786b0964b496ad6952f8adde14660f874dbd8700000000"

	decodedTx, err := hex.DecodeString(txHex)
	if err != nil {
		t.Errorf("error decoding tx hex")
	}

	var tx wire.MsgTx
	if err := tx.Deserialize(bytes.NewReader(decodedTx)); err != nil {
		t.Error("error deserializing tx")
	}

	extPrvKey, err := hdkeychain.NewKeyFromString("tprv8joYa5VZnBrKQPJbzvZnmcE9sUSur1EJ1MdiCbCCAkbp9vBVY9ifJtkNcYUranfVyA4XbzFVBpiTv768nNxTmxAyiS6gVtaRgzh8BT9vQkn")
	if err != nil {
		t.Errorf("error creating extended private key")
	}

	prvKey, err := extPrvKey.ECPrivKey()
	if err != nil {
		t.Errorf("error creating ec private key from extended")
	}

	lookupKey := func(a btcutil.Address) (*btcec.PrivateKey, bool, error) {
		return prvKey, true, nil
	}

	for i, in := range tx.TxIn {
		_, err = txscript.SignTxOutput(&chaincfg.TestNet3Params,
			&tx,
			i,
			in.SignatureScript,
			txscript.SigHashAll,
			txscript.KeyClosure(lookupKey), nil, nil)
		if err != nil {
			t.Errorf("error signing tx: %s", err.Error())
		}
	}`

**Comment by Roasbeef** [comment]
If you're using a non standard script, then we don't know how to automatically generate a signature.
