### ISSUE TITLE
How does a miner pass it's generated block to network(other peers)?

### ISSUE THREAD

**Issue by LeslieRan** [btcsuite/btcd#1367]
When a miner has mined a block, it will call `submitBlock()` : 

`              
               // Attempt to solve the block.  The function will exit early`
		`// with false when conditions that trigger a stale block, so`
		`// a new block template can be generated.  When the return is`
		`// true a solution was found, so submit the solved block.`
		`if m.solveBlock(template.Block, curHeight+1, ticker, quit) {`
			`block := btcutil.NewBlock(template.Block)`
			`m.submitBlock(block)`
		`}
`

In `submitBlock()`, `ProcessBlock()` has been called :

`
// ProcessBlock makes use of ProcessBlock on an internal instance of a block`
`// chain.`
`func (sm *SyncManager) ProcessBlock(block *btcutil.Block, flags blockchain.BehaviorFlags) (bool, error) {`
	`reply := make(chan processBlockResponse, 1)`
	`sm.msgChan <- processBlockMsg{block: block, flags: flags, reply: reply}`
	`response := <-reply`
	`return response.isOrphan, response.err`
`}
`

When fetching `processBlockMsg` message from `msgChan `, just calling `chain.ProcessBlock()` to do some checks.

So, in the whole process, I couldn't find that the generated block had been passed to network(other peers).

How does a miner pass it's generated block to network(other peers)?

**Comment by Roasbeef** [comment]
The peer to peer network. Check out https://bitcoin.org/en/developer-guide
