### ISSUE TITLE
x509: certificate is valid for 127.0.0.1, ::1, not my server ip?

### ISSUE THREAD

**Issue by demisstif** [btcsuite/btcd#1372]
Hi,
I am trying to run the rpcclient golang example code,(https://github.com/btcsuite/btcd/tree/master/rpcclient/examples/btcdwebsockets).
When I run it  in my server where btcd runing, it is fine.

But I want run the example in my local win10 computer,  the error is there:
> x509: certificate is valid for 127.0.0.1, ::1, 172.31.25.73, 172.19.0.1, 172.20.0.1, 172.18.0.1, 172.17.0.1, fe80::cdf:83ff:fe8d:828, fe80::42:32ff:fedb:bbbf, fe80::42:7bff:fe1f:b445, fe80::c85a:dbff:
fe9e:6fc2, not [my server ip]. 

I have already copied the rpc.cert file (/home/ubuntu/.btcd/rpc.cert) to my win10. and change the path in the example to get it.
```golang
certs, err := ioutil.ReadFile("../../btc/store/rpc.cert")
if err != nil {
	log.Fatal(err)
}
```

my btcd.conf is:
[Application Options]
rpcuser=blocks
rpcpass=block!1
rpclisten=0.0.0.0
datadir=/home/ubuntu//.btcd/data
#txindex=1
#addrindex=1

btcctl.conf is:
rpcuser=blocks
rpcpass=block!1

I didnt find same issue。I am very confused. Need some help, thank you very much

**Comment by fusion44** [comment]
You need to add your IP to the certificates. BTCD comes with the gencerts utility. For example to add the IP 1.2.3.4 to the rpc.cert file you use the command line:
`gencerts -d . -H 1.2.2.4 -f`
This will regenerate the certificate, write it to the current directory and overwrite existing files. You'll have to copy the file over to the client again.

```
gencerts --help
Usage:
  gencerts [OPTIONS]

Application Options:
  -d, --directory= Directory to write certificate pair
  -y, --years=     How many years a certificate is valid for (10)
  -o, --org=       Organization in certificate (gencerts)
  -H, --host=      Additional hosts/IPs to create certificate for
  -f, --force      Force overwriting of any old certs and keys

Help Options:
  -h, --help       Show this help message
```
