### ISSUE TITLE
btcctl: command not found

### ISSUE THREAD

**Issue by rahilzebpay** [btcsuite/btcd#1389]
I have followed the steps to lightning network tutorial (setting up with simnet). But facing issue with `btcctl`

`btcctl: command not found`

**Comment by molxyz** [comment]
@rahilzebpay Update to latest master.
```
cd $GOPATH/src/github.com/btcsuite/btcd
git fetch
git checkout origin/master
GO111MODULE=on go install -v . ./cmd/...
```
