### ISSUE TITLE
btcctl: command not found

### ISSUE THREAD

**Issue by anonymouse212** [btcsuite/btcd#1401]
Hi, I'm having trouble getting btcctl working. I've followed the steps in various posts about this (LND slack, here, etc) but I hit an issue when I try to use "GO1111MODULE=on go install -v . ./cmd/..."

It looks like it can't find a bunch of stuff, but I followed the instructions to a T, so I'm not sure what went wrong. Thanks in advance!

This is the error:
user@user-XPS-8930:~/gocode/src/github.com/btcsuite/btcd$ GO1111MODULE=on go install -v . ./cmd/...
database/ffldb/db.go:22:2: cannot find package "github.com/btcsuite/goleveldb/leveldb" in any of:
	/usr/lib/go-1.10/src/github.com/btcsuite/goleveldb/leveldb (from $GOROOT)
	/home/user/gocode/src/github.com/btcsuite/goleveldb/leveldb (from $GOPATH)
database/ffldb/db.go:23:2: cannot find package "github.com/btcsuite/goleveldb/leveldb/comparer" in any of:
	/usr/lib/go-1.10/src/github.com/btcsuite/goleveldb/leveldb/comparer (from $GOROOT)
	/home/user/gocode/src/github.com/btcsuite/goleveldb/leveldb/comparer (from $GOPATH)
database/ffldb/db.go:24:2: cannot find package "github.com/btcsuite/goleveldb/leveldb/errors" in any of:
	/usr/lib/go-1.10/src/github.com/btcsuite/goleveldb/leveldb/errors (from $GOROOT)
	/home/user/gocode/src/github.com/btcsuite/goleveldb/leveldb/errors (from $GOPATH)
database/ffldb/db.go:25:2: cannot find package "github.com/btcsuite/goleveldb/leveldb/filter" in any of:
	/usr/lib/go-1.10/src/github.com/btcsuite/goleveldb/leveldb/filter (from $GOROOT)
	/home/user/gocode/src/github.com/btcsuite/goleveldb/leveldb/filter (from $GOPATH)
database/ffldb/db.go:26:2: cannot find package "github.com/btcsuite/goleveldb/leveldb/iterator" in any of:
	/usr/lib/go-1.10/src/github.com/btcsuite/goleveldb/leveldb/iterator (from $GOROOT)
	/home/user/gocode/src/github.com/btcsuite/goleveldb/leveldb/iterator (from $GOPATH)
database/ffldb/db.go:27:2: cannot find package "github.com/btcsuite/goleveldb/leveldb/opt" in any of:
	/usr/lib/go-1.10/src/github.com/btcsuite/goleveldb/leveldb/opt (from $GOROOT)
	/home/user/gocode/src/github.com/btcsuite/goleveldb/leveldb/opt (from $GOPATH)
database/ffldb/db.go:28:2: cannot find package "github.com/btcsuite/goleveldb/leveldb/util" in any of:
	/usr/lib/go-1.10/src/github.com/btcsuite/goleveldb/leveldb/util (from $GOROOT)
	/home/user/gocode/src/github.com/btcsuite/goleveldb/leveldb/util (from $GOPATH)

**Comment by totaloutput** [comment]
you probably need to fix your GOROOT and GOPATH.. if you want to have it running in container (which is easier and cleaner), you can follow the steps from https://medium.com/@min_3320/how-to-use-docker-to-setup-multiple-bitcoin-test-nodes-on-your-own-mac-phase-ii-btcd-2ebdd473b720

**Comment by molxyz** [comment]
@anonymouse212 
```
but I hit an issue when I try to use "GO1111MODULE=on go install -v . ./cmd/..."
This is the error:
user@user-XPS-8930:~/gocode/src/github.com/btcsuite/btcd$ GO1111MODULE=on go install -v . ./cmd/...
database/ffldb/db.go:22:2: cannot find package "github.com/btcsuite/goleveldb/leveldb" in any of:
```
You have this error because your line of executable command has one extra number `1` 
The correct guide to get btcctl to work is as follows: 
```
$ cd $GOPATH/src/github.com/btcsuite/btcd
$ GO111MODULE=on go install -v . ./cmd/...
```
Notice there are only three digit of that number `1`, not four.
Here's the guide page:  https://github.com/btcsuite/btcd#installation
