### ISSUE TITLE
Possible race condition in (noncritical) script execution logging

### ISSUE THREAD

**Issue by l0k1verloren** [btcsuite/btcd#1403]
I may of course have muddled up something in my fork but I couldn't say how far back since I saw a replay running with trace turned on. So this may not be a concrete issue, but just looking at the output I have, maybe it isn't irrelevant.

The conflict I see looks like this on my codebase, but the function names and receiver types are the same:

```
==================
WARNING: DATA RACE
Read at 0x00c0003c4168 by goroutine 87:
  git.parallelcoin.io/dev/pod/pkg/chain/tx/script.(*Engine).validPC.func1()
      /home/loki/src/git.parallelcoin.io/dev/pod/pkg/chain/tx/script/engine.go:216 +0x128

Previous write at 0x00c0003c4168 by goroutine 181:
  git.parallelcoin.io/dev/pod/pkg/chain/tx/script.(*Engine).Step.func1()
      /home/loki/src/git.parallelcoin.io/dev/pod/pkg/chain/tx/script/engine.go:472 +0x3e

Goroutine 87 (running) created at:
  git.parallelcoin.io/dev/pod/pkg/chain/tx/script.(*Engine).validPC()
      /home/loki/src/git.parallelcoin.io/dev/pod/pkg/chain/tx/script/engine.go:208 +0x6f
  git.parallelcoin.io/dev/pod/pkg/chain/tx/script.(*Engine).DisasmPC()
      /home/loki/src/git.parallelcoin.io/dev/pod/pkg/chain/tx/script/engine.go:234 +0x3d
  git.parallelcoin.io/dev/pod/pkg/chain/tx/script.(*Engine).Execute.func1()
      /home/loki/src/git.parallelcoin.io/dev/pod/pkg/chain/tx/script/engine.go:554 +0x67
  git.parallelcoin.io/dev/pod/pkg/util/cl.NewSubSystem.func1.6()
      /home/loki/src/git.parallelcoin.io/dev/pod/pkg/util/cl/clog.go:182 +0x93
  git.parallelcoin.io/dev/pod/pkg/util/cl.init.0.func1()
      /home/loki/src/git.parallelcoin.io/dev/pod/pkg/util/cl/clog.go:319 +0x1af2

Goroutine 181 (finished) created at:
  git.parallelcoin.io/dev/pod/pkg/chain/tx/script.(*Engine).Step()
      /home/loki/src/git.parallelcoin.io/dev/pod/pkg/chain/tx/script/engine.go:470 +0x3bd
  git.parallelcoin.io/dev/pod/pkg/chain/tx/script.(*Engine).Execute()
      /home/loki/src/git.parallelcoin.io/dev/pod/pkg/chain/tx/script/engine.go:545 +0x88
  git.parallelcoin.io/dev/pod/pkg/chain.(*txValidator).validateHandler()
      /home/loki/src/git.parallelcoin.io/dev/pod/pkg/chain/scriptval.go:103 +0x4f6
==================

```

It isn't likely to be terribly critical in any way, only of interest to mainly developers working on this codebase (this would include decred I guess, maybe, if they use the same script language), and only for the actual logging output.

`vm.scriptIdx` and `vm.scriptOff` are the variables in `engine.go` inside txscript, inside btcd, that  are being read and written concurrently. I am using a channel lock to close this race condition for the moment but maybe someone more familiar with this code might have a better idea how to prevent it.

Functions with the code is Step() and validPC()

It seems highly unlikely to me that not having much familiarity with this code and seeing it concurrently accessing variables that I have introduced this as an additional bug, but it's not very serious in that it most likely has no security impact or opening a vulnerability since this code just isn't running in production. The use of this shared variable must surely have been a consciously introduced feature.

**Comment by Roasbeef** [comment]
Each validator makes its own instance of `txscript.Engine`. It appears that you've modified this code in your fork.
