### ISSUE TITLE
How do I create a P2SH-P2WPKH address?

### ISSUE THREAD

**Issue by lxjhk** [btcsuite/btcd#1414]
How do I create a P2SH-P2WPKH address (P2WPKH nested in BIP16 P2SH)?

**Comment by lxjhk** [comment]
I have looked at "Address.go". I think the ability to generate P2SH-P2WPKH is not included. Shall I create a PULL request?

**Comment by lxjhk** [comment]
Ref -> https://bitcoincore.org/en/segwit_wallet_dev/#creation-of-p2sh-p2wpkh-address

**Comment by Roasbeef** [comment]
Here's an example: https://github.com/btcsuite/btcwallet/blob/5fb94231d0c814f02ffc3110eee588278151b4e1/waddrmgr/address.go#L360
