### ISSUE TITLE
Add regtest flag to btcctl

### ISSUE THREAD

**Issue by dannypaz** [btcsuite/btcd#1456]
BTCD allows a regtest mode, but you are unable to use the btcctl due to a missing `--regtest` flag. The current workaround is to map the regtest ports to simnet, which allows you to then use `--simnet` to access any commands.

**Comment by darwin** [comment]
FYI, in simverse project as a workaround I apply these two patches to get regtest working:
https://github.com/darwin/simverse/tree/master/recipes/cookbook/scaffold/docker/btcd/patches

https://github.com/darwin/simverse/blob/master/recipes/cookbook/scaffold/docker/btcd/Dockerfile
