### ISSUE TITLE
Source tree formatting

### ISSUE THREAD

**Issue by harryrford** [btcsuite/btcd#1470]
Thought it would be important to point out that the entire source tree has not been correctly formatted.

This causes inconsistently with indentation and alignment across the codebase.

I think it is especially important for open-source code to use strict formatting, such as Geth PR's requiring you to run ``gofmt`` in order to be merged.

Let me know what you think.

**Comment by jcvernaleo** [comment]
Travis has been enforcing the use of gofmt and a number of linters on this code base since almost the beginning (see https://github.com/btcsuite/btcd/blob/master/goclean.sh) so I'm not sure what specifically you are referring to.  Do you have an example?

**Comment by jcvernaleo** [comment]
No examples given, and we already test for this, so closing the issue.  If you do find a specific example, please feel free to reopen the issue or open a new one.
