### ISSUE TITLE
Make btcd aware of NoFreelistSync option

### ISSUE THREAD

**Issue by darwin** [btcsuite/btcd#1473]
I believe recent merge https://github.com/btcsuite/btcwallet/pull/648 broke btcd when trying to create a temp wallet. Btcd seems to be unaware of no-freelist-sync option and a RPC call to btcwallet fails with this error message: 

```
Unable to create wallet: invalid arguments to bdb.Create -- expected database path and no-freelist-sync option
```

I believe btcwallet should be less strict [here](https://github.com/btcsuite/btcwallet/pull/648/files#diff-7a56bf5fd9751a56fbe6ea8277a16650R19) and issue a warning only or alternatively btcd should be made aware of this option.

For reference see:
https://github.com/btcsuite/btcwallet/pull/648#issuecomment-539237987
https://travis-ci.org/darwin/simverse/builds/594826741#L4574

**Comment by Roasbeef** [comment]
`btcd` is _entirely_ unaware of `btcwallet`, so config changes in `btcwallet` don't affect `btcd` as they're completely independent.

**Comment by wpaulino** [comment]
Yeah this looks more like an issue within `btcwallet` where the changes weren't made everywhere they needed to.
