### ISSUE TITLE
Does "Headers First" mode download blocks in parallel?

### ISSUE THREAD

**Issue by seafooler** [btcsuite/btcd#1486]
After flipping through the codes, I find `btcd` will not download blocks in parallel in the 'Headers First' mode.

Just want to confirm it, in case I missed something important.

If I am right, will it support the parallel blocks download and when?

Thanks a lot!

**Comment by Roasbeef** [comment]
Correct that it doesn't currently download blocks in parallel. However, parallel block download is on the roadmap. At this time, I can't give any prospective timing w.r.t when the feature will land. Over the past year or so, a number of preparatory changes have been made, some of them not yet merged.
