### ISSUE TITLE
Suspicious go.sum checksum mismatch

### ISSUE THREAD

**Issue by mediocregopher** [btcsuite/btcd#1487]
Got this today randomly, after not having touched the `go.mod` entry for the package:

```
verifying github.com/btcsuite/btcd@v0.20.0-beta: checksum mismatch
        downloaded: h1:DnZGUjFbRkpytojHWwy6nfUSA7vFrzWXDLpFNzt74ZA=
        go.sum:     h1:PamBMopnHxO2nEIsU89ibVVnqnXR2yFTgGNc+PdG68o=
```

Doing `go clean -modcache` and then `go mod download` did not fix it. Doing `GOPROXY=direct go mod download` did fix it, however.

Which leads me to ask... is `proxy.golang.org` ok?

**Comment by jrick** [comment]
https://github.com/btcsuite/btcwallet/issues/657

**Comment by mediocregopher** [comment]
@jrick interesting, so that error is the inverse of this one. I wonder which hash is the correct one, I would think it's the `direct` version, right?

**Comment by jrick** [comment]
What probably happened is that a tag was created, the proxy cached it and [permanently saved the go.sum to the public append-only transparent sum log](https://go.googlesource.com/proposal/+/master/design/25530-sumdb.md), and then the origin repo was retagged with something different.

I would personally always trust the sum saved on the sum server, and the sum in btcwallet's go.sum file, as this is likely the original tagged code.  Retagging origin with something different is indistinguishable from a MITM attack or a compromised git repo or github account.

**Comment by mediocregopher** [comment]
I guess the _truly_ correct answer is to pick the hash which has been audited, but barring that I agree the one tagged first is less suspicious.

**Comment by mediocregopher** [comment]
Is it possible to confirm that the repo was retagged? Would it be possible to tag a `v0.20.1-beta` so that we can remove the inconsistency between people hitting `direct` and people hitting a proxy?

**Comment by jrick** [comment]
> Is it possible to confirm that the repo was retagged?

Not with git.  Unlike some other dvcs tools like mercurial which save tags to a file that is tracked in the repo, git tags can be changed without any audit trail.

> Would it be possible to tag a `v0.20.1-beta` so that we can remove the inconsistency between people hitting `direct` and people hitting a proxy?

Yes, the solution is never to retag, but to push new tags with higher versions, and optionally push a tag indicating that some other tag has been deprecated.

**Comment by jrick** [comment]
CC @Roasbeef since github displays you as the one who pushed the tag.

**Comment by upklio** [comment]
I synced to 48% and the server shut down. On trying to restart:

```
Unable to start server on [:8333]: block data for block 0000000000000000200ca9e48cecda84cc78c834d82f834bd7602d09e3727f9a checksum does not match - got 5e2a4cc2, want 0
```

...I'm running in pruned mode?

**Comment by Roasbeef** [comment]
Yep, the latest version was retagged. AFAICT, `proxy.golang.org` has the correct `go.sum`, however it seems that depending on which version of Go you used, you may have downloaded the incorrect sum (pre new tag) in the past.

**Comment by upklio** [comment]
I'm running go 1.13.4, but not sure if that's the problem?

I'm trying to sync with `prune=1` enabled with `txindex=1` and `addrindex=1` - don't know if that's preventing my sync from working?

**Comment by mediocregopher** [comment]
@upklio I think you might be in the wrong issue :/

**Comment by upklio** [comment]
My bad, will create a separate one.

**Comment by mediocregopher** [comment]
@Roasbeef how do you feel about making a `v0.20.1-beta` tag to fix the inconsistency? It could be on the same commit as `v0.20.0-beta` is currently on, but it would help clear up confusion and broken builds between different projects.

**Comment by Roasbeef** [comment]
@mediocregopher new tag pushed.

**Comment by nordicdyno** [comment]
This retagging had broken my project build, where I have `btcd` as transitive dependency from my direct dependency `go-ethereum` .
I fixed it by updating `btcd` version manually, it feels dirty but work. And I really hope what you guys never ever will do such retagging-thing again. Please!
