### ISSUE TITLE
Checksum does not match error when syncing.

### ISSUE THREAD

**Issue by upklio** [btcsuite/btcd#1489]
When I try to sync I get to 48% and the server shuts down. On trying to restart:

```
Unable to start server on [:8333]: block data for block 0000000000000000200ca9e48cecda84cc78c834d82f834bd7602d09e3727f9a checksum does not match - got 5e2a4cc2, want 0
```

I'm running go `1.13.4`.

I'm trying to sync with `prune=1` enabled with `txindex=1` and `addrindex=1`.

...I'm using the bchd fork but feel the error is irrelevant to that.

**Comment by Roasbeef** [comment]
This isn't the `bchd` repo.
