### ISSUE TITLE
btcd/btcec a Go Module

### ISSUE THREAD

**Issue by Baha-sk** [btcsuite/btcd#1495]
There is interest in using btcd/btcec package in [Go Jose](https://github.com/square/go-jose) project to support secp256k1 algorithm.

Can this package have its own go.mod and go.sum files? 

This way, Go Jose can import btcec package alone (without loading the full btcd project).

If adding go mod in this subpackage is too complex, then probably extract this package into its own GitHub repo and reference it here would make more sense (it's the easiest approach as having sub packages as go modules can make maintaining imports and revisions a bit nasty, read [here](https://github.com/golang/go/wiki/Modules#should-i-have-multiple-modules-in-a-single-repository).. so extracting btcec in a separate repo is the easiest/best way)

Your help is much appreciated.

ref: https://github.com/square/go-jose/issues/263#issuecomment-555838446

**Comment by Baha-sk** [comment]
It looks like btcec used to exist as a separate project (5 years ago).
see: https://github.com/btcsuite/btcec

I believe, at the time, go mod didn't exist and there was no benefit in having a separate project. But now, with the introduction of go mod, it makes more sense to have btcec as a separate project.

**Comment by chappjc** [comment]
You may find the same primitives in https://github.com/decred/dcrd/tree/master/dcrec.  That fork is maintained by the original btcsuite authors and it provides a module as you need.

**Comment by Baha-sk** [comment]
Thanks @chappjc ... 
we will try to introduce this fork as reference in go-jose (as per @kdimak mention above)

I'm closing this issue.
