### ISSUE TITLE
Project Velocity

### ISSUE THREAD

**Issue by jakesyl** [btcsuite/btcd#1530]
So I want to prefix this with saying the entire community is extremely thankful for @Roasbeef stepping up as a co-maintainer and leading this after the [decred](https://github.com/decred/dcrd) teams activity decreased and they focused on their altcoin. Your contributions here/leadership on lnd are awesome (and I'm not kidding, there's literally a [reddit thread](https://www.reddit.com/r/Bitcoin/comments/7qj0b4/why_is_lightning_network_being_developed_on_btcd/dspk5be/?utm_source=share&utm_medium=web2x) refusing to believe your one person)

With that being said, we've got a pretty substantial backlog of pull requests 100+, a lot of which are approved for review than going stale or just not getting merged after a few months. Would it make sense to add more maintainers or figure out a peer review/ci workflow where you don't have to personally merge in every PR?

Just trying to figure out if we can do anything to get some of these PR's in more quickly or think about a more long running fork

**Comment by Roasbeef** [comment]
If you want to pitch in, I think you can begin by simply starting to help to review PRs in the backlog. W.r.t the number of open prs, it's typical for open source projects that some contributions may just never be merged/accepted.

**Comment by jakesyl** [comment]
Will do. I've got a few code reviews out now (and know @torkelrogstad has been extremely helpful in reviewing some of mine, e.g. #1503)

My point on the stale contributions is that _generally_ 3/4-year-old stuff with a bunch of merge conflicts should generally be closed and the PR's that are opened/reviewed  (e.g. #1467 which fixes #1466 and #1519) should probably be merged.

The longer these things stay open, the more merge conflicts occur and the slower the subsequent release cycles. I will definitely start reviewing some more of these PR's though

**Comment by panzarino** [comment]
@Roasbeef / @davecgh, as far as getting these things merged - can you tell us a bit about the process. I'm seeing the last release was November and nothing has been merged since then. Can you shine a little light on what the process of getting this stuff merged normally looks like?

**Comment by jcvernaleo** [comment]
I just merged #1537 and and going to make some attempt to both triage issues/PRs and do some reviewing and merging where possible.  This was discussed with @Rjected and @someone235 on irc.

**Comment by jakesyl** [comment]
@jcvernaleo I saw this conversation, but missed you guys buy a few hours. I'm generally on irc as `jakesyl` and will catch up with you guys at some point. I've stopped doing PR's here because of how stale a lot of my current ones were getting, but happy to begin again if things are getting merged

**Comment by jakesyl** [comment]
Also @jcvernaleo happy to go through and triage if we can tag (no permissions right now) - Went through about 20 pr's and approved/requested changes as per @Roasbeef a few weeks ago, but that's all we can do. Those 20 represent almost all of the non-stale commits

**Comment by jcvernaleo** [comment]
Since we have a plan for triaging PRs/issues, getting some more folks to have triage permissions, and dealing with the PR backlog, think we can close this issue?

**Comment by jakesyl** [comment]
Yep.

**Comment by jakesyl** [comment]
![image](https://user-images.githubusercontent.com/6392429/75881696-949a6480-5ded-11ea-9796-4605ed20b1c5.png)
![image](https://user-images.githubusercontent.com/6392429/75881712-9a904580-5ded-11ea-8d49-7587c63bc7f8.png)


(For anyone confused)

**Comment by jcvernaleo** [comment]
Yeah, I meant to reproduce some of that chat here but got distracted tagging things :)

**Comment by onyb** [comment]
@jcvernaleo @jakesyl Please count me in on this. I don't have triage permissions, but tried reviewing/reviving some stale PRs/issues here: https://github.com/btcsuite/btcutil

If it helps, we can start a GitHub Project board to make sure open PRs are not lost forever and have a clear path towards being merged (at least the ones that are ready). What do you think?

**Comment by jcvernaleo** [comment]
@onyb no objection to a github project board although I have no great idea how to best structure it myself.  If you have clear ideas, might be easiest to open an issue for it telling me what you'd need me to do.  I do plan on getting back to some of the open PRs soon.  I guess not too surprisingly, a global plague has left me with less time and focus than usual, but trying to get back into a kind of place (for work and projects anyway).

**Comment by jakesyl** [comment]
@onyb I think we've got a pretty clear path around the ones that are ready. As I've mentioned, I'm pretty busy the next week and a half or so but after that I've got a few PRs that I'm going to put some finishing touches on and merge
