### ISSUE TITLE
[btcec] why cannot the fieldValue has magnitude of 2 after first reduction in `fieldVal.Normalize()`

### ISSUE THREAD

**Issue by sammyne** [btcsuite/btcd#1535]
https://github.com/btcsuite/btcd/blob/f3ec13030e4e828869954472cbc51ac36bee5c1d/btcec/field.go#L312-L316

Wouldn't it be possible that the magnitude is 2 due to the carry bit?

**Comment by Rjected** [comment]
What's the reason for closing? Just curious
