### ISSUE TITLE
milestones and release versions

### ISSUE THREAD

**Issue by jcvernaleo** [btcsuite/btcd#1545]
There are two milestones set for the project, `0.13.0` and `0.14.0`.  Since those were made, there has already been an `0.20.0-beta` release.

I assume this means we that the next release would be `0.20.1` or something like that and `0.13` and `0.14` are dead (which is totally fine with me).  Just want to make sure I'm not missing something in terms of the versioning plans before I go and close those two milestones.

@Roasbeef ? @jakesyl?  anyone else who wants to chime in that github's tab complete isn't getting for me?

**Comment by jakesyl** [comment]
I’m guessing this is related to the bitcoins version numbers, but we definitely need this documented somewhere 
![D565B00B-913A-4520-AB9C-E61B4040FE41](https://user-images.githubusercontent.com/6392429/76045609-a41fc780-5f2b-11ea-98c1-a092dd6a759a.png)

**Comment by onyb** [comment]
> I assume this means we that the next release would be 0.20.1 or something like that.

@jcvernaleo All our previous releases have been beta versions, so let's stick to it for now. The next release is going to be **`0.21.0-beta`**.

Let's also close the 0.13 and 0.14 milestones, and start a new one for 0.22. I think we should think about introducing Go modules in our packages as part of the 0.22 milestone, so we could introduce potentially breaking API changes without bumping the major version of btcd.

**Comment by jcvernaleo** [comment]
@onyb agreed on all points.

**Comment by jcvernaleo** [comment]
I closed the two old milestones and opened an 0.22.0 milestone for the release after this one (baring point releases of course) so closing this issue.
