### ISSUE TITLE
Invalid private key generation

### ISSUE THREAD

**Issue by klim0v** [btcsuite/btcd#1551]
I fixed the error. Can you accept the [pull request](https://github.com/btcsuite/btcutil/pull/161) and update the dependency?

**Comment by LasTshaMAN** [comment]
@klim0v can this be closed now (as well as https://github.com/btcsuite/btcutil/pull/161) ? Looks like https://github.com/btcsuite/btcutil/pull/182 has been merged already fixing this issue.
