### ISSUE TITLE
OnFilteredBlockConnected function transactions parameter is empty

### ISSUE THREAD

**Issue by i11m20n** [btcsuite/btcd#1566]
Hello, I use Golang to write the NotifyBlocks registration program, in the length of the transaction parameter in the OnFilteredBlockConnected callback function is 0.

network: mainnet

![image](https://user-images.githubusercontent.com/13911593/79864023-5263cb80-840b-11ea-8635-f58f025677f6.png)

![image](https://user-images.githubusercontent.com/13911593/79864188-9e167500-840b-11ea-89eb-fc8b096ef347.png)

BlockHash: 00000000000000000001250d4a86d2b346caa79d8d94e5176f7cf2f024da2336

**Comment by Roasbeef** [comment]
This is expected, you need to call the filter load method first. Only when items match the filter will transactions be specified.
