### ISSUE TITLE
Consider using an org-wide GitHub Projects board

### ISSUE THREAD

**Issue by onyb** [btcsuite/btcd#1568]
As a new contributor, who is looking for issues to take up, I don't have a global view of which features should be worked upon, or the general direction where the project is heading. This is in addition to the discussion regarding the health of the project in #1530.

@jakesyl and @jcvernaleo recently did a great job triaging issues and stale PRs using labels. It would be great to now categorize them into buckets, and create wishlist-issues for the community to take up. A giant list of triaged items is available in #1530.

The objective is to make the life of maintainers easy by giving them a clear picture of what needs their attention and also gather the community towards a goal.

I propose we set up some [GitHub Project boards](https://help.github.com/en/github/managing-your-work-on-github/about-project-boards), and see if it helps us cut the clutter. Let's limit the number of boards to one or two for now, and make it org-wide to avoid dividing the attention of maintainers.

#### Topical boards

Examples: RPC, Elliptic Curve, Packaging, BIPs
Candidates: #1546

#### Permanent boards

Examples: Technical debt, documentation, test coverage

### Columns

Below are the columns I propose for the boards:

```
To Do        →  Not started (wishlist items, new bug reports)
Stale        →  Abandoned issues/PRs; needs someone to pick up.
In Progress  →  Actively being worked on
To Review    →  Attention reviewers and maintainers
Done         →  ✔️ ✔️ ✔️
```

Feedback?

**Comment by jakesyl** [comment]
I've got no objection - this seems like a great step in the right direction

**Comment by Rjected** [comment]
I think this is a great idea, it addresses some of the issues I've had getting into development as well

**Comment by jcvernaleo** [comment]
So what do we want as the first two boards (let's limit to that many for the first try)?

**Comment by onyb** [comment]
As per our discussion on IRC, we decided to have the following two boards for now:
- **RPC**: #1546, and RPC development in general
- **Dev** / **General**: Everything else that's not RPC

In future, we can obviously split things further if we feel the need.

**Comment by jcvernaleo** [comment]
Two boards made:
https://github.com/orgs/btcsuite/projects/

**Comment by onyb** [comment]
Great! Closing this issue.
