### ISSUE TITLE
Question: Secp256k1 it's written from scratch in go? 

### ISSUE THREAD

**Issue by tiero** [btcsuite/btcd#1570]
Hello!

I'm right saying that the secp256k1 curve has been implemented from scratch in go, isn't a cgo binding of the C library in bitcoin-core one right?

Someone knows what the reason for this choice? Easier to cross-compile?

Thanks

**Comment by jcvernaleo** [comment]
cgo is great if you absolutely need to link to c code (for example, if you need to link to CUDA or opencl libraries) but if you aren't absolutely stuck doing  it, there are big advantages to pure go.  The cross compiling bit you mentioned is one.  The race detector is another.  Being able to use the various go linters is also a big plus for pure go over cgo.

Also, at least for most people, go is easier to read than C so having things in go is a plus on that front.

Does that answer what you are asking, or am I missing some part of the question?

**Comment by tiero** [comment]
That's great! All of these points resonate well with me, just that you know...people every time repeat never "roll your own crypto". 

I want to port to native Go also [`secp256k1-zkp`](https://github.com/elementsproject/secp256k1-zkp). Would you suggest to start of from this implementation?

**Comment by jrick** [comment]
> never "roll your own crypto"

someone has to roll it.

in this case, these aren't new bespoke algorithms being written, but well known ones simply being implemented in another language.

**Comment by jcvernaleo** [comment]
Yeah, agree with @jrick, 'never roll your own' mostly means don't come up with your own crypto algorithm unless you really know what you are doing.  Reimplimenting is a much safer task than that.

**Comment by Roasbeef** [comment]
Closing as the question seems to be answered.
