### ISSUE TITLE
Where is the msi file?

### ISSUE THREAD

**Issue by c78867886** [btcsuite/btcd#1597]
I am using Windows 10 and try to install btcd with msi file.
Where is the msi file? Cannot find it in the release section.

**Comment by Rjected** [comment]
You can download the `.exe` files for `btcd` and `btcctl` directly from https://github.com/btcsuite/btcd/releases/tag/v0.20.1-beta. It is in `btcd-windows-amd64-v0.20.1-beta.zip`, and when you unzip the directory you'll see the `.exe` file. Does this help?

**Comment by c78867886** [comment]
> You can download the `.exe` files for `btcd` and `btcctl` directly from https://github.com/btcsuite/btcd/releases/tag/v0.20.1-beta. It is in `btcd-windows-amd64-v0.20.1-beta.zip`, and when you unzip the directory you'll see the `.exe` file. Does this help?

Thank you for answering.
After I have `btcd.exe` and `btcctl.exe`, what can I do with these two files?

**Comment by onyb** [comment]
* `btcd.exe` allows you to spawn a Bitcoin full node.
* `btcctl.exe` allows you to communicate with the node, by issuing RPC commands. To view the full list of commands, execute `btcctl.exe --listcommands` in your shell.

If it answers your question, please consider closing this issue.
