### ISSUE TITLE
Is it possible to migrate downloaded full node data to other machine?

### ISSUE THREAD

**Issue by c78867886** [btcsuite/btcd#1600]
My internet is too slow so I use EC2 instance to download full node data.
Is it possible to migrate all those data to my local so I can just update the latest block in the future?

I know for bitcoind we can just move certain folders to the new machine to achieve that but not sure if we can do the same thing to btcd.

Just to clarify, I am not asking how to migrate certain data from EC2 to a local machine. Just want to know it is possible to migrate btcd full node data to a new machine.

Thank you guys!

**Comment by jcvernaleo** [comment]
The block data all goes where the `--datadir` option tells it to.  That defaults to `$HOME/.btcd/data`.  As long as you cleanly shut btcd down you can copy that to another machine and point btcd to it.

**Comment by c78867886** [comment]
> The block data all goes where the `--datadir` option tells it to. That defaults to `$HOME/.btcd/data`. As long as you cleanly shut btcd down you can copy that to another machine and point btcd to it.

Thank you sir! This is really helpful! I have a last question here.
Can I migrate those block data, which is from Ubuntu, to Windows?
That is, Can different OS share the same block data?
Thank you again!

**Comment by jcvernaleo** [comment]
I have no access to any windows machines so I don't know.  I think I've moved things from ubuntu to openbsd or vice versa in the past but that was a long time ago.  You can let things sync for just a few blocks and test to be sure.

**Comment by c78867886** [comment]
> I have no access to any windows machines so I don't know. I think I've moved things from ubuntu to openbsd or vice versa in the past but that was a long time ago. You can let things sync for just a few blocks and test to be sure.

I will try it and post the result here later. Thank you sir!

**Comment by jcvernaleo** [comment]
@c78867886 Did you ever test what you wanted?  Wondering if I can close this issue.

**Comment by c78867886** [comment]
You can close it. Syncing btcd blocks is impossible. I run it on an `t3.medium` EC2 instance and it takes forever to sync blocks...

**Comment by jcvernaleo** [comment]
There is a PR that speeds up the sync dramatically (can't find it offhand).  We have a release coming up hopefully this week and then getting that in is high priority for next release.

**Comment by c78867886** [comment]
> There is a PR that speeds up the sync dramatically (can't find it offhand). We have a release coming up hopefully this week and then getting that in is high priority for next release.

Does the PR approved? I try to sync and still really slow...
