### ISSUE TITLE
addblock fails to import bootstrap.dat

### ISSUE THREAD

**Issue by roosmaa** [btcsuite/btcd#162]
It would seem the addblock utility fails to import the [official] bootstrap.dat from bitcoin.org.

```
$ addblock -i ~/Downloads/bootstrap.dat
09:08:03 2014-08-11 [INF] Loading block database from '/Users/me/Library/Application Support/Btcd/data/mainnet/blocks_leveldb'
09:08:03 2014-08-11 [INF] Block database loaded with block height -1
09:08:03 2014-08-11 [INF] Starting import
09:08:03 2014-08-11 [ERR] import file contains block 00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048 which does not link to the available block chain
```

As a workaround, is there any way to import the data to btcd after having imported it to bitcoind? Running bitcoind and btcd at the same time to "import" the blocks over bitcoin protocol?

**Comment by rickw** [comment]
I'm getting the same issue on updated master now trying to import a blockchain derived form my Bitcoin-Qt install. I get a fork that doesn't reorganize at height 298361... my Qt is up to date as of 2 hours ago on the blockchain... any ideas? Thanks

**Comment by davecgh** [comment]
Did you export to a linear file with `linearize.py ?  If you're just using the existing Bitcoin-Qt files it won't work since it's not the correct format for `bootstrap.dat`.  A `bootstrap.dat` must not contain any side chains and all blocks must be in order (this is what `linearize.py` does).

**Comment by rickw** [comment]
Ok thanks, I'll use that... apologies for my ignorance.
