### ISSUE TITLE
Import data from original core-bitcoind

### ISSUE THREAD

**Issue by DrMartiner** [btcsuite/btcd#1637]
Hello,

The first of all thanks a lot for this project. I have a question: may I import data from bitcoin core?

Best regards

**Comment by jakesyl** [comment]
I suppose it's possible to export using a tool like [this](https://github.com/ruqqq/blockchainparser) and parse to the btcd format. I'm not sure this would be advisable. 

As a side note, you can also go the otherway, see [coinbase exporter](https://github.com/coinbase/btcexport)

**Comment by DrMartiner** [comment]
> I suppose it's possible to export using a tool like [this](https://github.com/ruqqq/blockchainparser) and parse to the btcd format. I'm not sure this would be advisable.
> 
> As a side note, you can also go the otherway, see [coinbase exporter](https://github.com/coinbase/btcexport)

Great! Many thanks for your answer

**Comment by jakesyl** [comment]
Cool- closing this. If you have any more questions don't hesitate to reopen!
