### ISSUE TITLE
btcd.rawrpccert unable to configure

### ISSUE THREAD

**Issue by peername** [btcsuite/btcd#1655]
Hi,

I am trying to connect LND to a remote btcd node. RPC certificate is required. btcd.rpccert is working fine but I want to pass the certificate as a command parameter. Using a file is not convenient for me.

I tried to use btcd.rawrpccert but I can't format the certificate in the correct format. Each time I get the following error:

"LTND: unable to create chain control: encoding/hex: invalid byte: U+004D 'M'"

I tried everything and ask for help / example. Thanks.

**Comment by onyb** [comment]
> I tried to use btcd.rawrpccert but I can't format the certificate in the correct format.

This could be an issue with lnd itself, or you may be using the wrong certificate format. Make sure your certificate is encoded in PEM format. You can verify it is by doing:

```
openssl x509 -text < certificate.pem
```

**Comment by pfergi42** [comment]
Having same issue here, getting "TLS handshake error". My remote LND node can't connect to my Btcd rcp...
