### ISSUE TITLE
change command getnewaddress

### ISSUE THREAD

**Issue by medeirosfalante** [btcsuite/btcd#1703]
in bitcoin core rpc api the method [getnewaccount](https://developer.bitcoin.org/reference/rpc/getnewaddress.html) have a 2 params [label] [address_type] but in btcd/rpcclient have 1 param [account]  this is corrent ?

**Comment by Roasbeef** [comment]
Bitcoin Core changed their version, but the `rpcclient` still only accepts the args of the initial version. You can either craft a raw RPC request to pass in that new JSON, or make a PR to extend the rpcclient.

**Comment by chappjc** [comment]
Assuming this issue refers to `getnewaddress`, this would be resolved by https://github.com/btcsuite/btcd/issues/1703 plus https://github.com/btcsuite/btcwallet/pull/783
