### ISSUE TITLE
Windows missing .msi installer

### ISSUE THREAD

**Issue by HasseM** [btcsuite/btcd#1708]
It seems that the windows binaries are missing the msi installer. 
It just contains 2 files only, btcctl.exe and btcd.exe.
Or please explain how to install?

**Comment by jcvernaleo** [comment]
The mention of the msi is very outdated and should be removed from the docs.  Releases are built with the standard go build process which produces binaries for many platforms including windows.  In all cases, using the binaries just requires putting them somewhere in your path.  No installer needed or provided.

Sorry I can't give any more specific instructions.  Not a windows user.

**Comment by HasseM** [comment]
ic, got it. need to open a cmd prompt and start btcd. By just clicking the file from explorer, nothing seem to happen because it flashes an error about conf file. When running it from cmd prompt, it remains visible.

Anyhow: issue is that msi has to be removed from docs... ;-)

**Comment by jcvernaleo** [comment]
Totally agree we need an issue there.  Just opened #1710
