### ISSUE TITLE
Could rpcclient be used for other blockchains with the same REST API? (Dogecoin, Litecoin etc.)

### ISSUE THREAD

**Issue by TheoCoombes** [btcsuite/btcd#1713]
Could I use rpcclient for other networks, such as Dogecoin and Litecoin using the same BTC core connection code?

I believe they use the same REST API so surely they'd work?

**Comment by jcvernaleo** [comment]
I haven't tried in forever but at one point i had done some work for using the rpc code with litecoin.  REST api is pretty much the same.

**Comment by TheoCoombes** [comment]
Great - I think it's worth a try anyway

**Comment by jakesyl** [comment]
For litecoin, I'd use [ltcd](https://github.com/ltcsuite/ltcd).

**Comment by Roasbeef** [comment]
Yeah it works, assuming you mind things like the net constants of different chains.
