### ISSUE TITLE
Cannot connect to btcd via rpcclient 

### ISSUE THREAD

**Issue by d-fal** [btcsuite/btcd#1727]
I am on **btcd** docker with the following docker-compose:

```
version: "2"

services:
  btcd-node-2:
    container_name: btcd-node-2
    hostname: btcd
    image: btc-node
    restart: unless-stopped
    volumes:
      - ./btcd-data/:/root/.btcd/
    ports:
      - 8333:8333
      - 8334:8334
    networks:
        - btc-net
    command: [
        "--listen=",
        "--rpclisten=",
        "--rpcuser=myuser",
        "--rpcpass=mypass"
    ]

networks:
  btc-net:
volumes:
  btcd-data:

```

I have also generate a cert via **gencert** to let me connect via my server ip. The things go well once I try to connect **btcd** server on my server. However, I see unexpected response once I try via my laptop. 

```
btcctl --rpccert=$PATH_TO_CERT_FILE/rpc.cert --rpcuser=myuser --rpcpass=mypass --rpcserver=XXX.XXX.XXX.XXX getblockcount
```

I get the following response on my laptop after executing the above command:

> Post "https:/XXX.XXX.XXX.XXX8334": read tcp 192.168.100.35:55683->51.68.153.44:8334: read: operation timed out

I get the following log on my *btcd server as well* :

http: TLS handshake error from YYY.YYY.YYY.YYY:55794: read tcp4 10.10.0.2:8334->YYYY.YYY.YYY.YYY:55794: i/o timeout

Can anyone help how to resolve it?

**Comment by d-fal** [comment]
As a quick fix, I set a hostname in my **/etc/hosts** and generated a **cert** file for that using **gencert**.

**Comment by Roasbeef** [comment]
Appears resolved as it was an issue with the generated cert? Will re-open if there's an actual btcd issue here, as otherwise this is troubleshooting a local docker config.
