### ISSUE TITLE
Dedicated cpuminer

### ISSUE THREAD

**Issue by Barterio** [btcsuite/btcd#1734]
Hi there.
I'm running btcd node and made some changes to cpuminer which I want to test before making PR.
Is there any config guide about setting up cpu miner without whole blockchain sync? 
I've looked through all documentation at repository and I'm possibly missing something.
Thank you in advance

**Comment by Roasbeef** [comment]
> Is there any config guide about setting up cpu miner without whole blockchain sync?

What do you mean? It's a standalone package, so you can import it by itself if you need to. 

Assuming you want to write some unit tests for it, then you can create a fake simnet chain, which doesn't require you to download/process the entire chain or anything like that.
