### ISSUE TITLE
txscript.ExtractPkScriptAddrs fails on long (invalid?) scripts

### ISSUE THREAD

**Issue by smoyer64** [btcsuite/btcd#1736]
[Block 71036](https://www.blockchain.com/btc/block/71036) contains several transactions that `txscript.ExtractPkScriptAddrs` returns no addresses.  As shown in the link above, the Blockchain Explorer has properly parsed these transactions.  Specifically, transactions 3, 5 and 6 seem to have a script that's too long.  [Output 1](https://www.blockchain.com/btc/tx/e411dbebd2f7d64dafeef9b14b5c59ec60c36779d43f850e5e347abee1e1a455) of this transaction is a good example - the Blockchain explorer also reports no address but there's clearly one in the script which ends with a ridiculous number of `OP_CHECKSIG` operations.

**Comment by Roasbeef** [comment]
What address would you expect it to return in that case? The script is clearly invalid and can't be spent.

**Comment by smoyer64** [comment]
I think I was misunderstanding what I was seeing on the Blockchain Explorer - in output 1 referenced above, 0.05 bitcoin are "lost" since it's not sent to a valid output.  I need to account for that when considering the block as a whole (and the current available spendable bitcoin).
