### ISSUE TITLE
Upload btcd public blockchain snapshot

### ISSUE THREAD

**Issue by strusty** [btcsuite/btcd#1737]
@pakar   Kindly create a snapshot of the blockchain for new users to publicly download via FTP / SFTP coordinates to be provided by @Rakeshnohria.

**Comment by pakar** [comment]
@strusty @Rakeshnohria

Currently synced up to 2019-09-05 and will create a snapshot when it is current, or close to current.

Send upload details to me at pakar (at) imperialnet.org
