### ISSUE TITLE
Not a valid documentation

### ISSUE THREAD

**Issue by thecowmilk** [btcsuite/btcd#1740]
I tried to install following the documentation but nothing worked. Can you be more specific on how to install this? Thanks in advance

**Comment by smoyer64** [comment]
I was a newb about 6 months ago and got `btcd` running by following the documentation.  What steps did you perform and what was the output of each step?

**Comment by jcvernaleo** [comment]
@thecowmilk the install section in the readme should cover most install situations.  You'll need to give some more info such as what platform you are running on and what errors you are hitting if you want any more help.

**Comment by thecowmilk** [comment]
> @thecowmilk the install section in the readme should cover most install situations. You'll need to give some more info such as what platform you are running on and what errors you are hitting if you want any more help.

I run Kali Linux and I copy-paste every command I found on the README.md file and still didn't get it to work. I couldn't run the command "btcd" as the documentation said. and the thing is that I didn't get any erros.

**Comment by thecowmilk** [comment]
Something is off, I tried to build this long ago from source and it wouldn't give me the binary. Maybe the `go get` built it itself and now I got it... but fixing it with `go get` doesn't mean it still works the same when you try and build from source(especially when it doesn't say where we should `git clone` the repo). In the upcoming days i will give a visual representation on how I do things following the documentation. Cheers.

**Comment by jcvernaleo** [comment]
Thanks.  Any extra info will help.  I've never used Kali but pretty sure it is debian based which I am very familiar with.

**Comment by thecowmilk** [comment]
This [video](https://vimeo.com/594077113) shows how I did it following documentation. I think its better to add how to install it using `go get` and `git clone` because the first command didn't work. Yeah Kali Linux is based on Debain and they are very similar.

**Comment by Roasbeef** [comment]
You're running the `install` command from the _wrong_ directory. You need to `cd` back into the original dir you pasted at the start of the video.
