### ISSUE TITLE
Trying to connect electrumx and got error

### ISSUE THREAD

**Issue by paintmeyellow** [btcsuite/btcd#1741]
#### docker-compose.yml
![image](https://user-images.githubusercontent.com/24860764/129402533-fc14e9b6-3b99-4ad5-b46e-e6bd11857a2d.png)
--
#### Logs from btcd:
![image](https://user-images.githubusercontent.com/24860764/129402656-1259d552-fac3-43c2-b0bd-f138ae9b338d.png)
--
#### Logs from electrumx
![image](https://user-images.githubusercontent.com/24860764/129403027-c6011cac-0f4e-4705-a7c9-7e99d05d8cb1.png)

**Comment by Roasbeef** [comment]
> How can I disable ssl? 
```
      --notls                 Disable TLS for the RPC server -- NOTE: This is only allowed if the RPC server is bound to localhost
```
