### ISSUE TITLE
Clean up orphans on connected transactions.

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcd#176]
The current code properly removes transactions which are now double spends or have been mined into a newly connected block from the main memory pool when new blocks are connected, however the same things are not done to the orphan pool.  This isn't really a huge issue because the orphan pool is limited to a maximum number of entries and entries are randomly evicted once that limit is reached, however there is no reason to keep orphans around which can no longer be valid.  This will result in slightly less memory usage and free up additional slots for orphans which have a greater chance of actually becoming non-orphans.

The recently merged pull request #166 addresses part of this, however it did not address the cases of recursively removed transactions or orphans that now contain double spends as a result of transactions in a newly connected block.

**Comment by jrick** [comment]
I'm taking care of this as part of the mempool changes I'm working on.

**Comment by jakesyl** [comment]
Looks like this was fixed in #413
