### ISSUE TITLE
Import watch-only addresses 

### ISSUE THREAD

**Issue by gasparyanyur** [btcsuite/btcd#1775]
Hi all. 
I am going to use https://github.com/btcsuite/btcd (0.20.0-beta) as a part of my system, and I need to track some addresses imported using the public key. 
Can anybody help me with how to implement this kind of functionality?
I see that 0.20.0-beta release supports the ImportPrivateKey method, which adds an address into the wallet, but I can't find any solution how to import addresses using the only public key.

I would be very grateful if someone could share an example code or suggest where to find a similar implementation.

Thanks

**Comment by Roasbeef** [comment]
Use btcwallet: https://github.com/btcsuite/btcwallet

btcd doesn't contain a wallet. 

You can also use lnd that packages things like PSBT and key import: https://api.lightning.community/#service-walletkit
