### ISSUE TITLE
Add starting and current priority to getrawmempool

### ISSUE THREAD

**Issue by dajohi** [btcsuite/btcd#178]
Currently, btcd doesn't fill in the proper priority values for getrawmempool verbose.  Now that btcd does have the ability to calculate tx priority, these should be filled in with the correct values.

```
 StartingPriority: 0, // We don't mine.
 CurrentPriority:  0, // We don't mine.
```

**Comment by Roasbeef** [comment]
I believe this issue can be closed, starting and current priority for `getrawmempool` was added in [this commit](https://github.com/btcsuite/btcd/commit/a49b0d05b388cacdaa569e7f83a668571a984d95).

**Comment by davecgh** [comment]
Thanks @Roasbeef.  You're correct.
