### ISSUE TITLE
go get command is downloading the `github.com/gcash/bchd` module instead of `btcd`

### ISSUE THREAD

**Issue by theredrad** [btcsuite/btcd#1818]
I'm trying to add `btcd` to the module, but the `github.com/gcash/bchd` is downloaded to the GOPATH/pkg/mod.

```shell
$ go get github.com/btcsuite/btcd
go get: github.com/btcsuite/btcd@v0.14.6 updating to
        github.com/btcsuite/btcd@v0.18.1: parsing go.mod:
        module declares its path as: github.com/gcash/bchd
                but was required as: github.com/btcsuite/btcd
```

**Comment by theredrad** [comment]
It only works with an explicit version tag

```shell
$ go get github.com/btcsuite/btcd@v0.22.0-beta
```

Maybe it's related to the forked repositories tags conflicts which are fixed in the go mod retract scope. but I don't know why it was trying to download the `v0.18.1` version instead of `0.22.0-beta` as the default.

**Comment by Roasbeef** [comment]
See this issue: https://github.com/btcsuite/btcd/issues/1791#issuecomment-1031954335

**Comment by theredrad** [comment]
So this is a duplicate of issue #1791
