### ISSUE TITLE
Regtest: "block target difficulty is higher than max"

### ISSUE THREAD

**Issue by sangaman** [btcsuite/btcd#1819]
I ran into this error trying to use lnd in neutrino mode against a bitcoind node on regtest. I traced the error to this codebase, https://github.com/btcsuite/btcd/blob/master/blockchain/validate.go#L318.

```
[WRN] BTCN: Header doesn't pass sanity check: block target difficulty of 7fffff0000000000000000000000000000000000000000000000000000000000 is higher than max of 1fffff0000000000000000000000000000000000000000000000000000000000 -- disconnecting peer
```

The block target difficulty is actually very low for this regtest node, `"difficulty": 4.656542373906925e-10` according to `bitcoin-cli getblockchaininfo`. But it looks like btcd rejects it for being too high.

**Comment by guggero** [comment]
Fixed by https://github.com/btcsuite/btcd/pull/1985.
