### ISSUE TITLE
Makefile "build" not building all modules which makes GH Action build incomplete

### ISSUE THREAD

**Issue by vpereira01** [btcsuite/btcd#1826]
Noticed because of checks on PR #1815 that the build job, which uses the Makefile "build" is not really building all modules, just btcd package and its commands. Sub-modules are not being built (btcec, btcutil, btcutil/psbt).

Should the Makefile generate builds for all executables in all modules?
Or should the GH Action run new Makefile instruction to check all packages and all modules can be built?
Or other option?

I was a bit confused about the Makefile since it states in the comment "Installation" but the target "build" so I don't really know what's the intent between the Makefile "build" target and its use on the GitHub action.

I think that for GH Action a "build" job should do so it checks all modules and packages can be built

```
go build ./...
cd btcec; go build ./...
cd btcutil; go build ./...
cd btcutil/psbt; go build ./...
```

**Comment by samay-kothari** [comment]
Hi @vpereira01,
I think the build target in the Makefile is checking for submodules as well.
`
build:
	@$(call print, "Building all binaries")
	$(GOBUILD) $(PKG)
	$(GOBUILD) $(PKG)/cmd/btcctl
	$(GOBUILD) $(PKG)/cmd/gencerts
	$(GOBUILD) $(PKG)/cmd/findcheckpoint
	$(GOBUILD) $(PKG)/cmd/addblock
`
So the `make build` in the github workflow is calling this from the makefile, which in turn is building all the sub-modules as well along with the btcd module.

**Comment by vpereira01** [comment]
> I think the build target in the Makefile is checking for submodules as well.

More or less, yes but not completely.

* The repository contains four modules, the main module `github.com/btcsuite/btcd` and three other modules `github.com/btcsuite/btcd/btcec/v2`, `github.com/btcsuite/btcd/btcutil` and `github.com/btcsuite/btcd/btcutil/psbt`. This can be verified by finding all go.mod files.

* Makefile 'build' is building all main packages, or in other words, executables from the main module `github.com/btcsuite/btcd`. It also builds other modules from the working directory if there's a `replace` directive. This can be verified by making a change in another module so it does not compile and run `make build` to verified if it's really being built.

* Currently, on master, when running `make build` only the main module `github.com/btcsuite/btcd` and the module `github.com/btcsuite/btcd/btcutil` are built because there's just one `replace` directive in the root directory go.mod.

So far, nothing that bad besides being a bit confusing. The issue that I know better understand is the go.sum file in each module.

In the PR #1815 `make build` runs successfully and also builds the "submodule" btcutil with success. But if run `go build .` in the btcutil directory fails with error 
```
user@PC:~/github/btcd/btcutil$ go build .
go: github.com/btcsuite/btcd@v0.22.0-beta.0.20220111032746-97732e52810c requires
        golang.org/x/sys@v0.0.0-20200814200057-3d37ad5750ed: missing go.sum entry; to add it:
        go mod download golang.org/x/sys
go: github.com/btcsuite/btcd@v0.22.0-beta.0.20220111032746-97732e52810c requires
        golang.org/x/sys@v0.0.0-20200814200057-3d37ad5750ed: missing go.sum entry; to add it:
        go mod download golang.org/x/sys
```

This means that `make build` is not enough to know whether all modules can be built.

Seems to me that the better approach is to add another makefile target to validate that all modules can be built.
What do you guys think?

**Comment by chappjc** [comment]
The Makefile is ensuring the modules are building, indirectly via the go tests.

https://github.com/btcsuite/btcd/blob/558fcde3ddcae93b55f366963883279967beb4a6/Makefile#L82-L85

You could explicitly `cd` into each module for a `go build`, but it has to build them to run the unit tests.  Either way, you don't want to rely on replaces to build the local revisions of a sub-module.

Those "missing" go.sum entries could be caught by adding `go mod tidy` to the CI workflow and checking for modifications.  e.g. `MOD_STATUS=$(git status --porcelain go.mod go.sum)` and check if anything is modified.  You just have to be sure to pick only one Go version to do that tidy because different versions do different things to the go.mod/sum files.

**Comment by vpereira01** [comment]
You're correct, it's already validated through `make unit`, so probably nothing needs to be changed.

I was confused but how this was structured but I it's clear to me now :+1: 

Either way if someone wants to add the go mod tidy check here's the Makefile code for it:

```
tidycheck:
	@$(call print, "Checking if go mod tidy changes anything.$(NC)")
	go mod tidy
#   Exit code non-zero when changes are detected go.sum or go.mod
	git diff --exit-code -- go.mod
	git diff --exit-code -- go.sum
#   Same check but for all other modules
	cd btcec; go mod tidy
	cd btcutil; go mod tidy
	cd btcutil/psbt; go mod tidy
	git diff --exit-code -- **/go.mod
	git diff --exit-code -- **/go.sum
```

**Comment by tobetterman** [comment]
g5s4g5sdg45sdg45sなフアやャクヤなどがミドっぱくラバニラサダウのブはとてもおい
