### ISSUE TITLE
Using rpcclient GetNewAddress shows -32600: Invalid request

### ISSUE THREAD

**Issue by leoyzx** [btcsuite/btcd#1843]
my version of btcd/btcwallet:
btcd version 0.22.0-beta
btcwallet version 0.7.0-alpha
After running`btcd --simnet --rpcuser=rpcuser --rpcpass=rpcpass --rpclisten=0.0.0.0:18556 --listen=0.0.0.0:18555`&`btcwallet --simnet --username=rpcuser --password=rpcpass` the btcwallet RPC server listening on 127.0.0.1:18554
after connecting to btcw rpcserver with the config
`connCfg := &rpcclient.ConnConfig{
		Host:         "localhost:18554",
		Endpoint:     "ws",
		User:         "rpcuser",
		Pass:         "rpcpass",
		Params: 	"simnet",
		Certificates: certs,
	}`
using the api `address,err:=client.GetNewAddress("default","legacy")` the err shows that`-32600: Invalid request`.
Does anyone know the possible solution of this situation?
PS: i have tried `ListAccounts`&`GetAddressesByAccount`,they can return the correct data.

**Comment by chappjc** [comment]
You're using the `rpcclient` package from `master`, but the btcwallet from long ago.

In https://github.com/btcsuite/btcd/commit/061aef98af1321d2cad437afcb7dcbd562a5b3b6, the `getnewaddress` RPC was given the addess type argument, but corresponding btcwallet change is not merged yet https://github.com/btcsuite/btcwallet/pull/783

Just use the rpcclient package from the 0.22.0-beta tag.  You should probably also update your btcwallet from 0.7.0 to latest.

**Comment by leoyzx** [comment]
i have update my btcwallet from 0.7.0 to 0.14.0(i didn't modify the code).
Using the new btcw server certificates&connecting to it.
In the code `address,err =client.GetNewAddress("test","legacy")`.
err still returns `-32600: Invalid request`.

**Comment by leoyzx** [comment]
> You're using the `rpcclient` package from `master`, but the btcwallet from long ago.
> 
> In [061aef9](https://github.com/btcsuite/btcd/commit/061aef98af1321d2cad437afcb7dcbd562a5b3b6), the `getnewaddress` RPC was given the addess type argument, but corresponding btcwallet change is not merged yet [btcsuite/btcwallet#783](https://github.com/btcsuite/btcwallet/pull/783)
> 
> Just use the rpcclient package from the 0.22.0-beta tag or right before [061aef9](https://github.com/btcsuite/btcd/commit/061aef98af1321d2cad437afcb7dcbd562a5b3b6). You should probably also update your btcwallet from 0.7.0 to latest (cli will show 0.11.0, but tag is 0.14.0)

i checked the btcctl, using`btcctl /l`,it still shows `getnewaddress ("account")`,doesn't receive the param 'addrType', do you know in which version or any branches it can receive 'addrType'.(I don't want to use the lower version of rpcclient,cause #1519 shows that it doesn't work in simnet)

**Comment by chappjc** [comment]
As I explained, btcwallet does not support the address type argument yet.  That PR still needs to be merged.  btcwallet does not yet support the address type argument.

**Comment by chappjc** [comment]
I don't understand the relevance of https://github.com/btcsuite/btcd/issues/1519.  The fix PR was merged long before 0.22-beta.

**Comment by leoyzx** [comment]
ok, i understand your meaning, but face another problem now,when i compile my code it shows`btcsuite\btcd@v0.22.0-beta.0.20220111032746-97732e52810c\txscript\sign.go:296:25: cannot use pubKey (variable of type *secp256k1.PublicKey) as type *btcec.PublicKey in argument to pSig.Verify
` i will do as your suggestion after i solve it.

**Comment by chappjc** [comment]
`v0.22.0-beta.0.20220111032746-97732e52810c` is past `v0.22.0-beta`.  You need to edit your app's go.mod and have the btcd require line specify exactly `v0.22.0-beta`

**Comment by leoyzx** [comment]
Sincerely appreciate your help.
i download the source code of `v0.22.0-beta`(Jun 8, 2021) and replace it in both my goroot&gopath, but now when i compile my code in goland it still shows used`btcd@v0.22.0-beta.0.20220111032746-97732e52810c`, i don't know how to solve it.Each time i run`go mod tidy`&`go mod download`, go mod downloads the version of `v0.22.0-beta.0.20220111032746-97732e52810c`,if I used replace btcd from `v0.22.0-beta.0.20220111032746-97732e52810c` to `v0.22.0-beta`, it shows
![image](https://user-images.githubusercontent.com/44257696/163702328-966b8b21-a27d-4c9f-abae-2d054ef776ac.png)
 

my go.mod
![image](https://user-images.githubusercontent.com/44257696/163702344-3df84fae-46ea-4694-8e9a-9b12b135bd41.png)

i just want to use v0.22.0-beta directly, but since i use v0.21.0 last time and want to use v0.22.0 again it doesn't work, or can you  tell me how to delete all the package and build a whole new project again, i tried it several times but failed.

**Comment by chappjc** [comment]
Is that your entire go.mod file?  You have no `require` statement in go.mod for btcd.  No direct requires at all.  Is your code using rpcclient or something indirectly?

Also, you should not need a `replace`, but that's not the correct syntax for a replace directive.  The left side should not specify a version.

**Comment by leoyzx** [comment]
I used`go mod edit -require="github.com/btcsuite/btcd@v0.22.0-beta`,after i used `go mod tidy`it still turn into `github.com/btcsuite/btcd v0.22.0-beta.0.20220111032746-97732e52810c`.
before:
![image](https://user-images.githubusercontent.com/44257696/163778272-e170ad13-0d5e-4419-825b-4a1007206021.png)
after:
![image](https://user-images.githubusercontent.com/44257696/163778378-863ba4e9-8294-41fe-b78a-c642bea50dc0.png)
Should require btcd in the format like `v0.22.0-beta.0.20220111032746-97732e52810c`? I don't know

**Comment by leoyzx** [comment]
it seems that i have solved it now, i'm not sure, i will close this comment as i confirm it was done. Really thanks for your help. : )
