### ISSUE TITLE
txscript error

### ISSUE THREAD

**Issue by pilotpirks** [btcsuite/btcd#1845]
Hello,
when i call any fynction from txscript (e.q DisasmString(), ), i get this error:

github.com/btcsuite/btcd/txscript
../../../go/pkg/mod/github.com/btcsuite/btcd@v0.22.0-beta.0.20220111032746-97732e52810c/txscript/sign.go:296:25: cannot use pubKey (variable of type *secp256k1.PublicKey) as type *btcec.PublicKey in argument to pSig.Verify

Thx)

**Comment by chappjc** [comment]
Specify the `v0.22.0-beta` tag in your go.mod.
You're using a revision that's not part of a release branch or tag.

**Comment by pilotpirks** [comment]
reinstalled by manual,
sorry
