### ISSUE TITLE
Planned support for `searchrawtransactions` API method?

### ISSUE THREAD

**Issue by adamkrellenstein** [btcsuite/btcd#185]
Over at [Counterparty](https://github.com/CounterpartyXCP/), we're currently using local Insight servers for providing counterpartyd with Bitcoin block explorer functionality, and we're considering switching over to just using jmcorgan's `addrindex` fork of Bitcoin Core (which provides a `searchrawtransactions` API method) to do all of that instead. However, it's not clear yet whether that functionality will be merged into Bitcoin Core `master`. We'd really like to switch to using btcd as our backend as soon as it's production-ready, so if btcd isn't going to support this functionality (namely if it doesn't get merged into Bitcoin Core), we might hold off on dropping Insight support. So the question is, will btcd index transactions by address?

**Comment by davecgh** [comment]
This is currently implemented in pr #205.

**Comment by davecgh** [comment]
This is now available on master.
