### ISSUE TITLE
rpc getrawtransaction return vout.scriptPubKey.addresses is deprecated at bitcoind version 22.0

### ISSUE THREAD

**Issue by jianbo-zh** [btcsuite/btcd#1874]
issue #1754 problem still exists, not fixed

Content: rpc getrawtransaction return vout.scriptPubKey.addresses is deprecated at bitcoind version 22.0

https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-22.0.md#new-and-updated-rpcs

**Comment by Revinand** [comment]
Any updates on this? @Roasbeef @dajohi @davecgh

**Comment by Revinand** [comment]
There is a PR, but it is still not merged - https://github.com/btcsuite/btcd/pull/1858
