### ISSUE TITLE
question: lack of witness encoding in handleInvMsg

### ISSUE THREAD

**Issue by BrannonKing** [btcsuite/btcd#1877]
Regarding the encoding chosen at the bottom of netsync/manager::handleInvMsg, why does it not use the peer's witness support? In other words, why does it always encode without witness data rather than ending like this code below? Is the `iv.Type` always sufficient for Segwit-enabled peers?

```go
	...
	e := wire.BaseEncoding
	if peer.IsWitnessEnabled() {
		e = wire.WitnessEncoding
	}

	state.requestQueue = requestQueue
	if len(gdmsg.InvList) > 0 {
		peer.QueueMessageWithEncoding(gdmsg, nil, e)
	}
}
```

**Comment by Roasbeef** [comment]
So we're just sending a `getdata` here. This message doesn't have any witness specific encoding. If you look above, if they send us an inv, and they have witness support, then we'll set the inv type to mark that we want witness data.
