### ISSUE TITLE
GetBlock  return "error reading json reply: unexpected EOF"

### ISSUE THREAD

**Issue by xianggy** [btcsuite/btcd#1881]
Hi,
Calling rpcclient.Client.GetBlock get a response: "error reading json reply: unexpected EOF".
block height: 750730
block hash: 00000000000000000004d4a438528a60a34bb9ee4c463d6f1773dc0948911831
This error throws at infrastructure.go line 852.
This error may be related to the block data being too large, but I don't know how to fix it.

Thanks.

**Comment by Roasbeef** [comment]
I'm able to fetch this block on the command line no problem (both verbose and regular).

**Comment by xianggy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Roasbeef** [comment]
Closing for now....

Maybe open a question in the Discussions section once you're back.

**Comment by xianggy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
