### ISSUE TITLE
BTCD does not contain BTCEC package

### ISSUE THREAD

**Issue by markcryptohash** [btcsuite/btcd#1887]
I switched from Go 1.16, to Go 1.18 and getting this.

In my project I am trying:
go mod tidy
go: finding module for package github.com/btcsuite/btcd/btcec
github.com/imperviousai/imp-daemon/id/ion imports
	github.com/hyperledger/aries-framework-go/pkg/doc/jose/jwk imports
	github.com/btcsuite/btcd/btcec: module github.com/btcsuite/btcd@latest found (v0.23.1), but does not contain package github.com/btcsuite/btcd/btcec

**Comment by markcryptohash** [comment]
Also just tried with Go 1.19 still same error.

**Comment by Roasbeef** [comment]
The latest version uses `btcec/v2`: https://pkg.go.dev/github.com/btcsuite/btcd/btcec/v2

**Comment by markcryptohash** [comment]
Hmmmm....

go get github.com/btcsuite/btcd/btcec/v2
go: downloading github.com/btcsuite/btcd/btcec/v2 v2.2.1
go: upgraded github.com/btcsuite/btcd/btcec/v2 v2.1.3 => v2.2.1
▶ go build cmain.go
../../go/pkg/mod/github.com/hyperledger/aries-framework-go@v0.1.8/pkg/doc/jose/jwk/jwk.go:21:2: no required module provides package github.com/btcsuite/btcd/btcec; to add it:
	go get github.com/btcsuite/btcd/btcec

**Comment by Roasbeef** [comment]
You need to fix all your import paths, the v2 suffix needs to be added. We
made a v2 since there're breaking API changes btw.

**Comment by markcryptohash** [comment]
ah interesting.. the BTCEC was pulled in by a third party package, so I'll tweak thier to add the /v2. Think that is appropriate?

**Comment by chappjc** [comment]
You can't force the third party package to use the different module.  They aren't compatible.

In your project, specify to require `github.com/btcsuite/btcd@v0.22.1` rather than leaving it unspecified to get `latest`.  

`aries-framework-go` should either update their require to `v0.22.1` instead of [`v0.22.0-beta`](**url**), or they should update to `v0.23.1` (and `btcec/v2` and `btcd/btcutil`)

**Comment by markcryptohash** [comment]
thank you, this worked!

**Comment by markcryptohash** [comment]
p.s. for future people who may run across the same error I ran this:
go mod edit -require github.com/btcsuite/btcd@v0.22.1
