### ISSUE TITLE
maxWitnessItemSize too low for TX 7393096d97bfee8660f4100ffd61874d62f9a65de9fb6acf740c4c386990ef73

### ISSUE THREAD

**Issue by grisha** [btcsuite/btcd#1897]
```
readScript: script witness item is larger than the max allowed size [count 33970, max 11000]
```

This line here:

https://github.com/btcsuite/btcd/blob/master/wire/msgtx.go#L109

I upped it to 40000 and it worked for me, but I'm using btcd for a rather unusual application and don't know what else upping this might break.

HTH

**Comment by guggero** [comment]
Fixed by https://github.com/btcsuite/btcd/pull/1896.

**Comment by Clodo76** [comment]
I also have this issue, in production, stucked at block 757921.
If i try to update btcd, throw
```
#GO111MODULE=on go install -v . ./cmd/...
go: errors parsing go.mod:
/home/air/go/src/github.com/btcsuite/btcd/go.mod:35: unknown block type: retract

```
what i can do? thanks

**Comment by guggero** [comment]
Use golang 1.18 or later to build `btcd`.

**Comment by Clodo76** [comment]
> Use golang 1.18 or later to build `btcd`.

Thank you, i resolved.
"Go" under official Debian repo (the latest, Debian 11 Bullseye) is still 1.17, i installed Go 1.19.2 without Debian repo (if anyone have the same issue).
