### ISSUE TITLE
$1500 bounty for the creation of address index in btcd

### ISSUE THREAD

**Issue by ivanaszuber** [btcsuite/btcd#190]
The [Counterparty](https://github.com/CounterpartyXCP/) team is offering a $1500 bounty for the creation of address index in btcd.

Counterparty is currently using local Insight servers for providing counterpartyd with Bitcoin block explorer functionality, and we'd like to switch to using btcd as our backend as soon as it's production-ready. For this we need btcd to index transactions by address.

Related: https://github.com/conformal/btcd/issues/185

**Comment by davecgh** [comment]
@ivanaszuber, @adamkrellenstein: PR #205 is nearing completion.  I'm still doing a lot of testing on it and it needs another round of code review, but it should be ready for you guys to pull and test to make sure it does what is expected.  As @Roasbeef posted above, once the address index is activated with --addrindex and has caught up to the main chain, the new `searchrawtransaction` RPC will return all transactions which involve the provided address.

**Comment by ivanaszuber** [comment]
Thanks @davecgh & @Roasbeef ! We'll start our testing soon and let you know if we run into any issues.

**Comment by ivanaszuber** [comment]
@davecgh we've done our initial testing and it seems to work as expected (we didn't run into any issues so far). Once you complete your code review we can proceed with the payment

**Comment by davecgh** [comment]
@ivanaszuber Thanks for the update.  I'm done with the code review and testing.  The only thing that remains is for the `searchrawtransactions` bool -> int fix and then I'll get it merged.

**Comment by davecgh** [comment]
This has been implemented by #205 and is now available on master.
