### ISSUE TITLE
Running LND over Litecoin unmarshal error

### ISSUE THREAD

**Issue by josesolaro** [btcsuite/btcd#1902]
Running the latest version of https://github.com/lightningnetwork/lnd (lnd v0.15.2-beta) for LiteCoin (version Litecoin Core v0.21.2.1) cause the next problem:

`LTND: unable to create partial chain control: unable to determine if bitcoind is pruned: json: cannot unmarshal object into Go struct field SoftForks.softforks of type []*btcjson.SoftForkDescription
LTND: Shutting down because error in main method: error creating wallet config: unable to create partial chain control: unable to determine if bitcoind is pruned: json: cannot unmarshal object into Go struct field SoftForks.softforks of type []*btcjson.SoftForkDescription
LTND: Shutdown complete`

Could you improve the compatibility?

**Comment by Roasbeef** [comment]
This is a Bitcoin repo. btcd only works on Bitcoin. lnd's support for litecoin is also mostly unmaintained.
