### ISSUE TITLE
Failed to decode mainnet block 761249

### ISSUE THREAD

**Issue by iam047801** [btcsuite/btcd#1910]
`(*rpcclient.Client).GetBlock` fails on 761249 block with hash `000000000000000000070742427fa10ec3c66d006160155a704d9f56d090a3ea` with the following error:

`MsgTx.BtcDecode: too many witness items to fit into max message size [count 500003, max 500000]`

I'm using `btcd@v0.23.2`.

**Comment by sputn1ck** [comment]
We just pushed the fix to master and tag `btcd@v0.23.3` a release will be up soon
