### ISSUE TITLE
Package unsafe is not in GOROOT

### ISSUE THREAD

**Issue by mateusgalasso** [btcsuite/btcd#1926]
Following the instalation I receive the error
`package unsafe is not in GOROOT`
What could be?

**Comment by guggero** [comment]
Make sure to use Golang 1.18 or later?

**Comment by mateusgalasso** [comment]
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/mateusgalasso/Library/Caches/go-build"
GOENV="/Users/mateusgalasso/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/mateusgalasso/gocode/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mateusgalasso/gocode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/mateusgalasso/gocode"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/mateusgalasso/gocode/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19.3"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tq/h6927n_165j7qcjnq3ync_th0000gn/T/go-build2811312351=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by guggero** [comment]
Sounds like an incorrect installation. `GOROOT` should point to the installation directory and not the same as `GOPATH`.

**Comment by mateusgalasso** [comment]
my mistake , thanks a lot
