### ISSUE TITLE
Ambiguous import

### ISSUE THREAD

**Issue by joshklop** [btcsuite/btcd#1937]
Hi! I'm importing `github.com/ethereum/go-ethereum/core/types`, which depends on `btcd`. When I run `go mod tidy`, I get the following error:
```
github.com/filecoin-project/bacalhau/pkg/storage/ethblock imports
	github.com/ethereum/go-ethereum/core/types imports
	github.com/ethereum/go-ethereum/crypto imports
	github.com/btcsuite/btcd/btcec/v2/ecdsa tested by
	github.com/btcsuite/btcd/btcec/v2/ecdsa.test imports
	github.com/btcsuite/btcd/chaincfg/chainhash: ambiguous import: found package github.com/btcsuite/btcd/chaincfg/chainhash in multiple modules:
	github.com/btcsuite/btcd v0.22.0-beta (/home/user/.go/pkg/mod/github.com/btcsuite/btcd@v0.22.0-beta/chaincfg/chainhash)
	github.com/btcsuite/btcd/chaincfg/chainhash v1.0.1 (/home/user/.go/pkg/mod/github.com/btcsuite/btcd/chaincfg/chainhash@v1.0.1)
```
Even after reading through a number of issues (#1839, [here](https://github.com/ethereum/go-ethereum/pull/24554), [here](https://github.com/ethereum/go-ethereum/pull/24700)), I have been unable to resolve the issue.

I am on the latest version of `go-ethereum`. If I create a nearly empty go module and import the `github.com/ethereum/go-ethereum/core/types` package, I do not get this issue. Any suggestions/pointers would be much appreciated.

**Comment by chappjc** [comment]
Can you link to the branch you are working on and/or the go.mod?

**Comment by joshklop** [comment]
Thanks for the prompt response! [Branch](https://github.com/joshklop/bacalhau/tree/joshklop/ethblock-storage), [go.mod](https://github.com/joshklop/bacalhau/blob/joshklop/ethblock-storage/go.mod)

**Comment by chappjc** [comment]
Nothing stands out, hmm.  Give `go get -d github.com/btcsuite/btcd/chaincfg/chainhash@v1.0.2` a shot maybe.

**Comment by joshklop** [comment]
That worked! It appears I have some gaps in my understanding of go modules. Where is the `-d` flag documented?

**Comment by chappjc** [comment]
> That worked! It appears I have some gaps in my understanding of go modules. Where is the `-d` flag documented?

It's not you. Go modules are a confusing nightmare.  I think there's a go tool bug you were hitting in this case.  The `btcec/v2` module clearly requires a specific `chainhash` module, and your project has no direct or transitive requires on btcd (that I can see), so it shouldn't have barfed like this.
