### ISSUE TITLE
GCS duplicate data creates non-optimal filter

### ISSUE THREAD

**Issue by tcharding** [btcsuite/btcd#1940]
Hi,

I'm not a go dev but I'm reading your code to check that we don't have bugs in our Rust version of the bip158 golomb coded set [0].

Could you please clear something up for me. From my understanding, in your implementation if the input data passed to the filter builder includes a duplicate byte array the encoded bit stream will include a stream of zeros for the duplicate. And, again just from my understanding, this will not effect the querying of the filter but it will make the ecoding bigger than it needs to be. 

Three questions please:
1. Am I understanding your code correctly?
2. Was this done on purpose?
3. Will duplicates ever occur in practice?

The reason I'm investigating this is in our implementation we remove duplicates before building the filter and it has been suggested that this is a bug in our implementation [1].

Thanks in advance for your time,
Tobin.

[0] https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/src/bip158.rs
[1] https://github.com/rust-bitcoin/rust-bitcoin/issues/1444

**Comment by Kixunil** [comment]
To clarify a bit, if this was on purpose, then we do have a bug but if not then our filtering-out isn't perfect anyway and we should fix that.

**Comment by Roasbeef** [comment]
Not sure what you're seeing, but the data should be de-up (a map is used): https://github.com/btcsuite/btcd/blob/master/btcutil/gcs/builder/builder.go#L153-L163

Have you also cross checked against `btcd`? 

Also the test vectors include a transaction with duplicate push data iirc (has been a while since I looked at them): https://github.com/bitcoin/bips/blob/master/bip-0158/testnet-19.json

**Comment by Roasbeef** [comment]
> Will duplicates ever occur in practice?

Yes, for extended filters, anytime there's a duplicate item in the witness. 

For regular filters, anytime a re-used address is spent multiple times in the same block.

**Comment by Roasbeef** [comment]
Looks like `bitcoind` uses a set as well: https://github.com/kcalvinalvin/bitcoin/blob/e734228d8585c0870c71ce8ba8c037f8cf8b249a/src/blockfilter.h#L28

Perhaps the BIP needs to be clearer on this front.

**Comment by tcharding** [comment]
> Not sure what you're seeing, but the data should be deduped (a map is used): https://github.com/btcsuite/btcd/blob/master/btcutil/gcs/builder/builder.go#L153-L163

Ah sweet, I missed that yesterday - thanks for pointing that out.

Have you also cross checked against bitcoind?

No, but I will. Thanks.

Also the test vectors include a transaction with duplicate push data iirc (has been a while since I looked at them): https://github.com/bitcoin/bips/blob/master/bip-0158/testnet-19.json

Sweet, our code runs through these already, win.

Thanks for you time @Roasbeef, super helpful.
