### ISSUE TITLE
[Error] Client sent an HTTP request to an HTTPS server

### ISSUE THREAD

**Issue by lenhatquang97** [btcsuite/btcd#1947]
## Situation:
- I have installed btcd and setup configuration related to rpc. I try connecting to btcd through this code.
```
connCfg := &rpcclient.ConnConfig{
	Host:         "localhost:8334",
	User:         "4bmeiF7E3ny8cGf8Ok6QJZy/0pk=",
	Pass:         "2oljjSoRFzC5Go7hCGDID6xWi+c=",
	HTTPPostMode: true, // Bitcoin core only supports HTTP POST mode
	DisableTLS:   true, // Bitcoin core does not provide TLS by default
}
client, err := rpcclient.New(connCfg, nil)
```

However, when I run this script, there is an exception:
> unable to detect btcd version: status code: 400, response: "Client sent an HTTP request to an HTTPS server.\n"

Why do I run this code failed? How can I solve this problem?

## btcd.conf config
```
testnet=1
rpcuser=4bmeiF7E3ny8cGf8Ok6QJZy/0pk=
rpcpass=2oljjSoRFzC5Go7hCGDID6xWi+c=
rpclisten=0.0.0.0:8334
```
## btcd version
btcd version 0.23.3-beta

**Comment by chappjc** [comment]
btcd is not Bitcoin Core.  It's RPC server uses TLS, unlike bitcoind.
You can either use the rpc.cert with the rpcclient, or run btcd with `--notls` but `rpclisten` will have to be on a loopback interface.

**Comment by lenhatquang97** [comment]
Thank you very much!! I have changed to rpclisten=127.0.0.1:8334 and disable tls with --notls
