### ISSUE TITLE
Unable to "go get" chainhash

### ISSUE THREAD

**Issue by visualbasic6** [btcsuite/btcd#1959]
```
root@1999:~# go get github.com/btcsuite/btcutil/chaincfg/chainhash
go: module github.com/btcsuite/btcutil@upgrade found (v1.0.2), but does not contain package github.com/btcsuite/btcutil/chaincfg/chainhash
```

**Comment by guggero** [comment]
The `btcutil` project was moved into `btcsuite/btcd` to simplify things around dependencies somewhat. And the `chaincfg/chainhash` module was moved to `github.com/btcsuite/btcd/chaincfg/chainhash`.
So you need to pull in the module with `go get github.com/btcsuite/btcd/chaincfg/chainhash`. Maybe you also need to specify a version for that to work, I'd suggest to use `v1.0.2`.
