### ISSUE TITLE
Docs/mining.md is detected as a Trojan Horse by my antivirus software

### ISSUE THREAD

**Issue by WesleyLiu0717** [btcsuite/btcd#1961]
I use **Kaspersky** antivirus software.
The Docs/mining.md is detected as a Trojan Horse by **HEUR:Trojan.Script.Miner.gen** .
When I want to check the raw file, it is also blocked by the Kaspersky browser extension.
Please check that.
<img width="1080" alt="截圖 2023-03-15 上午9 20 23" src="https://user-images.githubusercontent.com/46731787/225179575-4beee552-62e1-45a8-b801-42c4509d792e.png">
<img width="378" alt="截圖 2023-03-15 上午9 14 09" src="https://user-images.githubusercontent.com/46731787/225179807-3e86896e-1f63-4770-98c7-b11cf8902b8f.png">

**Comment by guggero** [comment]
That is probably just some very badly implemented heuristic on the Kaspersky side. Not sure we can do anything about that, it's literally a text document! I'd file a "false positive" report with Kaspersky.

**Comment by jcvernaleo** [comment]
Yeah, that is an extra dumb match.  Reporting to Kaspersky that it is a clear false positive is the only real option.
