### ISSUE TITLE
unexpected EOF when loading rpc.cert

### ISSUE THREAD

**Issue by lenhatquang97** [btcsuite/btcd#1967]
Hello everyone, I have connected to btcd and I try to run this part of code for connecting to server:
```
func LoadCerts() ([]byte, error) {
	certHomeDir := btcutil.AppDataDir("btcd", false)
	certs, err := ioutil.ReadFile(filepath.Join(certHomeDir, "rpc.cert"))
	if err != nil {
		return nil, err
	}
	return certs, nil
}

certs, _ := LoadCerts()
client, err := rpcclient.New(&rpcclient.ConnConfig{
	Host:         "127.0.0.1:8334",
	User:         opt.User,
	Pass:         opt.pass,
	Certificates: certs,
}, nil)
```

However, when I run this code, it always says "unexpected EOF". What is the main problem with this code? I have learned this code in an example in docs/json_rpc_api.md.

**Comment by Roasbeef** [comment]
You'll get that if you either can't connect, or there's no cert file, or it isn't formatted correctly. Try to use either print statement or a debugger like `dlv` to figure out where things are going wrong.
