### ISSUE TITLE
How to sign form and sign P2TR transaction?

### ISSUE THREAD

**Issue by Sayplaydiv** [btcsuite/btcd#1982]
When i submit tx, sendrawtransaction return error:

`non-mandatory-script-verify-flag (Invalid Schnorr signature)`

my code:

`

func createSignedP2TRTx() {
	privKey := "xxxxx"
	spendAddrStr := "bc1pxxxxx"
	destAddrStr := "bc1pxxxx"
	chain := &chaincfg.MainNetParams
	txHash := "737235976b3a79f0c4afa9643e35195054c7d459702d0cf8870f3e2d3eb97c69"
	position := 1

	spendAddr, err := btcutil.DecodeAddress(spendAddrStr, chain)
	if err != nil {
		log.Println("DecodeAddress spendAddr err", err)
		return
	}
	destAddr, err := btcutil.DecodeAddress(destAddrStr, chain)
	if err != nil {
		log.Println("DecodeAddress destAddrStr err", err)
		return
	}

	wif, err := btcutil.DecodeWIF(privKey)
	if err != nil {
		log.Println("wif err", err)
		return
	}

	spenderAddrByte, err := txscript.PayToAddrScript(spendAddr)
	if err != nil {
		log.Println("spendAddr PayToAddrScript err", err)
		return
	}

	addrPubKey, err := btcutil.NewAddressTaproot(schnorr.SerializePubKey(txscript.ComputeTaprootKeyNoScript(wif.PrivKey.PubKey())), chain)
	witnessProgram, err := txscript.PayToAddrScript(addrPubKey)
	log.Println(hex.EncodeToString(spenderAddrByte), hex.EncodeToString(witnessProgram))
	// either witnessProgram or spenderAddrByte works

	destAddrByte, err := txscript.PayToAddrScript(destAddr)
	if err != nil {
		log.Println("destAddr PayToAddrScript err", err)
		return
	}

	utxoHash, err := chainhash.NewHashFromStr(txHash)
	if err != nil {
		log.Println("NewHashFromStr err", err)
		return
	}

	outPoint := wire.NewOutPoint(utxoHash, uint32(position))

	redeemTx := wire.NewMsgTx(2)

	txIn := wire.NewTxIn(outPoint, nil, [][]byte{})
	txIn.Sequence = txIn.Sequence - 2
	redeemTx.AddTxIn(txIn)

	redeemTxOut0 := wire.NewTxOut(10000, destAddrByte)
	redeemTxOut1 := wire.NewTxOut(200000, spenderAddrByte)

	redeemTx.AddTxOut(redeemTxOut0)
	redeemTx.AddTxOut(redeemTxOut1)
	redeemTx.LockTime = 0

	if err != nil {
		log.Println("DecodeString pkScript err", err)
		return
	}
	a := txscript.NewMultiPrevOutFetcher(map[wire.OutPoint]*wire.TxOut{
		*outPoint: {},
	})
	sigHashes := txscript.NewTxSigHashes(redeemTx, a)

	signature, err := txscript.TaprootWitnessSignature(redeemTx, sigHashes, 0, 277678, spenderAddrByte, txscript.SigHashAll, wif.PrivKey)
	if err != nil {
		panic(err)
	}
	redeemTx.TxIn[0].Witness = signature

	var signedTx bytes.Buffer
	redeemTx.Serialize(&signedTx)

	hexSignedTx := hex.EncodeToString(signedTx.Bytes())
	log.Println(hexSignedTx)
}
`

**Comment by Sayplaydiv** [comment]
After modification  use txscript.SigHashDefault, the error is still: non-mandatory-script-verify-flag (Invalid Schnorr signature).   



> You need to use `txscript.SigHashDefault` for Taproot signatures.

**Comment by guggero** [comment]
You're signing a taproot input, so you need to provide all previous outputs. So try adding real values to the `NewMultiPrevOutFetcher`. OutPoint is the input you're spending, and the TxOut is the info of that UTXO you're spending (its output script and value).

**Comment by Sayplaydiv** [comment]
> spenderAddrByte



> 
Is it modified like this? :
Or could you tell me how to modify my code? I would be very grateful！

`
	a := txscript.NewMultiPrevOutFetcher(map[wire.OutPoint]*wire.TxOut{
		*outPoint: {},
	})
	a.AddPrevOut(wire.OutPoint{
		Hash:  *utxoHash,
		Index: 0,
	}, wire.NewTxOut(277678, spenderAddrByte))

`

**Comment by Sayplaydiv** [comment]
> You're signing a taproot input, so you need to provide all previous outputs. So try adding real values to the `NewMultiPrevOutFetcher`. OutPoint is the input you're spending, and the TxOut is the info of that UTXO you're spending (its output script and value).

s it modified like this? :
Or could you tell me how to modify my code? I would be very grateful！

```
a := txscript.NewMultiPrevOutFetcher(map[wire.OutPoint]*wire.TxOut{
*outPoint: {},
})
a.AddPrevOut(wire.OutPoint{
Hash: *utxoHash,
Index: 0,
}, wire.NewTxOut(277678, spenderAddrByte))
```

**Comment by guggero** [comment]
You can do just:
```
a := txscript.NewMultiPrevOutFetcher(map[wire.OutPoint]*wire.TxOut{
*outPoint: {
    PkScript: spenderAddrByte,
    Value: 277678,
},
})
```

**Comment by 0xEclair** [comment]
Same problem, when i add two inputs, got error `Invalid Schnorr signature`.
```
signature, err := txscript.TaprootWitnessSignature(redeemTx, sigHashes, 0, 202, spenderAddrByte, txscript.SigHashDefault, wif.PrivKey)
if err != nil {
	panic(err)
}
redeemTx.TxIn[0].Witness = signature

signature2, err := txscript.TaprootWitnessSignature(redeemTx, sigHashes, 1, 6000, spenderAddrByte, txscript.SigHashDefault, wif.PrivKey)
if err != nil {
	panic(err)
}
redeemTx.TxIn[1].Witness = signature2
```

One input is working well.
