### ISSUE TITLE
go module error

### ISSUE THREAD

**Issue by DukeDeng** [btcsuite/btcd#2007]
github.com/btcsuite/btcd/btcec: module github.com/btcsuite/btcd@latest found (v0.23.4), but does not contain package github.com/btcsuite/btcd/btcec

**Comment by 0xEclair** [comment]
please check imported module path

**Comment by guggero** [comment]
See https://github.com/btcsuite/btcd/issues/1960#issuecomment-1594236164 (and also feel free to [use the search](https://github.com/btcsuite/btcd/issues?q=is%3Aissue+does+not+contain)).
