### ISSUE TITLE
Trojan:Win32/Bearfoos.A!ml

### ISSUE THREAD

**Issue by bmsn1** [btcsuite/btcd#2012]
Im getting a Trojan:Win32/Bearfoos.A!ml from running btcd.exe Help explain

**Comment by guggero** [comment]
Virus scanners are notoriously bad with false positives. Bitcoin Core gets them all the time. So unless you downloaded `btcd.exe` from an untrusted source, it very likely doesn't mean anything. If you want to be sure it's okay, build the executable yourself. Or use it on a non-Windows system.
