### ISSUE TITLE
Github Docker Image non existend

### ISSUE THREAD

**Issue by Schnitzel** [btcsuite/btcd#2015]
As far as I understand https://github.com/btcsuite/btcd/blob/master/.github/workflows/dimagespub.yml this should automatically build btcd and push it into the github image registry. There is an action log from the last version push but the logs are expired: https://github.com/btcsuite/btcd/actions/runs/3369306552/job/9224795357 so I can't check what might have gone wrong.

In any case I cannot pull Images from the Github Docker Registry:

```
❯ docker pull ghcr.io/btcsuite/btcd
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/btcsuite/btcd/manifests/latest": unauthorized

❯ docker pull ghcr.io/btcsuite/btcd:v0.23.3
Error response from daemon: Head "https://ghcr.io/v2/btcsuite/btcd/manifests/v0.23.3": unauthorized
```

anybody has an idea if these images exist and were they are?

**Comment by 0xEclair** [comment]
`unauthorized` means that you need to login.

Images are published as private images, so you can't pull it by default.

**Comment by Schnitzel** [comment]
@0xEclair thanks for your reply!

Even if I'm logged in the registry though I cannot pull them:

```
❯ docker login ghcr.io
Username: Schnitzel
Password:
Login Succeeded

❯ docker pull ghcr.io/btcsuite/btcd:v0.23.3
Error response from daemon: denied
```

you mention they are pushed as `private`, is there any reason for that? Can we push them as public?

**Comment by 0xEclair** [comment]
It's a default rule. You can check here: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#pushing-container-images.

**Comment by Schnitzel** [comment]
@0xEclair sorry didn't phrase my question correctly. Yes the images are `private` by default, my question is why we don't change this to public? Is there a specific reason? Maybe we need @Roasbeef or @guggero to help with changing this to public?

**Comment by Roasbeef** [comment]
Yep the package is private right now which wasn't the intention. Looks like the default on the org level is private, will get that switched over to public then report back here for confirmation.

**Comment by vniche** [comment]
Any updates?

**Comment by deliarmin** [comment]
Hi all! 
Found this thread, trying to find btcd docker builds. The docker hub repo that is mentioned in the documentation is non existent anymore, also here on github I could't find anything.
Is the only way to get images to build them yourself?

**Comment by Roasbeef** [comment]
The images should now be public: https://github.com/btcsuite/btcd/pkgs/container/btcd
