### ISSUE TITLE
v0.22.1 Detected like HEUR:Trojan.Script.Miner.gen

### ISSUE THREAD

**Issue by whonion** [btcsuite/btcd#2029]
https://www.virustotal.com/gui/file/1cdf53fbf87a2ed6290d62cce218a17c65c186bea7a64978c920c7c377ceba54?nocache=1

**Comment by guggero** [comment]
See https://github.com/btcsuite/btcd/issues/2012.
You can help by reporting false positives to those anti virus companies. Almost every Bitcoin Core release got flagged by one or two of those tools until people started to actively report those false positives: https://bitcoinissafe.com/
