### ISSUE TITLE
`if` with identical `then` and `else` blocks

### ISSUE THREAD

**Issue by chavacava** [btcsuite/btcd#2037]
https://github.com/btcsuite/btcd/blob/80f5a0ffdf363cfff27d550f9e38aa262667a7f1/cmd/btcctl/config.go#L143-L147

Either the whole conditional can be replaced by `defaultPort = "38332"` or the `else` branch should be fixed (by referring a different port?)

(found by [revive](https://github.com/mgechev/revive) while testing it on answer code base)

**Comment by 0xEclair** [comment]
Should fix `else` branch.

**Comment by chavacava** [comment]
@0xEclair if you can tell me the port number to use, I can make the PR.
