### ISSUE TITLE
chainhash do not include Unmarshal at v1.0.2

### ISSUE THREAD

**Issue by baduy-wd** [btcsuite/btcd#2063]
I saw the function in btcd but it not exists in "github.com/btcsuite/btcd/chaincfg/chainhash"
<img width="1116" alt="image" src="https://github.com/btcsuite/btcd/assets/119557954/2a4437e4-66a9-424e-8683-4ea16e3b7a67">
This is what I got 
<img width="943" alt="image" src="https://github.com/btcsuite/btcd/assets/119557954/6e4fd2b3-5f4f-49e9-b1df-826f958f19b3">

**Comment by guggero** [comment]
Thanks for reporting. I pushed a new tag `chaincfg/chainhash/v1.0.3`, so you can use `v1.0.3` which should include all recent changes.
