### ISSUE TITLE
no way to set rpcVersion! this is too freaky for https://getblock.io/

### ISSUE THREAD

**Issue by xpoy1** [btcsuite/btcd#2086]
https://getblock.io/ need rpcVersion 2 to call succuss, and doesn't support batch request.
There are no way to set rpcversion and batch option both correct at now

**Comment by Roasbeef** [comment]
Can you describe your issue in more detail? 

You can enable batch which will use rpc version 2, eg: https://github.com/btcsuite/btcd/blob/master/rpcclient/infrastructure.go#L1005
