### ISSUE TITLE
btcutil refactoring

### ISSUE THREAD

**Issue by mhitcher** [btcsuite/btcd#2096]
go run main.go          # github.com/btcsuite/btcwallet/wallet/txrules    ../../../../go/pkg/mod/github.com/btcsuite/btcwall
et/wallet/txrules@v1.2.0/rules.go:30:32: cannot us
e relayFeePerKb (variable of type "github.com/btcsuite/btcd/btcutil".Amount) as "github.com/btcsuite/btcutil".Amount value in argument to mempool.IsDust

**Comment by Roasbeef** [comment]
What does your local `go.mod` look like?

**Comment by yemmyharry** [comment]
The error being encountered is based off the fact that there's a mismatch between`github.com/btcsuite/btcd/btcutil` and `github.com/btcsuite/btcutil`.  `github.com/btcsuite/btcutil` is now a sub-package under btcd. There is a likelihood you have them both as dependencies and that can be quite confusing. You can review and potentially update the versions of dependencies specified in the `go.mod` file to resolve the conflict.
