### ISSUE TITLE
if RecoverCompact succeeds, it prove that signature is valid

### ISSUE THREAD

**Issue by xianggy** [btcsuite/btcd#2109]
If `ecdsa.RecoverCompact` returns the correct public key, does it mean that the signature is legitimate? Do I need to call the signature verification function(such as ` ecdsa.ParseDERSignature`) again to verify the signature?

**Comment by guggero** [comment]
`RecoverCompact` does verify the signature. See https://github.com/decred/dcrd/blob/master/dcrec/secp256k1/ecdsa/signature.go#L796, which is what is actually used under the hood.

Also, please use [discussions](https://github.com/btcsuite/btcd/discussions) for questions.

**Comment by xianggy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
