### ISSUE TITLE
When using client for RPC access, how do I specify the wallet?

### ISSUE THREAD

**Issue by s1mple1122** [btcsuite/btcd#2111]
request err ，Wallet file not specified (must request wallet RPC through /wallet/<filename> uri-path)
The method I am using is `client.GetTransaction(txHash)`

**Comment by Roasbeef** [comment]
`btcd` doesn't package a wallet, you can find one here: https://github.com/btcsuite/btcwallet/tree/master

Or run `lnd` which lets you package neutrino and the wallet: https://github.com/lightningnetwork/lnd
