### ISSUE TITLE
 GetDustThreshold does not take into account taproot

### ISSUE THREAD

**Issue by benthecarman** [btcsuite/btcd#2114]

**Comment by Roasbeef** [comment]
Do you have a test case or some counter example? 

IIUC, the dust limit for taproot outputs was purposefully never updated: https://github.com/bitcoin/bitcoin/blob/5fbcc8f0560cce36abafb8467339276b7c0d62b6/src/policy/policy.cpp#L49-L60

See this PR for the discussion that led to leaving the dust computation unchanged (generic for witness version 0 onwards): https://github.com/bitcoin/bitcoin/pull/22779

You actually ACK'd that PR yourself: https://github.com/bitcoin/bitcoin/pull/22779#pullrequestreview-742133650

**Comment by benthecarman** [comment]
Oh my bad, was reading through the dust code and saw it didn't mention taproot, forgot about the dust limit not changing
