### ISSUE TITLE
Upcoming Btcd Code Migration and Reorganization

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcd#214]
Hello all,

This issue is an announcement to make everyone aware that the entire Conformal Bitcoin-related code base is going to be moving to a [new organization](https://github.com/btcsuite) here on github.  This  [gist](https://gist.github.com/davecgh/9bfbcc18fc6a59366939) contains the details.

Please feel free to respond if you have any questions, concerns, or suggestions.

**Comment by flammit** [comment]
+1.  Sounds like a great idea.  Having a single repo for the main btcd components will certainly make the old multi-package pull requests much easier.

**Comment by davecgh** [comment]
This first round of this has been completed.  In particular all repos have been moved here to the btcsuite organization and all packages have been updated to use the new paths.

The second phase will include the other changes to merge some of the repos as outlined in the linked document.

From now on, you'll want to run `go get -u github.com/btcsuite/btcd/...` to get updates or `go get github.com/btcsuite/btcd/...` when fetching the code to an empty `GOPATH` such as for a fresh installation.

**Comment by NSkelsey** [comment]
@davecgh, do you have a planned date for the second phase of the move?

**Comment by davecgh** [comment]
@NSkelsey:  It will be happening over the next couple of weeks, one repo at a time.  Unlike transferring a repo to a new organization, merging them doesn't bring the issue and pull requests along with them, so we will be making a push to get pull requests on the deps merged and/or closed then performing the merge of the repo.  This first one is likely to be btcdb.

**Comment by davecgh** [comment]
This has now been completed.
