### ISSUE TITLE
Run option btcd --regtest has an issue

### ISSUE THREAD

**Issue by Sotatek-MinhNguyen11** [btcsuite/btcd#2159]
My process is hanging when i run command: btcd --regtest
![Screenshot from 2024-04-08 11-17-50](https://github.com/btcsuite/btcd/assets/146687333/f7df8117-50ed-4817-bba1-b7ba0f9df4ad)

**Comment by guggero** [comment]
I see no error message. More details please.

**Comment by Sotatek-MinhNguyen11** [comment]
@guggero it still here for along time, don't fetch any block data

**Comment by guggero** [comment]
Regtest is a local network that has no blocks. You produce blocks yourself. See https://river.com/learn/terms/r/regtest/.
