### ISSUE TITLE
Issue/Bug with PSBT deserialization

### ISSUE THREAD

**Issue by hax0kartik** [btcsuite/btcd#2199]
Hello, 

BTCD _does not fail as it should_ when trying to deserialize the following bytes:

`70736274ff01001c000000000002000000000000000000000000736210ff01000001010010ff70ff01001c00000000000000000000000000000000000000000000`

For the above input, Bitcoin-core _fails_ while trying to deserialize and throws the error `ReadCompactSize(): size too large`.

This issue partly seems to be due to incorrect implementation of [bip-174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki). Bip-174 says that `keytype` is a `compact size int` and from what I see btcd simply treats `keytype` [as a single byte](https://github.com/btcsuite/btcd/blob/master/btcutil/psbt/utils.go#L253-L258).

The test case given below can be used to reproduce this issue:

```golang

func TestKeyType(t *testing.T) {
	k, _ := hex.DecodeString("70736274ff01001c000000000002000000000000000000000000736210ff01000001010010ff70ff01001c00000000000000000000000000000000000000000000")
	if _, err := NewFromRawBytes(bytes.NewReader(k), false); err == nil {
		require.Error(t, err, "Err should not be nil")
	}
}
```

cc: @brunoerg

**Comment by Roasbeef** [comment]
> Bip-174 says that keytype is a compact size int and from what I see btcd simply treats keytype [as a single byte](https://github.com/btcsuite/btcd/blob/master/btcutil/psbt/utils.go#L253-L258).

Nice find! This should be easy enough to fix.
