### ISSUE TITLE
btcctl uptime command returns the current time, not the uptime

### ISSUE THREAD

**Issue by cec489** [btcsuite/btcd#2202]
I'm using utreexod, which is based on btcd.  The uptime command returns the current time:

~/utreexod/utreexod$ ./utreexoctl --datadir=/mnt/T9/utreexod/bridge-assume-prune uptime
1719253093
~/utreexod/utreexod$ date +%s
1719253095

Looks like this happens because the startupTime in the server struct is 0 when its set in the rpc server config.  startupTime is set later when the server Start() is called.

**Comment by cec489** [comment]
... same for btcd master branch

~/btcd/btcd$ ./btcctl uptime
1719255124

**Comment by chrisguida** [comment]
Confirmed, I'm also seeing this

**Comment by cec489** [comment]
PR was merged
