### ISSUE TITLE
getnetworkinfo core RPC introduced new field in json object.

### ISSUE THREAD

**Issue by ziggie1984** [btcsuite/btcd#2224]
The current master branch of bitcoin-core introduced a new field into the `getnetworkinfo` rpc json-response. We should adapt the btcd code to account for this however I am not sure how we should do this in a backwards compatible manner. Any suggestions from prior RPC updates of the core software ?

```
bitcoin-cli --regtest getnetworkinfo
{
  ...
  "warnings": [
    "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
  ]
}
```

```
diff --git a/btcjson/chainsvrresults.go b/btcjson/chainsvrresults.go
index 11c0483d..cfb75485 100644
--- a/btcjson/chainsvrresults.go
+++ b/btcjson/chainsvrresults.go
@@ -380,7 +380,7 @@ type GetNetworkInfoResult struct {
        RelayFee        float64                `json:"relayfee"`
        IncrementalFee  float64                `json:"incrementalfee"`
        LocalAddresses  []LocalAddressesResult `json:"localaddresses"`
-       Warnings        string                 `json:"warnings"`
+       Warnings        []string               `json:"warnings"`
 }

```

Thanks @michael1011 for pointing this out.

**Comment by stickies-v** [comment]
FYI see https://github.com/bitcoin/bitcoin/pull/29845 for more context. Old behaviour can temporarily be reverted via `-deprecatedrpc=warnings` as per the [release notes](https://github.com/stickies-v/bitcoin/blob/42fb5311b19582361409d65c6fddeadbee14bb97/doc/release-notes-29845.md) but this will be removed in a future version so best to upgrade when you can.

See also https://github.com/bitcoin/bitcoin/blob/master/doc/JSON-RPC-interface.md#versioning.
