### ISSUE TITLE
govulncheck failure on v0.24.x

### ISSUE THREAD

**Issue by notatestuser** [btcsuite/btcd#2267]
Someone smart has filed a security vulnerability for a consensus bug in btcd v0.24.x that blocks our build because we have a gate on govulncheck. We have tried to move around various versions but the entire v0.24.x tree appears to be blocked which our apps (and our dependencies) use.

We are only using btcd as a library, and not as a btc daemon, so the fact that there is a consensus bug does not matter to us or our app

Is there a fix on the way so that we can get past this? Thanks.

```
Run govulncheck -C . -format text ./...
=== Symbol Results ===

Vulnerability #1: GO-2024-3189
    Consensus failure in github.com/btcsuite/btcd
  More info: https://pkg.go.dev/vuln/GO-2024-3189
  Module: github.com/btcsuite/btcd
    Found in: github.com/btcsuite/btcd@v0.24.3-0.20241011125836-24eb8
    Fixed in: N/A
    Example traces found:
Error:       #1: xx/transaction.go:54:54: btc.MakeBitcoinSignedTxHex calls tss.BTCConvertToSignedTXHex, which eventually calls txscript.Engine.Execute
```

**Comment by kcalvinalvin** [comment]
Seems like an error on govulncheck's part because the fix is in v0.24.2-beta. Looks like it's just parsing the security tab on github. https://github.com/btcsuite/btcd/security/advisories/GHSA-27vh-h6mc-q6g8

Found this on govulncheck's doc

>In some cases, such as when a Go project uses its own versioning scheme, the mapping to standard Go versions can fail. When this happens, the Go vulnerability database report may conservatively list all Go versions as affected. This ensures that tools such as govulncheck do not fail to report vulnerabilities due to unrecognized version ranges (false negatives). However, conservatively listing all versions as affected may cause tools to incorrectly report a fixed version of a module as containing the vulnerability (false positives).
>If you believe govulncheck is incorrectly reporting (or failing to report) a vulnerability, please [suggest an edit](https://github.com/golang/vulndb/issues/new?assignees=&labels=Needs+Triage%2CSuggested+Edit&template=suggest_edit.yaml&title=x%2Fvulndb%3A+suggestion+regarding+GO-2024-2965&report=GO-XXXX-YYYY) to the vulnerability report and we will review it.

Looks like we just have to submit an edit. In the meanwhile, you can just ignore the error since v0.24.2 includes the fix.

**Comment by kcalvinalvin** [comment]
https://github.com/golang/vulndb/issues/3206

Submitted an issue.

**Comment by Roasbeef** [comment]
> Looks like it's just parsing the security tab on github

Was the notice incorrectly formatted? 

Here's what I see in the normal view:
![Screenshot 2024-10-17 at 10 23 46 AM](https://github.com/user-attachments/assets/4830f68d-7a8e-4cce-8712-a42feefa6805)

**Comment by notatestuser** [comment]
It's resolved now, thanks.

**Comment by kcalvinalvin** [comment]
> > Looks like it's just parsing the security tab on github
> 
> Was the notice incorrectly formatted?
> 
> Here's what I see in the normal view: ![Screenshot 2024-10-17 at 10 23 46 AM](https://private-user-images.githubusercontent.com/998190/377569809-4830f68d-7a8e-4cce-8712-a42feefa6805.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NzM0NDcsIm5iZiI6MTcyOTU3MzE0NywicGF0aCI6Ii85OTgxOTAvMzc3NTY5ODA5LTQ4MzBmNjhkLTdhOGUtNGNjZS04NzEyLWE0MmZlZWZhNjgwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwNDU5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2I5ZTMxNDg0MjIyNjFlZDBiZDRjODQ0MjljMWUyOWFlZDc3ZTM2NDIwMjUzYjEzN2YxMTYyNDhiM2M3NDY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JhpMs1jLve1oW6uPOP_Ff5iYKNjVx60jdWtSjQ2f5uI)

tbh not quite sure what they parsed. I saw the same but I guess they parsed something with the `-beta` suffix
