### ISSUE TITLE
Very slow block processing

### ISSUE THREAD

**Issue by stevenroose** [btcsuite/btcd#247]
I'm running btcd in Ubuntu Linux and it is syncing really slow.

I've mentioned this in the chat channel and most people suggested it was due to IO limitations. However, I'm monitoring file IO now and, although it spikes every now and then, there are often very long periods of no file IO at all.

I've just launched btcd after several days of being offline and this is my log output:
https://gist.github.com/stevenroose/d4b88d6dc0e1e5425b34

You can see the current block height when launched: "Syncing to block height 339784".

I have processing rates of about 1-4 blocks a minute.

**Comment by davecgh** [comment]
I've categorized this as an optimization.  The speed will be increasing with the upcoming database, chain, and concurrent download work.

**Comment by hjfreyer** [comment]
What's the timeframe on this? If it's not too far in the future, I'll probably be able to use this code before my blockchain catches up :P

**Comment by davecgh** [comment]
There isn't really an exact time frame on it yet, but there are now 3 pull requests up related to it (#380, #491, and #492).  There are still some things to be done before they are ready however and I'm not sure how long that will take.

I have seen some respectable speed ups on the initial block download with the referenced PRs (and extreme speedup in regards to serving data), but I do want to properly set expectations.  A lot of it depends on your hardware, so even with the new code, if you don't have a very beefy machine, it will still take a while.  There are roughly 82.5 million transaction to churn through as of the current time.  That is just _a lot_ of data to process.

As a point of reference however, from my initial testing on the new code in its current state (which isn't ready for prime time yet) it is roughly 2x faster at IBD on a 4 year old machine with a 7200 RPM Hitachi HDD.  As a further point of reference, it syncs faster than the current version of Bitcoin Core on the same machine.

Nevertheless, I want to make sure people aren't expecting miracles.  The initial sync is an extremely demanding process and will remain to be so until some fundamental scalability improvements are made to Bitcoin.

**Comment by hjfreyer** [comment]
What sort of duration would you expect for a full sync? I have a 2 year old
server with decent specs, and I'm running btcd inside a VM in virtualbox
(because the voices echoing in my tinfoil hat told me to).

With bootstrap.dat, I got to late 2014 in maybe 2 days. I've been trying to
catch up with the p2p network for at least another couple days, and it's a
in March 2015.

**Comment by davecgh** [comment]
My latest times for full sync as of around block 370,000 on the aforementioned (I haven't tried it in a VM) machine were as follows:

- Current btcd code: ~20 hours
- Current BC Code: ~17 hours
- Development btcd code (the referenced PRs and a bit more that isn't in them yet): ~11 hours

I have more than one copy of the blockchain on my local network, so I took these figures using `--connect` to the same local instance to be fair in the comparison.

In my experience with VMs, they typically have extremely poor I/O performance, especially VirtualBox shared folders which are just abysmal.

**Comment by hjfreyer** [comment]
Yeah, I discovered that as a huge problem (processing the blockchain over
NFS = not happy). Now I'm using a VDI attached to the VM, which is much
better, but perhaps still not so great.
