### ISSUE TITLE
checkTransactionStandard not used.

### ISSUE THREAD

**Issue by jongillham** [btcsuite/btcd#248]
I noticed package private [`checkTransactionStandard`](https://github.com/btcsuite/btcd/blob/a57505b7f02f3692a818c935815ceddb1f3b562c/mempool.go#L227) does not seem to be called from anywhere within the `btcd` package (according to GitHub search).

Just wanted to make sure that this is supposed to be the case.

**Comment by Roasbeef** [comment]
`checkTransactionStandard` is used, right [here](https://github.com/btcsuite/btcd/blob/a57505b7f02f3692a818c935815ceddb1f3b562c/mempool.go#L856).

**Comment by jongillham** [comment]
Hah, in the same file. Will just grep in the future.
