### ISSUE TITLE
btcd Adding lots of orphan blocks

### ISSUE THREAD

**Issue by carryforward** [btcsuite/btcd#253]
the symptoms seem slightly different from earlier bug reports.  BTCD is running on a VM.

http://pastebin.com/5AmhYgte

This is a fresh install from btcsuite.  I did copy the leveldb block database from an existing installation though.  is that part of the problem?  can I not just copy ~/.btcd/data/testnet/ from one system to another?

**Comment by davecgh** [comment]
In theory, you should be able to copy the database from one system to another.  I have not tried it personally though.

That said, I see from your log that it appears like it didn't pick up the database.

> 14:46:09 2015-01-23 [INF] BTCD: Block database loaded with block height 0

That should be a higher number if the database was already loaded.  

Also, after that there is:
> 14:46:22 2015-01-23 [WRN] BCDB: Failed to insert block 000000004e0fdac82b6e3c5b9212f2d438f122f1a086ae8d137b020ce2c54d05 000000007718fc70e720dffe2e7722eacee66c5698a89e0b8fbca781e02c1994 requested block does not exist
> 14:46:22 2015-01-23 [ERR] BMGR: Failed to process block 000000004e0fdac82b6e3c5b9212f2d438f122f1a086ae8d137b020ce2c54d05: requested block does not exist

Which was the start of it.  Once it failed to insert the block (1224), everything else is considered an orphan, so that makes sense.

Now, based on the log, I don't see why it couldn't find block 1223 since it should have just been loaded.  Do you still have your database log (~/.btcd/data/testnet/blocks_leveldb/LOG)?  I'd like to see if there is a failure in there.


Something to note, there is currently a lot of ongoing work in regards to the database and concurrent downloads which will end up making the sync code a whole lot more robust and putting the blocks on the filesystem versus in the database (for the default back end).  This in turn will offer a lot more flexibility in the ability to fix corrupt blocks, recreate the metadata in the event of corruption there, and several other nice recovery properties.

However, in the mean time, the only real solution to a corrupt db is to nuke it.  I know that is certainly not ideal.

**Comment by carryforward** [comment]
ok, that initial 0 height was from when I started without the DB in place.  I deleted the start of the DB it generated and substituted in a complete one from another system. 

bummer, I ran btcd again after seeing this error.  the LOG or LOG.old file does not cover the errored period. 

I did however take a snapshot of my VM.  I just reset it to a few days ago and the latest error is repeatable.  These VMs making problems repeatable are awesome.

Here is the log of what I did again.

do we know if the testnet was forked?  this was the latest error I saw:

19:18:01 2015-01-26 [INF] BMGR: Rejected block 00000000aaadef16414b69380fcceab75cac644ce02b3b01317c24518ab7777d from 144.76.175.228:18333 (outbound): failed to validate input 446cf3681e812692fc94f6dc8c3d8acd8eadf3a1683c3e9febded41ee016d38d:144 which references output f76087623f0923d26cd710c714816b687aeb0e77f73c94d5261dfd8ce3f306b2:230 - execute fail, fail on stack (input script bytes 47304402201f3e708f47940a2aa443ddf5de2f972c07c83ef2c1040a3125aceaffc443981502203f4e358d691107b82b4493a4d1fa30cdeeef35e749cd3f4ec491ab51c143887b0121036544ac4fbd4a09184eea5d7a10b35593dee210d4045209c661c1ce660cc3ba6a, prev output script bytes 76a914c8e778f26911cd5da3715377d2096971b281e08c88ac)


execute fail, fail on stack sounds like maybe a consensus issue?

btcd.log
http://pastebin.com/y5bVQrZp

LOG
http://pastebin.com/pdM5efDy


I can probably repeat it again.  If you would like, I can send you my VM snapshot.

**Comment by carryforward** [comment]
After it added tons of orphans last time it stopped for several minutes and I had to ctrl-c it.  I ran btcd again and it was still ~300 blocks behind.

It caught up fine to full height the 2nd time.

btc.log 2nd time
http://pastebin.com/HZWu6Q5S

LOG 2nd time
http://pastebin.com/uApnLRns

**Comment by carryforward** [comment]
it is complaining about this transaction:
https://www.biteasy.com/testnet/transactions/446cf3681e812692fc94f6dc8c3d8acd8eadf3a1683c3e9febded41ee016d38d
with this address:
myqEjQc7oRWY9EGCBvocfkjb3cAmhbnDgG
spending this transaction:
https://www.biteasy.com/testnet/transactions/f76087623f0923d26cd710c714816b687aeb0e77f73c94d5261dfd8ce3f306b2


doesn't look like something too out of the ordinary.

**Comment by davecgh** [comment]
Thanks for the additional details.

So the first question, that can't be a consensus issue since my local copy has that block and matches the current BC tip:

```
$ ./compare.sh getblockcount
BC: 319728
btcd: 319728

$ ./compare.sh getblockhash 319728
BC: 0000000075c4e305ca7c47add0ae3283c077fe2dc8ec19f44beb204cfb0d5fa8
btcd: 0000000075c4e305ca7c47add0ae3283c077fe2dc8ec19f44beb204cfb0d5fa8
```

Looking at that particular transaction, I see that the bytes don't match what you pasted:
```JSON
{
	"txid": "f76087623f0923d26cd710c714816b687aeb0e77f73c94d5261dfd8ce3f306b2",
	"vout": 144,
	"scriptSig": {
		"asm": "3045022100b19864cbcd338b57110eff41d272b5373c1bf9c63eb8f948ec53b1f58263a469022016ff251fd0f0177c5612c5af47e296401e7d7cafe8ffe34338d2a466a01e488801 0270734fd59959e722e69a3da2ff34f6e4a9f4ddc70c9746ee2581dd61cf390b4f",
		"hex": "483045022100b19864cbcd338b57110eff41d272b5373c1bf9c63eb8f948ec53b1f58263a469022016ff251fd0f0177c5612c5af47e296401e7d7cafe8ffe34338d2a466a01e488801210270734fd59959e722e69a3da2ff34f6e4a9f4ddc70c9746ee2581dd61cf390b4f"
	},
	"sequence": 4294967295
},
```

Notice how the hex starts with `48304502...` while what you pasted `47304402...`.

**Comment by davecgh** [comment]
Disregard the previous about the mismatched bytes.  I pulled the wrong txout.  My fault there.  It's still true that my local copy and several others I've asked all match, so the consensus isn't wrong.  Now, let me dig into the specific area to see what you actually hit.

**Comment by carryforward** [comment]
ok, I saw that and was trying to reproduce it.  

here is what my system says:

 btcctl --testnet -u xxx -P xxx getrawtransaction 446cf3681e812692fc94f6dc8c3d8acd8eadf3a1683c3e9febded41ee016d38d 1 | less

ins:
```
		{
			"txid": "f76087623f0923d26cd710c714816b687aeb0e77f73c94d5261dfd8ce3f306b2",
			"vout": 230,
			"scriptSig": {
				"asm": "304402201f3e708f47940a2aa443ddf5de2f972c07c83ef2c1040a3125aceaffc443981502203f4e358d691107b82b4493a4d1fa30cdeeef35e749cd3f4ec491ab51c143887b01 036544ac4fbd4a09184eea5d7a10b35593dee210d4045209c661c1ce660cc3ba6a",
				"hex": "47304402201f3e708f47940a2aa443ddf5de2f972c07c83ef2c1040a3125aceaffc443981502203f4e358d691107b82b4493a4d1fa30cdeeef35e749cd3f4ec491ab51c143887b0121036544ac4fbd4a09184eea5d7a10b35593dee210d4045209c661c1ce660cc3ba6a"
			},
			"sequence": 4294967295
		},
```

```
                {
                        "txid": "f76087623f0923d26cd710c714816b687aeb0e77f73c94d5261dfd8ce3f306b2",
                        "vout": 144,
                        "scriptSig": {
                                "asm": "3045022100b19864cbcd338b57110eff41d272b5373c1bf9c63eb8f948ec53b1f58263a469022016ff251fd0f0177c5612c5af47e296401e7d7cafe8ffe34338d2a466a01e488801 0270734fd59959e722e69a3da2ff34f6e4a9f4ddc70c9746ee2581dd61cf390b4f",
                                "hex": "483045022100b19864cbcd338b57110eff41d272b5373c1bf9c63eb8f948ec53b1f58263a469022016ff251fd0f0177c5612c5af47e296401e7d7cafe8ffe34338d2a466a01e488801210270734fd59959e722e69a3da2ff34f6e4a9f4ddc70c9746ee2581dd61cf390b4f"
                        },
                        "sequence": 4294967295
                },
```



btcctl --testnet -u xxx -P xxx getrawtransaction f76087623f0923d26cd710c714816b687aeb0e77f73c94d5261dfd8ce3f306b2 1 | less
```
                {
                        "value": 1e-05,
                        "n": 230,
                        "scriptPubKey": {
                                "asm": "OP_DUP OP_HASH160 c8e778f26911cd5da3715377d2096971b281e08c OP_EQUALVERIFY OP_CHECKSIG",
                                "hex": "76a914c8e778f26911cd5da3715377d2096971b281e08c88ac",
                                "reqSigs": 1,
                                "type": "pubkeyhash",
                                "addresses": [
                                        "myqEjQc7oRWY9EGCBvocfkjb3cAmhbnDgG"
                                ]
                        }
                },
```

```
                {
                        "value": 1e-05,
                        "n": 144,
                        "scriptPubKey": {
                                "asm": "OP_DUP OP_HASH160 129e246ea642e9f37ac142e1690ff4cbe72d3ef2 OP_EQUALVERIFY OP_CHECKSIG",
                                "hex": "76a914129e246ea642e9f37ac142e1690ff4cbe72d3ef288ac",
                                "reqSigs": 1,
                                "type": "pubkeyhash",
                                "addresses": [
                                        "mhDPuRkUWrhfsmp63Df8krqhhMwsRwRWX8"
                                ]
                        }
                },
```



It is probably just something funny from copying the levelDB over, but might be indicitive of something deeper.

**Comment by carryforward** [comment]
restored VM and cut off internet so no new blocks would download.  reran btcctl --testnet -u xxx -P xxx getrawtransaction f76087623f0923d26cd710c714816b687aeb0e77f73c94d5261dfd8ce3f306b2 1 | less

returned identical data as posted above.

turned internet back on and impressively btcd reconnected and started downloading blocks.

It started complaingin about a different transaction it didn't like before it started including orphans.  it didn't like this tx now: https://www.biteasy.com/testnet/transactions/e8005cae760fae93f86030fb9527a0c5fa576082b24be67d6785866638c5db67

found another gem too:
21:24:10 2015-01-26 [INF] BMGR: Rejected block 000000000000046ac9c4a2f168a735fe23feca1799486972cb0689e9ed2be59d from 192.241.225.155:18333 (outbound): block merkle root is invalid - block header indicates fabba363cf89400257f6a6d96151cc5a4dda9a9833639970ed5fcb4498dc6edb, but calculated value is 319d2d285ee905915e086034d867fae1b07390a79a50bc8190b8f7c85329f0ab

https://www.biteasy.com/testnet/blocks/000000000000046ac9c4a2f168a735fe23feca1799486972cb0689e9ed2be59d shows fabba... is correct.

I am going to run a ram check on my computer.  these errors don't seem consistant enough to diagnose.  

Dave, I'll let you decide if you want to close this one or not.  I feel this is something that got goofed up by copying the levelDB.

**Comment by davecgh** [comment]
This does look like something strange is going on with db corruption and/or memory.  I wrote this small snipped to execute the script in question and, as you can see, it verifies properly:

```Go
package main

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"io/ioutil"

	"github.com/btcsuite/btcscript"
	"github.com/btcsuite/btcwire"
)

func main() {
	txHex, err := ioutil.ReadFile("tx.hex")
	if err != nil {
		fmt.Println(err)
		return
	}

	txBytes := make([]byte, hex.DecodedLen(len(txHex)))
	if _, err := hex.Decode(txBytes, txHex); err != nil {
		fmt.Println(err)
		return
	}

	var tx btcwire.MsgTx
	if err := tx.Deserialize(bytes.NewReader(txBytes)); err != nil {
		fmt.Println(err)
		return
	}

	txInIdx := 144
	sigScript := tx.TxIn[txInIdx].SignatureScript
	pkScript, err := hex.DecodeString("76a914c8e778f26911cd5da3715377d2096971b281e08c88ac")
	if err != nil {
		fmt.Println(err)
		return
	}

	flags := btcscript.ScriptBip16 |
		btcscript.ScriptCanonicalSignatures |
		btcscript.ScriptStrictMultiSig
	engine, err := btcscript.NewScript(sigScript, pkScript, txInIdx, &tx, flags)
	if err != nil {
		fmt.Println(err)
		return
	}

	if err := engine.Execute(); err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println("Successfully verified")
}
```

Output:
```
Successfully verified
```

**Comment by davecgh** [comment]
This has been closed since the behavior points to hardware issues and is not reproducible.

**Comment by stevenroose** [comment]
Just for the record, I also bumped into loads of orphans when migrating my btcd from Arch Linux to Alpine Linux (and not having synced for a few weeks in between). While logging all the orphans, it hung and I had to restart it several times.
