### ISSUE TITLE
[txscript] Feature request: Export parseScript and opcode fields

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcd#267]
<a href="https://github.com/jonasnick"><img src="https://avatars.githubusercontent.com/u/2582071?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jonasnick](https://github.com/jonasnick)**
_Friday Oct 31, 2014 at 19:26 GMT_
_Originally opened as https://github.com/btcsuite/btcscript/issues/28_

----

Thank you for creating and maintaining btcscript.
As far as I can see, there is currently no possibility for external packages to parse the bytes from btcwire.MsgTx.TxOut[i].PkScript to an array of opcodes. The function parseScript achieves that, but is not exported.
In order to further process the script it is necessary that the fields of opcode and parsedOpcode are accessible.
Example of what could be possible:
```go
func printScriptPubkey(txOut *btcwire.TxOut) {
	scriptPubkey, _ := btcscript.ParseScript(txOut.PkScript)

	for _, op := range scriptPubkey {
		log.Println(op.Opcode.Name)
	}
}

```

**Comment by davecgh** [comment]
<a href="https://github.com/davecgh"><img src="https://avatars.githubusercontent.com/u/2115102?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [davecgh](https://github.com/davecgh)**
_Friday Oct 31, 2014 at 19:44 GMT_

----

Did you have something specific in mind you're trying to do?

There is already a function, [DisasmString](http://godoc.org/github.com/btcsuite/btcscript#DisasmString), to do the script disassembly.  There are also functions to get all pertinent details from a script such as [ExtractPkScriptAddrs](http://godoc.org/github.com/btcsuite/btcscript#ExtractPkScriptAddrs) ([example](http://godoc.org/github.com/btcsuite/btcscript#example-ExtractPkScriptAddrs)) and [GetScriptClass](http://godoc.org/github.com/btcsuite/btcscript#GetScriptClass).

 Accessing the opcodes themselves seems like something that callers should not be concerning themselves with as that seems to be the domain of the script engine.  I'm not 100% opposed to the idea, just simply trying to understand what use case you're after.

**Comment by davecgh** [comment]
<a href="https://github.com/jonasnick"><img src="https://avatars.githubusercontent.com/u/2582071?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jonasnick](https://github.com/jonasnick)**
_Friday Oct 31, 2014 at 21:16 GMT_

----

I agree that this is more about diagnosis and testing.
For that you do not really want to parse the output of DisasmString yourself given that the required function and datastructures are already available. Consider for example you want to record a potential malleability attack by checking if the scriptSig contains additional pushes.
Also, DisasmString does not include the actual OP_DATA_* that is being used.

**Comment by davecgh** [comment]
<a href="https://github.com/davecgh"><img src="https://avatars.githubusercontent.com/u/2115102?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [davecgh](https://github.com/davecgh)**
_Friday Oct 31, 2014 at 22:22 GMT_

----

Fair enough.  I suppose it could be useful to access the parsed opcodes for diagnosis/testing purposes.  That said, you can get all the pushed data with the [PushedData](http://godoc.org/github.com/conformal/btcscript#PushedData) function for your particular example.

I suspect the vast majority of things you'd want to do are already available, but I can see it might be a bit more flexible with raw access to the parsed opcodes.

**Comment by davecgh** [comment]
<a href="https://github.com/shazow"><img src="https://avatars.githubusercontent.com/u/6292?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shazow](https://github.com/shazow)**
_Saturday Nov 01, 2014 at 01:21 GMT_

----

+1, exporting the opcodes, or possibly just `opcodemap`, would make it more feasible to use btcscript to build arbitrary transaction Scripts. I was going to build my own lookup derived from `opcodemap` but then realized it was not exported. :(

**Comment by davecgh** [comment]
<a href="https://github.com/shazow"><img src="https://avatars.githubusercontent.com/u/6292?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shazow](https://github.com/shazow)**
_Saturday Nov 01, 2014 at 01:33 GMT_

----

Er, to clarify on how this is different from #5 (which I just noticed), this would also allow reusing this code for building our own assembler/scripting language without having to copypasta all the opcodes and keep them in sync.

**Comment by davecgh** [comment]
<a href="https://github.com/davecgh"><img src="https://avatars.githubusercontent.com/u/2115102?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [davecgh](https://github.com/davecgh)**
_Saturday Nov 01, 2014 at 01:38 GMT_

----

@shazow: As you noted, you can build arbitrary scripts with the [Script Builder](http://godoc.org/github.com/conformal/btcscript#NewScriptBuilder).  The opcodes themselves are exported already too, so you shouldn't have to copypasta them (e.g `btcscript.OP_CHECKSIG`).

**Comment by davecgh** [comment]
<a href="https://github.com/shazow"><img src="https://avatars.githubusercontent.com/u/6292?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shazow](https://github.com/shazow)**
_Saturday Nov 01, 2014 at 01:46 GMT_

----

@davecgh I mean rather to get a mapping from their semantic name to their logical value (`string{"OP_CHECKSIG"}` -> `byte{172}`)

**Comment by davecgh** [comment]
<a href="https://github.com/jrick"><img src="https://avatars.githubusercontent.com/u/1420313?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jrick](https://github.com/jrick)**
_Saturday Nov 01, 2014 at 03:50 GMT_

----

Instead of exporting the map, how about giving the opcodes their own exported type and making them a fmt.Stringer?

edit: actually if you wanted to go the reverse direction (from string to byte), opcodemap is not quite what you want, unless you created the reverse mapping in your own package.

**Comment by davecgh** [comment]
<a href="https://github.com/davecgh"><img src="https://avatars.githubusercontent.com/u/2115102?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [davecgh](https://github.com/davecgh)**
_Saturday Nov 01, 2014 at 04:50 GMT_

----

@jrick:  I think that is the opposite of what @shazow was talking about from what he posted.  It appears he wants to be able to look up `OP_CHECKSIG` by name and get the associated opcode value.  The only reason I see why you'd even want to do that is parsing a disassembly back into opcodes.  Otherwise you know what opcode(s) you want, so you can just do `btcscript.OP_XYZ`.

**Comment by davecgh** [comment]
<a href="https://github.com/shazow"><img src="https://avatars.githubusercontent.com/u/6292?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shazow](https://github.com/shazow)**
_Saturday Nov 01, 2014 at 18:21 GMT_

----

> The only reason I see why you'd even want to do that is parsing a disassembly back into opcodes.

Correct, one idea we were playing around with is building scripts by reading in human-readable semantic opcodes from a JSON payload or somesuch.

**Comment by davecgh** [comment]
I know it's been forever, but I'm about to work on this.  In an upcoming PR I've changed the opcode map over to an array since it provides a nice speed boost and every entry in the array is defined.

However, since the array includes the unexported opcode type which contains pointers to the internal functions and state, I don't want to export it directly.

Thus, what I'm thinking of doing is providing the following:

```Go
func LookupOpcode(opcode byte) string
```

Would that be sufficient to cover the use case?

**Comment by davecgh** [comment]
Another alternative would be to create a map at init time from the opcode array and export that.  For example:

```Go
var OpcodeByName map[string]byte

func init() {
	OpcodeByName = make(map[string]byte)
	// Populate it...
}
```

Any preferences?

**Comment by shazow** [comment]
Either should work for what I had in mind. :)
