### ISSUE TITLE
[txscript] Invalid signatures in opcodeCheckMultiSig validate invalid transactions

### ISSUE THREAD

**Issue by yrashk** [btcsuite/btcd#293]
While I am yet to fully verify my findings, my preliminary research (debugging an issue on my end plus reading opcodeCheckMultiSig's code).

The issue: if any of supplied signatures are invalid (in my case, sighashtype was missing), opcodeCheckMultiSig will silently skip that signature: https://github.com/btcsuite/btcd/blob/e7c7c3399ff7ee43057fb5c59aeb30359d0c0d2b/txscript/opcode.go#L1894-L1907

That in itself is not a big problem. However, if I read the signature verification code that follows it doesn't actually check whether `signatures`' length is actually `nsig` or more, making opcode push `true` on stack even with insufficient number of signatures (remember, at least one of them was invalid).

Am I missing anything?

**Comment by davecgh** [comment]
You are correct.  Very nice find.  We're pushing a pr shortly that fixes this case.

**Comment by yrashk** [comment]
Thanks!
