### ISSUE TITLE
goclean.sh unable to find /bin/find

### ISSUE THREAD

**Issue by roosmaa** [btcsuite/btcd#294]
It would seem that `./goclean.sh` is unable to find `/bin/find` on TravisCI: [logs](https://travis-ci.org/btcsuite/btcd/jobs/50260196#L775). Might be a problem?

**Comment by davecgh** [comment]
Thanks!  Yes, it should just be calling find without the /bin prefix.  It's not a huge issue, but it does prevent the coverage from being printed.  I'll submit a PR shortly to fix that.
