### ISSUE TITLE
secp256k1.go appears to be causing some errors for Google App Engine

### ISSUE THREAD

**Issue by ThePiachu** [btcsuite/btcd#297]
The long []byte array in the file appears to be causing some issues for Google App Engine - https://groups.google.com/forum/#!topic/google-appengine-go/YRsH3cWdql8 .

Is that data necessary for the library to function, or does it simply speed the process up?

**Comment by ThePiachu** [comment]
Perhaps the []byte array can be more compressed by switching

https://github.com/btcsuite/btcd/blob/master/btcec/genprecomps.go#L33

to http://golang.org/pkg/compress/zlib/#NewWriterLevel BestCompression

**Comment by jrick** [comment]
IIRC internally 6g (and the other gc compilers?) transforms `[]byte("string")` to `[]byte{'s', 't', 'r', 'i', 'n', 'g'}` to avoid the byte slice copy at runtime.  However, this can take up a lot of memory since each byte literal is stored as a big integer.  We may want to try using a string here instead of a byte slice.

**Comment by ThePiachu** [comment]
I couldn't directly change things to string in loadS256BytePoints(), since `if _, err := base64.StdEncoding.Decode(decoded, bp); err != nil {` requires []byte.

However, I did change `secp256k1BytePoints` to string and `bp := []byte(secp256k1BytePoints)` and now everything seems to work so far. Will do some more tests.

**Comment by davecgh** [comment]
I'll work up a pull request real quick which switches this to a string.

**Comment by davecgh** [comment]
@ThePiachu: Can you try with pr #298 please?

**Comment by ThePiachu** [comment]
It looks like it's working. Cool!

**Comment by davecgh** [comment]
Thanks for confirming.
