### ISSUE TITLE
btcd v0.9.0-beta for Windows x64: nothing happens on install

### ISSUE THREAD

**Issue by rippler** [btcsuite/btcd#301]
* Win 7 x64
* I click on downloaded btcd v0.9.0-beta installer package (btcd_standalone_0.9.0-beta_x64.msi), get prompted to accept to run it, and then nothing happens (the window disappears and install does not seem to continue)

**Comment by davecgh** [comment]
@rippler: This is the first I've heard of any issues with the installer on Win 7 x64.  Can you run it with the following command and submit the generated log?

`msiexec /i btcd_standalone_0.9.0-beta_x64.msi /l*v .\install.log`

**Comment by rippler** [comment]
@davecgh, same here, and I use Windows all the time. Solution to this nonsensical problem:
![windows-nonsense](https://cloud.githubusercontent.com/assets/4045519/6202221/5cfe5064-b518-11e4-8f66-5d802c33fa0c.jpg)
