### ISSUE TITLE
[rpc] Add support for JSON-RPC 2.0 batch requests

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcd#329]
The current RPC server only supports JSON-RPC 1.0 requests.  The JSON-RPC 2.0 spec added several things, one of which is the ability to batch several requests into one.  We need to add support for these batched requests.

I have some code which does this for the normal path if anyone gets to this before I get back around to it and wants a starting point, however there are various considerations that need to be made for supporting batching in the websockets path.  In particular, the websockets path supports the notion of some long-running requests, currently only rescan, executing asynchronously so the faster commands can continue to be executed while the long-running operation is performed asynchronously.  Thus, the interaction with batching must be carefully considered when one of the requests in the batch is one that is executed asynchronously.

**Comment by unsystemizer** [comment]
Any chance to have this completed for the next release?

**Comment by davecgh** [comment]
To be honest, unless somebody volunteers to work on this, it probably won't be done any time soon.  It's low on the priority list for us.  As I mentioned in the original issue, I have some unfinished code on a local branch (outdated now, but it should still work as a starting point) which does batching for the normal path that I'd be willing to share if someone wants to take this on.

**Comment by opacey** [comment]
Hi. Has there been any change in priority for adding JSON-RPC 2.0 Batch handling into BTCD?
Reading through the history (& #632) in fact I'm not completely clear what I want isn't already implemented. Building a client which grabs the headers (2000k per call makes this relatively fast even in serial calls) and then requests additional data such as TX count per block). That second step is infeasibly slow in RPC 1.0.

I am sending the following batch request (for example)...
[
    {"jsonrpc":"2.0", "id":"getblockhash1", "method":"getblockhash", "params":[58942]}, 
    {"jsonrpc":"2.0", "id":"getblockhash2", "method":"getblockhash", "params":[58943]}, 
    {"jsonrpc":"2.0", "id":"getblockhash3", "method":"getblockhash", "params":[58944]}
]

But getting this response from BTCD...
{
  "result": null,
  "error": {
    "code": -32700,
    "message": "Failed to parse request: json: cannot unmarshal array into Go value of type btcjson.Request"
  },
  "id": null
}

I'm in an environment which cannot handle websockets unfortunately. Is the above conclusive that batches are not implemented or am I calling incorrectly?

**Comment by davecgh** [comment]
This is a PR in our other project dcrd, https://github.com/decred/dcrd/pull/841, which implements it.  It has not finished the review process, but once it has been merged, that could be backported to btcd.

**Comment by stevenroose** [comment]
I'm working on gRPC support, I guess that would fix this issue as well.

**Comment by opacey** [comment]
More power to you davecgh and stevenrose! I look forward to playing as and when BTCSuite get to your PRs.

**Comment by Roasbeef** [comment]
We'll likely be porting over the PR from `dcrd` soon as for `lnd` at times, we need to fetch a ton of headers from `bitcoind`, which atm, forces us to create a new TCP connection for each request. Since they don't plan on supporting keep alive or anything like that, batching the requests is our only option, but can also be used to improve the performance of the `btcd` chain backend as well.

**Comment by karask** [comment]
Any update on btcd supporting JSON-RPC 2.0 batch requests?

**Comment by jakesyl** [comment]
In progress #1583
