### ISSUE TITLE
`getblock` returns slightly different difficulty than bitcoin core

### ISSUE THREAD

**Issue by arnuschky** [btcsuite/btcd#414]
Not sure if relevant, again just reporting differences.

bitcoin core:
```
{u'bits': u'1c2f7e80',
 u'confirmations': 38872,
 u'difficulty': Decimal('5.39005634'),
 u'hash': u'000000002625e7a7960aaeceaefdd7f187e9da93abaf097c11dde293dfbf08a0',
 u'height': 353665,
 u'merkleroot': u'818bd73d11d4cece7a8d73cc1173aa61a993f542f40c708db4a43ae10a84f736',
 u'nextblockhash': u'0000000025e1d96963213ebd2023861c3c157707e0cb76a76cb265cac8cca20e',
 u'nonce': 2880533359,
 u'previousblockhash': u'0000000021ca73c8b25d7d4dd887f8df891c6730f96bb063aa2a43acf515d127',
 u'size': 208,
 u'time': 1429984191,
 u'tx': [u'818bd73d11d4cece7a8d73cc1173aa61a993f542f40c708db4a43ae10a84f736'],
 u'version': 3}
```

btcd:
```
{u'bits': u'1c2f7e80',
 u'confirmations': 38872,
 u'difficulty': Decimal('5.39'),
 u'hash': u'000000002625e7a7960aaeceaefdd7f187e9da93abaf097c11dde293dfbf08a0',
 u'height': 353665,
 u'merkleroot': u'818bd73d11d4cece7a8d73cc1173aa61a993f542f40c708db4a43ae10a84f736',
 u'nextblockhash': u'0000000025e1d96963213ebd2023861c3c157707e0cb76a76cb265cac8cca20e',
 u'nonce': 2880533359,
 u'previousblockhash': u'0000000021ca73c8b25d7d4dd887f8df891c6730f96bb063aa2a43acf515d127',
 u'size': 208,
 u'time': 1429984191,
 u'tx': [u'818bd73d11d4cece7a8d73cc1173aa61a993f542f40c708db4a43ae10a84f736'],
 u'version': 3}
```

**Comment by davecgh** [comment]
That's just a human readable ratio of max pow limit over the bits field.  We've limited it to a precision of 2 whereas they limit it to 8.  The `bits` field is the one that actually matters.

You'll notice that the various block explorers show a different precision after the decimal as well.  I'll leave this open for a bit to give others a chance to comment, but this can be closed in my opinion.

**Comment by arnuschky** [comment]
Two digits sound reasonable to me, but again, we are not using this field.

Note that the two explorers you've mentioned only show a limited precision on their website. Both APIs report the exact same value as bitcoin core. (which is most likely running in the background, I guess)

**Comment by davecgh** [comment]
Fair enough.  It's a simple change and doesn't hurt anything to provide the extra precision.  I'll submit a PR in a few for it.

**Comment by arnuschky** [comment]
Confirmed working here, thanks.
