### ISSUE TITLE
`getrawtransactions` includes confirmations=0 for unconfirmed tx

### ISSUE THREAD

**Issue by arnuschky** [btcsuite/btcd#420]
Bitcoin core omits the field `confirmation` in case the transaction in unconfirmed, while btcd includes it with value 0.

Similar to #416

**Comment by davecgh** [comment]
Thanks.  I'll push a PR for it in a bit.  Similar to #416, missing versus 0 isn't really a big deal, but I'll change it for the sake of compatibility.

**Comment by arnuschky** [comment]
Confirmed working. Thanks.
