### ISSUE TITLE
Can't retrieve information for some tx

### ISSUE THREAD

**Issue by tam-vo** [btcsuite/btcd#424]
I can't retrieve information for some tx hash with method `getrawtransaction`, it returned an error: 
```
{"code"=>-5, "message"=>"No information available about transaction"}
```

Here is some example txes: 
tx_hash = "b89b702f8bfc2e4e93ea28880b865179d6fc3260a79b9a181878678cf2133372"
tx_hash = "66e088e95b29f6bfc0e565d62376b9c0bc154f142d178853dd05f88af9fcf678"

Though I can find out those tx on blockchain. I also check other txes in same blocks and other works. Any suggestion?

**Comment by davecgh** [comment]
Are you running with the address index?  There was an issue where the address index could incorrectly remove transaction index entries that was fixed by #354.

**Comment by tam-vo** [comment]
Thanks for your quick reply. Let me update btcd and see it comes again. I close this issue for now. 

Have a nice day.

**Comment by dajohi** [comment]
@tam-vo update?

**Comment by tam-vo** [comment]
Thanks for your support, I haven't had a chance to upgrade that server, will work on that in today or tomorrow. I will close this ticket for now
