### ISSUE TITLE
Report latest git commit hash in --version

### ISSUE THREAD

**Issue by arnuschky** [btcsuite/btcd#431]
I would propose to report the hash of the latest git commit in `--version`. It would make it much easier to track what's installed when testing unstable builds, for example, determining whether the installed version includes a given fix. The version number itself is not very indicative for this unfortunately.

**Comment by davecgh** [comment]
You can do already this by providing an additional flag when running `go build`, but since go doesn't have any type of Makefiles, there is no way to automatically do this on a plain `go build`.  If you want to make a script however, you can have it do something like the following:

```bash
#!/bin/sh

go build -ldflags "-X main.appBuild $(git describe)" ./...
```

**Comment by arnuschky** [comment]
Awesome, works like a charm. This is absolutely sufficient for testing unstable versions.
