### ISSUE TITLE
`getblock` gives unknown nextblockhash

### ISSUE THREAD

**Issue by arnuschky** [btcsuite/btcd#432]
(this is on testnet)

`btcctl getblock 0000000094982ea624cbbdfd79d90cb3fe35256b169e6a0a1d1b962fd286bc82` returns `nextblockhash: 00000000c9f02d6ffd56531b02aa84fabc943339797d2db771017d179f349a52`.

However, block explorers and bitcoin core return `nextblockhash: 0000000048e450735930c6a8878df5465b5cf0ee487fcc2062bf778cc82515c4` for this block.

Interestingly, `0000000048e450735930c6a8878df5465b5cf0ee487fcc2062bf778cc82515c4` appears in the btcd log as a fork while `00000000c9f02d6ffd56531b02aa84fabc943339797d2db771017d179f349a52` isn't mentioned in the log.

Log excerpt:
```
09:29:43 2015-05-14 [INF] BMGR: Processed 1 block in the last 20m1.17s (13 transactions, height 396716, 2015-05-14 11:29:41 +0000 UTC)
09:29:43 2015-05-14 [INF] CHAN: Adding orphan block 0000000044a9aa5a20afbb424429e70e13bcbe17e4f535f0b1e2172a4b6a13fe with parent 0000000048e450735930c6a8878df5465b5cf0ee487fcc2062bf778cc82515c4
09:29:43 2015-05-14 [INF] CHAN: FORK: Block 0000000048e450735930c6a8878df5465b5cf0ee487fcc2062bf778cc82515c4 forks the chain at height 396714/block 0000000094982ea624cbbdfd79d90cb3fe35256b169e6a0a1d1b962fd286bc82, but does not cause a reorganize
09:29:43 2015-05-14 [INF] CHAN: EXTEND FORK: Block 0000000044a9aa5a20afbb424429e70e13bcbe17e4f535f0b1e2172a4b6a13fe extends a side chain which forks the chain at height 396714/block 0000000094982ea624cbbdfd79d90cb3fe35256b169e6a0a1d1b962fd286bc82
09:49:43 2015-05-14 [INF] BMGR: Processed 2 blocks in the last 20m0.44s (38 transactions, height 396717, 2015-05-14 11:49:42 +0000 UTC)
09:49:43 2015-05-14 [INF] CHAN: EXTEND FORK: Block 000000000e59c2672c05ea72a2769af660eab19c8aee0ac670bfc78995be07b7 extends a side chain which forks the chain at height 396714/block 0000000094982ea624cbbdfd79d90cb3fe35256b169e6a0a1d1b962fd286bc82
10:09:45 2015-05-14 [INF] BMGR: Processed 2 blocks in the last 20m2s (137 transactions, height 396718, 2015-05-14 12:09:44 +0000 UTC)
10:09:45 2015-05-14 [INF] CHAN: EXTEND FORK: Block 00000000943559dc5b99f3da697c024752770e6ae06efb76707570b5e85aa10d extends a side chain which forks the chain at height 396714/block 0000000094982ea624cbbdfd79d90cb3fe35256b169e6a0a1d1b962fd286bc82
```

**Comment by arnuschky** [comment]
Note: `00000000c9f02d6ffd56531b02aa84fabc943339797d2db771017d179f349a52` is known to bitcoin core and btcd:

```
{
  "hash": "00000000c9f02d6ffd56531b02aa84fabc943339797d2db771017d179f349a52",
  "confirmations": 4,
  "size": 1596,
  "height": 396715,
  "version": 3,
  "merkleroot": "5ed8903709994258055b53151ec070ce42ba9e0922ddf25be78e426648118d35",
  "tx": [
    "cbcaae14b641029f58f2a109ef0516025506d6011136f524667e3d3dd246333a",
    "f02ab2ada1a14ba39907ea3934107fa33a2c1b449deaed9a41f3c47186a9ea9c",
    "568a4cc87b29bf43a1ec4d56f0634045ab64ddbe78468e22871d60e7bf648d87",
    "d5403e3f3928e80a79c2e5d6c8bcc1858c4a3c6dd523acc6a6d912e4fcb7b068",
    "dbbde3ad47217025e732fb974559996c10c24cedba15f5bfe5514815e287f986",
    "2848e079c92a3fac8865227bff2d05e9b6daf66932718603bd513f7b9a8b234e"
  ],
  "time": 1431601780,
  "nonce": 2720431412,
  "bits": "1d00ffff",
  "difficulty": 1,
  "previousblockhash": "0000000094982ea624cbbdfd79d90cb3fe35256b169e6a0a1d1b962fd286bc82",
  "nextblockhash": "00000000f0c2b2a8ba204a0e79f35204830f206997288bee76ab107a9bbbb6c2"
}
```

**Comment by davecgh** [comment]
This is the normal fork resolution process.  You see it more readily on testnet since people are often intentionally forking things around for testing purposes.

In this particular case some nodes saw one version of 396715 while other nodes saw a different version.  As soon as block 396716 showed up, one side of the fork won and everything converged.

**Comment by davecgh** [comment]
I should also mention the reason that block is unknown is because btcd does not store orphaned blocks.  So even though it say the block at one point, once the chain reorged away from it, the block became an orphan and thus discarded.

When the new database stuff is done, we'll probably provide an option to store old blocks that were orphaned simply for the purposes of historical research, but it's certainly not needed.

**Comment by arnuschky** [comment]
Thanks. Just came here to close this issue after I realized that the testnet produces constantly relatively long forks at the moment.
