### ISSUE TITLE
mempool: Rejected transactions send incorrect subcommand.

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcd#436]
Reported by @TheBlueMatt in IRC.

> < BlueMatt> my bitcoind log has some reject messages that are apparently from btcd nodes - "Reject block code 64: orphan transaction size of XXXX is larger than max allowed size of XXXX bytes: hash..."
> < BlueMatt> I'm hoping the bug is that the reject message should be a tx reject message, not a block reject message

The root cause of this is rejected transactions are currently setting the `Cmd` field of the `reject` message to `block` instead of the expected `tx`.

**Comment by dajohi** [comment]
Nice catch.  OK.
