### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by PavelNiedoba** [btcsuite/btcd#447]
My system is: uname -a
Linux akat 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64

when running:
go get -u github.com/btcsuite/btcd/...

i get bunch of errors:
only dbtest is created in /bin

github.com/btcsuite/fastsha256
src/github.com/btcsuite/fastsha256/sha256block_amd64.s: Assembler messages:
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:53: Error: junk `(SI)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:53: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:53: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:54: Error: operand size mismatch for `bswap'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:54: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:55: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:61: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:61: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:61: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:62: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:62: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:63: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:64: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:64: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:65: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:66: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:67: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:67: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:67: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:68: Error: too many memory references for `xor'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:68: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:69: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:69: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:70: Error: too many memory references for `xor'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:70: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:71: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:72: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:72: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:73: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:74: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:75: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:75: Error: too many memory references for `add'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:75: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:76: Error: too many memory references for `xor'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:76: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:77: Error: too many memory references for `xor'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:77: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:78: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:78: Error: too many memory references for `add'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:78: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:79: Error: too many memory references for `add'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:79: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:80: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:88: Error: too many memory references for `add'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:88: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:89: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:89: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:90: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:91: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:91: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:92: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:93: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:93: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:94: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:95: Error: too many memory references for `xor'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:95: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:96: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:96: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:97: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:98: Error: too many memory references for `and'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:98: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:99: Error: too many memory references for `xor'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:99: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:100: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:100: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:101: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:102: Error: too many memory references for `add'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:102: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:103: Error: too many memory references for `and'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:103: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:104: Error: too many memory references for `xor'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:104: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:105: Error: too many memory references for `add'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:112: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:112: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:113: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:113: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:114: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:115: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:115: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:116: Error: too many memory references for `and'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:116: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:117: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:118: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:118: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:119: Error: too many memory references for `and'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:119: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:120: Error: too many memory references for `xor'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:120: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:121: Error: too many memory references for `xor'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:121: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:122: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:122: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:123: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:123: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:124: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:125: Error: too many memory references for `and'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:125: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:126: Error: too many memory references for `xor'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:126: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:127: Error: too many memory references for `xor'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:127: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:128: Error: too many memory references for `add'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:133: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:133: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:134: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:134: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:135: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:135: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:136: Error: too many memory references for `add'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:136: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:137: Error: too many memory references for `add'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:140: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:140: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:141: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:144: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:144: Error: junk at end of line, first unrecognized character is `\'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:145: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:147: Error: no such instruction: `text ·block(SB),0,$264-32'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:148: Error: junk `(FP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:148: Error: too many memory references for `movq'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:149: Error: junk `(FP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:149: Error: too many memory references for `movq'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:153: Error: junk `(DX*1)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:153: Error: too many memory references for `lea'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:154: Error: too many memory references for `movq'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:155: Error: too many memory references for `cmp'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:156: Error: invalid instruction suffix for `je'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:158: Error: junk `(FP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:158: Error: too many memory references for `movq'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:159: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:159: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:160: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:160: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:161: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:161: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:162: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:162: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:163: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:163: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:164: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:164: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:165: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:165: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:166: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:166: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:169: Error: too many memory references for `movq'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:171: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:172: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:173: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:174: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:175: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:176: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:177: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:178: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:179: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:180: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:181: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:182: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:183: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:184: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:185: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:186: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:188: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:189: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:190: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:191: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:192: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:193: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:194: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:195: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:196: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:197: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:198: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:199: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:200: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:201: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:202: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:203: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:204: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:205: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:206: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:207: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:208: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:209: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:210: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:211: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:212: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:213: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:214: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:215: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:216: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:217: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:218: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:219: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:220: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:221: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:222: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:223: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:224: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:225: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:226: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:227: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:228: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:229: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:230: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:231: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:232: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:233: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:234: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:235: Error: invalid character '(' in mnemonic
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:237: Error: junk `(FP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:237: Error: too many memory references for `movq'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:238: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:238: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:239: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:240: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:240: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:241: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:242: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:242: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:243: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:244: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:244: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:245: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:246: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:246: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:247: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:248: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:248: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:249: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:250: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:250: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:251: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:252: Error: junk `(BP)' after expression
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:252: Error: invalid character '=' in operand 2
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:253: Error: too many memory references for `mov'
src/github.com/btcsuite/fastsha256/sha256block_amd64.s:256: Error: too many memory references for `cmp'

**Comment by davecgh** [comment]
Looks like you're trying to build it with a strange version of Go based on `go version xgcc (Ubuntu 4.9.1-0ubuntu1) 4.9.1 linux/amd64`.

I'm going to guess you have a old distro installed version.  Perhaps try `sudo apt-get remove gccgo`.

When Go is installed per the link given in the build instructions in [README.md](https://github.com/btcsuite/btcd#linuxbsdmacosxposix---build-from-source), the `$ go version` line should give `go version go1.4.2 linx/amd64`.

**Comment by annanay25** [comment]
I faced the same issue recently.
Just type 
```which go```
in your terminal. It will probably show ```/usr/bin/go```
Then type ```export PATH=$PATH:/usr/local/go/bin```
This should probably work.

**Comment by PavelNiedoba** [comment]
Thank you all for your help. The solution from annanay25 alone didn't help. I had to install go 1.4.2 from tar package. After that it compiled silently. Now I struggle to find out how to change network port, because 8333 is already used...

**Comment by davecgh** [comment]
https://github.com/btcsuite/btcd/blob/master/docs/configure_peer_server_listen_interfaces.md
