### ISSUE TITLE
No reconnection on peers

### ISSUE THREAD

**Issue by bclermont** [btcsuite/btcd#463]
I was syncing btcd (on non-default port) to my Bitcoin-Core (port ``8333``) with ``connect=127.0.0.1``:

Frequently, btcd get disconnected from bitcoin-core, running on the same host, which is weird, but anyway, when that happens btcd never seen to try to reconnect:

```
19:40:00 2015-07-16 [ERR] PEER: Can't read message from 127.0.0.1:8333 (outbound): unexpected EOF
19:40:00 2015-07-16 [INF] BMGR: Lost peer 127.0.0.1:8333 (outbound)
19:40:00 2015-07-16 [WRN] BMGR: No sync peer candidates available
```

it stays like that until I ctrl-c

**Comment by davecgh** [comment]
Interesting.  I'll do some testing with the same config, but btcd does have a retry with an increasing backoff (capping at 1 minute retries if memory serves) to keep the peers specified via `--connect`.

**Comment by davecgh** [comment]
I was able to reproduce this behavior and believe I have identified the cause.  I'll submit a pull request shortly for you to verify.

**Comment by davecgh** [comment]
@bclermont Would you mind trying out #464 to verify it fixes your issue?

**Comment by bclermont** [comment]
@davecgh look like it fixed the problem! thanks

**Comment by dajohi** [comment]
OK
