### ISSUE TITLE
logging of double-spends

### ISSUE THREAD

**Issue by CzechJiri** [btcsuite/btcd#493]
I have been running BTCD on several (ten plus) instances for a reasonable long time (days) and the instances spanning decent portion of the network

looking at the logs (running in debug level) and comparing them to double-spend transactions blockchain.info and few other sites, there is never any detection of double-spend for 

1. a transactions my BTCD pushes to peers (in another words there is never any sign of peers rejecting that TX as double-spend). I can see the TX being pushed and I can see some peers (not all) acking the message, but never any rejection. 

2. my BTCD never logs its own rejection (transaction being pushed to my node)

I certainly do not expect to catch every single double-spend, but not being able to see single one is a bit strange.

Is this expected BTCD and wire logging behavior?

**Comment by davecgh** [comment]
If I understand what you're asking correctly, you want to see when a remote peer responds with a reject message, correct?

The is a debug level message in the PEER subsystem (though it contains all messages not just rejects).  To enable that you could either use `btcctl debuglevel PEER=debug` or start btcd with `-d PEER=debug`.

**Comment by CzechJiri** [comment]
thank you for quick response, will give it a try

**Comment by davecgh** [comment]
Just saw your edits. So if you're already running with debug logging turned on (via `-d debug` at start or `btcctl debuglevel debug` at runtime), it will already be debug logging for all subsystems, so doing it specifically for `PEER` won't add any more information (though you could limit it to only `PEER` debug messages if that's what you wanted).

In the case of number 1, you should be seeing the reject message from the `PEER` subsystem that looks like this:
> 16:05:25 2015-08-26 [DBG] PEER: Received reject (cmd tx, code ##, reason ...) from 1.2.3.4:8333 (outbound)

This is assuming the remote peer is actually sending a reject message (older protocol versions didn't have it and some node just don't send it)

For the case of number 2, it's part of the `BMGR` subsystem and with debug logging enabled you should see:
> 16:05:25 2015-08-26 [DBG] BMGR: Rejected transaction 123...123 from 1.2.3.4:8333 (outbound): transaction 123...123 tried to double spend output 345...345:1

**Comment by CzechJiri** [comment]
yep, thats exactly what I would expect, but don't see these. If I simplify it a bit and derail from double-spend, I should see other rejects, for example Reject tx code 66: insufficient priority. I do not see those neither.

**Comment by davecgh** [comment]
As an update, I've been running it with debug logging enabled and I am seeing double spend rejects:

> 21:30:10 2015-08-27 [DBG] BMGR: Rejected transaction 4c8a2242aba9ea2f6bf962b83cd9dbaace91bbf55e4c93cabbad5007071614b0 from 148.251.151.71:38259 (inbound): transaction 4c8a2242aba9ea2f6bf962b83cd9dbaace91bbf55e4c93cabbad5007071614b0 tried to double spend output 6907ed9a5df4357e0abb6a80d1c868cad48f9f9118cf147492c3c8101c77a725:1
> 21:33:56 2015-08-27 [DBG] BMGR: Rejected transaction 24cc3c3467554a1a864a44f611ba36d83ae3f5f56f8a627a05875b54bfda9712 from 52.20.152.215:51562 (inbound): transaction 24cc3c3467554a1a864a44f611ba36d83ae3f5f56f8a627a05875b54bfda9712 tried to double spend output 5e242d31ecc1f84ebf7e4e7028b559ab9567cf557af5cde1f2129f2a0ca13cfe:20
> 21:33:56 2015-08-27 [DBG] PEER: Sending reject (cmd tx, code REJECT_DUPLICATE, reason transaction 24cc3c3467554a1a864a44f611ba36d83ae3f5f56f8a627a05875b54bfda9712 tried to double spend output 5e242d31ecc1f84ebf7e4e7028b559ab9567cf557af5cde1f2129f2a0ca13cfe:20, hash 24cc3c3467554a1a864a44f611ba36d83ae3f5f56f8a627a05875b54bfda9712) to 52.20.152.215:51562 (inbound)
> 21:33:56 2015-08-27 [DBG] BMGR: Rejected transaction 0e2521fc572b93a3e06de41af848f81462e570e509a1fc7376127ac54f9a58c9 from 52.20.152.215:51562 (inbound): transaction 0e2521fc572b93a3e06de41af848f81462e570e509a1fc7376127ac54f9a58c9 tried to double spend output 5e242d31ecc1f84ebf7e4e7028b559ab9567cf557af5cde1f2129f2a0ca13cfe:8
> 21:33:56 2015-08-27 [DBG] PEER: Sending reject (cmd tx, code REJECT_DUPLICATE, reason transaction 0e2521fc572b93a3e06de41af848f81462e570e509a1fc7376127ac54f9a58c9 tried to double spend output 5e242d31ecc1f84ebf7e4e7028b559ab9567cf557af5cde1f2129f2a0ca13cfe:8, hash 0e2521fc572b93a3e06de41af848f81462e570e509a1fc7376127ac54f9a58c9) to 52.20.152.215:51562 (inbound)
> 21:33:56 2015-08-27 [DBG] BMGR: Rejected transaction 884b8fa81d0e6d6ba04f744c5e9aad82825c3b2f18a8898f5ca58839ef57f2c3 from 52.20.152.215:51562 (inbound): transaction 884b8fa81d0e6d6ba04f744c5e9aad82825c3b2f18a8898f5ca58839ef57f2c3 tried to double spend output 5e242d31ecc1f84ebf7e4e7028b559ab9567cf557af5cde1f2129f2a0ca13cfe:9
> 21:33:56 2015-08-27 [DBG] PEER: Sending reject (cmd tx, code REJECT_DUPLICATE, reason transaction 884b8fa81d0e6d6ba04f744c5e9aad82825c3b2f18a8898f5ca58839ef57f2c3 tried to double spend output 5e242d31ecc1f84ebf7e4e7028b559ab9567cf557af5cde1f2129f2a0ca13cfe:9, hash 884b8fa81d0e6d6ba04f744c5e9aad82825c3b2f18a8898f5ca58839ef57f2c3) to 52.20.152.215:51562 (inbound)
> 21:33:56 2015-08-27 [DBG] BMGR: Rejected transaction 2b838d08e5a8448074b684bb7bb32a35eb821f365dd1c63de8a5e717ec912b73 from 52.20.152.215:51562 (inbound): transaction 2b838d08e5a8448074b684bb7bb32a35eb821f365dd1c63de8a5e717ec912b73 tried to double spend output 5e242d31ecc1f84ebf7e4e7028b559ab9567cf557af5cde1f2129f2a0ca13cfe:18
> 21:33:56 2015-08-27 [DBG] PEER: Sending reject (cmd tx, code REJECT_DUPLICATE, reason transaction 2b838d08e5a8448074b684bb7bb32a35eb821f365dd1c63de8a5e717ec912b73 tried to double spend output 5e242d31ecc1f84ebf7e4e7028b559ab9567cf557af5cde1f2129f2a0ca13cfe:18, hash 2b838d08e5a8448074b684bb7bb32a35eb821f365dd1c63de8a5e717ec912b73) to 52.20.152.215:51562 (inbound)
> 21:38:46 2015-08-27 [DBG] BMGR: Rejected transaction 1d3a778f715053466a0c91d201909baf2ece8c35f8f3f6146c2c57b85e39f56a from 52.20.152.215:51562 (inbound): transaction 1d3a778f715053466a0c91d201909baf2ece8c35f8f3f6146c2c57b85e39f56a tried to double spend output 4cb26e45ab589c20127b93313410d9e6601f00f779cf8ff482e103b29d4aba67:0
> 21:38:46 2015-08-27 [DBG] PEER: Sending reject (cmd tx, code REJECT_DUPLICATE, reason transaction 1d3a778f715053466a0c91d201909baf2ece8c35f8f3f6146c2c57b85e39f56a tried to doubl

One thing to keep in mind is that btcd limits each log file to 10MB and automatically rolls the logs with a max of 3 historical files.  When you have debug enabled, it logs a lot of information, so you'll probably only have about 4 to 5 hours of history in the logs given standard traffic rates.  Perhaps we should up those limits and make them configurable.

**Comment by CzechJiri** [comment]
very strange, still see nothing, but please close

**Comment by davecgh** [comment]
@CzechJiri: As I mentioned, double spend attempts aren't overly common to see since double spend txns typically don't relay due to being rejected.  As a result, I suspect they're just rolling out of the log history.

You might want to try increasing how much logging data is stored.  In `btcd/log.go`, there is the following line:
```Go
			<rollingfile type="size" filename="%s" maxsize="10485760" maxrolls="3" />
```

You can modify the `maxsize` and/or `maxrolls` as desired and rebuild btcd if you'd like to keep more logging data to see if that is what is happening.  The `maxsize` is per file and the `maxrolls` is the max number of history files to keep.  The settings shown here (the default in btcd) thus amounts to 3 historical files at 10MB each + the current log file for a max of 40MB.
