### ISSUE TITLE
Address Index fails due to levelbd corruption

### ISSUE THREAD

**Issue by T909** [btcsuite/btcd#510]
I have encountered a strange bug in the addrindex.  This *may* be due to the fact that I initially build the addrindex in 0.10, then in 0.11.1, it automatically re-build the index.

My btcd node was synced up to testnet, but was re-building the addrindex.  I got this error:

`
12:26:33 2015-09-28 [ERR] ADXR: Unable to look up the sha of the next target block (height 445080): leveldb/table: corruption on data-block (pos=795339): checksum mismatch, want=0x17f73090 got=0xf7e069a7 [file=102663.ldb]
`

Re-running btcd gave the same error, so I disabled addrindex, and used --dropaddrindex to get rid of it.  Then I re-built it.  I quickly got a different error:

`
12:30:31 2015-09-28 [ERR] ADXR: Unable to look up the sha of the next target block (height 44508): leveldb/table: corruption on data-block (pos=795339): checksum mismatch, want=0x17f73090 got=0xf7e069a7 [file=102663.ldb]
`

Height 445080 the first time, and height 44508 when rebuilding?  Strange huh?

I will delete the whole ~/.btcd/ and start over, maybe building addrindex concurrently with the blockchain will work better.  I'll post back on how that works.  Just thought that was an interesting bug.  Thanks to all the btcsuite crew!

**Comment by davecgh** [comment]
Thanks for the report.  It looks like the leveldb file `102663.ldb` got corrupted.  Leveldb uses LSM (log-structured merging) under the hood, so the correlation of the numbers makes sense if the corruption happened in a higher level, which is almost surely the case here.

Rather than deleting the entire `~/.btcd` directory which nukes the conf file too, you can just delete the data directory.

**Comment by davecgh** [comment]
I'm going to close this as there isn't really anything to be done here.

**Comment by vladyslav2** [comment]
@davecgh thought that might be useful to somebody.
Today i got an error:
```
2018-03-07 10:05:46.389 [ERR] BTCD: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-039492]: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-039492]
2018-03-07 10:05:46.389 [INF] BTCD: Shutdown complete
```

Since bitcoin blockchain takes time to download, i found solution how it is possible to fix leveldb issues:
```
# pip install leveldb
# python
>> import leveldb
>> leveldb.RepairDB('~/.btcd/data/mainnet/blocks_ffldb/metadata')
>> leveldb.RepairDB('~/.btcd/data/mainnet/blocks_ffldb')
```

After this fix btcd was able to run again
