### ISSUE TITLE
signmessage fails for eligius ??

### ISSUE THREAD

**Issue by toddfries** [btcsuite/btcd#513]
It is easy enough to verify.   Find an address in your wallet, you don't even have to send coins to eligius to do this, just put the address in at:

 http://eligius.st/~wizkid057/newstats/mystats.php

and then go to 'Configuration Options' and then make any change, note the message to sign below, unlock your wallet, do:

   btcctl signmessage "&lt;address&gt;" "&lt;message&gt;"

and note eligius claims this fails.  If you can succeed where I have failed, I'll be glad to have done something wrong....

**Comment by davecgh** [comment]
Thanks for the report.  This should really be filed under github.com/btcsuite/btcwallet since btcd does not do any signing or handling of private keys.  I'll open the issue over there.

**Comment by toddfries** [comment]
urgle, sorry. github should permit moving issues between repos *grin*. closing with prejudice.

**Comment by davecgh** [comment]
This has been moved to btcsuite/btcwallet#323.
