### ISSUE TITLE
Mempool fee calculation should not be calculated per full kB

### ISSUE THREAD

**Issue by jrick** [btcsuite/btcd#521]
When Core added floating fees to their wallet the mempool behavior changed as well to calculate the fee as a percentage of the rate times the size (fee = rate * size / 1000), rather than using integer division first to calculate the full number of kilobytes of the transaction size (fee = (1 + size/1000) * rate).  This can cause transactions accepted by Core's mempool to be rejected by btcd's due to the fee being too low.

Example:

Given a transaction that is 1.5 kB large, and a fee rate of 0.00005 BTC/kB, Core would calculate the required fee to be 0.00075 (this equals the rate * 1.5).  btcd with the same fee rate would instead require the transaction to have a fee of at least 0.00010 (the rate * 2) because the size is greater than 1 kB but does not exceed 2 kB.

**Comment by davecgh** [comment]
Implemented by PR #537.
