### ISSUE TITLE
Not full blockchain

### ISSUE THREAD

**Issue by mathiasrw** [btcsuite/btcd#533]
Is it possible to let btcd work without keeping the whole blockchain?

I am aware that the whole blockchain is needed to verify the chain from the genesisblock to the latest verified block - but a lot of data is stored only for linking as a lot of blocks will only have transactions that are already spent. Maybe only storing the headers of blocks where all the transactions have been spent...

I guess my question is if its possible to optimize the size needed to let btcd help spread and verify new blocks...

**Comment by davecgh** [comment]
btcd does not currently support block pruning.  The work in PRs #380, #491, and #492 make infrastructure changes that will ultimately allow it to be supported.

**Comment by mathiasrw** [comment]
:+1:

**Comment by kikoncuo** [comment]
PRs seem merged, several years have passed, are we ever going to have prunning? will that be compatible with serving content to neutrino light clients? (I don't think so)
