### ISSUE TITLE
BIP101 support?

### ISSUE THREAD

**Issue by teran-mckinney** [btcsuite/btcd#541]
Hi,

Does btcd support BIP101? I did a quick search and found nothing on it. It'd be interesting if btcd could behave like bitcoin-xt.

Thank you,
Teran

**Comment by justusranvier** [comment]
Especially since there are BIP101 block currently being mined on testnet, a command line option to enable BIP101 support would be great so that btcd nodes can participate in that as well.

https://www.reddit.com/r/bitcoinxt/comments/3s08sl/bip101_on_testnet_is_coming_want_to_help/

**Comment by dajohi** [comment]
https://github.com/bitcoinxt/bitcoinxt/commit/946e3ba8c7806a66c2b834d3817ff0c986c0811b

**Comment by ashmoran** [comment]
I just came here to find out the same thing about btcd. Now BitPay is behind BIP101 and (like @justusranvier says) it's active on testnet, I've decided I will install and run a Bitcoin node. I was curious if btcd implemented BIP101, as to me having an alternative implementation is even more important for network democracy than a patched bitcoind.

**Comment by dajohi** [comment]
No, but it is on the TODO list.

**Comment by DeftNerd** [comment]
More and more groups are moving to support BIP101. I was curious about the position of this on the TODO list. Several mining pools have announced their support as well as Coinbase and Bitstamp.

**Comment by davecgh** [comment]
I will probably be able to start taking a look at it next week.

**Comment by dajohi** [comment]
https://github.com/bitcoinxt/bitcoinxt/commit/946e3ba8c7806a66c2b834d3817ff0c986c0811b

**Comment by OferE** [comment]
+1
This seems like an important feature. We need it in the core wallet as well, or the core wallet will be outdated.

**Comment by cypherdoc** [comment]
it's a good idea

**Comment by maddenw** [comment]
I agree, bcd would benefit from this greatly.

**Comment by hjfreyer** [comment]
So... drama, huh? Is btcd going to take a stance?

**Comment by davecgh** [comment]
After much deliberation, we've decided to close this issue without implementing it.  We're not against BIP101 in any way and if someone were willing to submit a PR that implements it properly as an optional parameter we'd be willing to accept it once it's in shape.

That said, we have limited development resources and given Mike has quit and Gavin seems to have moved on to Bitcon Classic, it doesn't seem likely that XT/BIP101 will gain widespread acceptance.

One of our devs has been looking at implementing BIP202 and that is the direction we're leaning in.

**Comment by luke-jr** [comment]
FYI: There is no such thing as BIP 202.

**Comment by davecgh** [comment]
Aye, I know it's not in the official repository.  For reference, I'm referring to [this BIP](https://github.com/jgarzik/bips/blob/87aacb6a58d3c63a5dd2082a566b763dd22f919e/bip-0202.mediawiki).  Any implementation would provide an opt-in flag for the user to make a choice.

**Comment by luke-jr** [comment]
That's BIP 108: https://github.com/bitcoin/bips/pull/263

**Comment by davecgh** [comment]
Ah, I missed the rename.  Thanks for the clarification.
