### ISSUE TITLE
[connmgr] Proposal to refactor connection logic into its own package

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcd#564]
The current code which handles establishing and maintaining a specific number of connections to other peers is tightly integrated into the server code.  While this is not problematic in and of itself, I would like to propose it be refactored into a separate sub-package named `connmgr` just like `wire`, `peer`, `txscript`, `addrmgr`, etc.

To be a bit more concrete, the package would handle all of the general connection concerns such as maintaining a set number of outbound connections, sourcing peers from seeds and the `addrmgr` package, banning, limiting max connections, tor, etc.

Ideally the refactor should be generic enough to allow the caller the flexibility to create their own types which can close over the peer state rather than having the package simply return a `peer.Peer`.  For more details on this point, see the `serverPeer` type in the current code.  This flexibility would allow the code to be used both by btcd proper and the SPV wallet work which is currently under development could ultimately make use of it, and it could also be useful in other scenarios.

In order to accomplish this, I think it would make sense to simply have the connection manger establish the connections as needed according to the configuration options and notify the caller (probably via a channel) with the established `net.Conn`.  The caller would then be responsible for creating a `peer.Peer` (likely with an enclosing state), setting its connection to the provided one, and notifying the connection manager when it goes away.

This would have a few benefits such as the ability to create mock connections in the testing framework that are independent of the Bitcoin-specific peer logic to ensure it works properly and help prevent regressions, allow the core server logic to be simplified down to only dealing with bitcoin-specific details, and, as previously mentioned, allow this fairly commonly needed functionality to be used externally.

Obviously I'm just spitballing here and the details will undoubtedly have to be tweaked once the actual work begins, but I think it's worth exploring.

**Comment by tuxcanfly** [comment]
Thanks, yeah this would help decouple the connection logic and remove a lot of duplicate code while implementing SPV wallet. Let me me take a dig at this and come up with a draft.

**Comment by jongillham** [comment]
@tuxcanfly are you still working on this?

**Comment by tuxcanfly** [comment]
@jongillham Yeah, I was playing around with some ideas on a local branch. I'll get that cleaned up and push it for review.

**Comment by davecgh** [comment]
This has been implemented and merged via PR https://github.com/btcsuite/btcd/pull/653.
