### ISSUE TITLE
[txscript] Sigcache Implementation Needs Optimization

### ISSUE THREAD

**Issue by davecgh** [btcsuite/btcd#575]
I was doing a bit of profiling for other reasons tonight and I noticed the recently added signature cache is taking way more CPU time than it should.  The following profile was generated when doing an initial block download, so there would be very few hits of the signature cache, nevertheless, as I've highlighted in the image, the signature cache additions and lookups are actually taking more time than the signature verifications!

![sigcachecpuprof](https://cloud.githubusercontent.com/assets/2115102/11605502/ed32b668-9ac6-11e5-87a7-83d41728bedc.png)

I'm fairly certain this is the result of using a struct as the map key, which, in my experience, typically results in poor performance and this case appears to be no exception.  I suspect making the map key a smaller fixed size array and using a fast hashing function (does not need to be a cryptographic hash function) to hash just the signature, then using that as the key would make a huge difference.  Note that doing this would obviously also require making the struct that currently acts as the key the value for the entry and then ensuring that any hits are actually matches (since collisions would now be possible).  In practice, the number of collisions that would require additional checking will be minimal and the more expensive full check would barely ever have to run in the case of cache misses.

**Comment by wallclockbuilder** [comment]
Apparently map key hashing for types: `int32`, `int64` and `string` is superfast due to a special case fast path designed into the runtime. Other types are condemned to slow hash times.

https://github.com/golang/go/issues/13271
