### ISSUE TITLE
Max peers possibly mis-counted

### ISSUE THREAD

**Issue by T909** [btcsuite/btcd#577]
I have a network setup with several btcd nodes but only one connects out to the internet, and the others sync with it over the LAN.  
A few times I've gotten loops where it keeps disconnecting and reconnecting to internal nodes.
It seems it may be counting connections that are in the process of closing and getting mixed up due to that.

10.0.30.10's btcd.conf:
```
testnet=1
addrindex=1
rpcuser= -
rpcpass= -

nodnsseed=1

maxpeers=5
connect=na
connect=104.131.6.40
connect=122.18.83.210

nolisten=0

minrelaytxfee=0.00001
rpclisten=
notls=0
```

Log example of the internet connected node (10.0.30.10):
```
17:02:00 2015-12-07 [INF] SRVR: Max peers reached [5] - disconnecting peer na:18333 (outbound)
17:02:00 2015-12-07 [INF] BMGR: New valid peer na:18333 (outbound) (/btcwire:0.3.0/btcd:0.12.0/)
17:02:00 2015-12-07 [INF] BMGR: Lost peer na:18333 (outbound)
17:02:05 2015-12-07 [INF] BMGR: New valid peer na:18333 (outbound) (/btcwire:0.3.0/btcd:0.12.0/)
17:02:05 2015-12-07 [INF] SRVR: Max peers reached [5] - disconnecting peer na:18333 (outbound)
17:02:05 2015-12-07 [INF] BMGR: Lost peer na:18333 (outbound)
```
... repeats every 5 seconds till I kill btcd.

and an example log from "na" (10.0.30.11) the node being disconnected:
```
04:01:22 2015-12-08 [INF] BMGR: Syncing to block height 617134 from peer 10.0.30.10:35848
04:01:22 2015-12-08 [INF] BMGR: Lost peer 10.0.30.10:35848 (inbound)
04:01:27 2015-12-08 [INF] BMGR: New valid peer 10.0.30.10:35850 (inbound) (/btcwire:0.3.0/btcd:0.12.0/)
04:01:27 2015-12-08 [INF] BMGR: Syncing to block height 617134 from peer 10.0.30.10:35850
04:01:27 2015-12-08 [INF] BMGR: Lost peer 10.0.30.10:35850 (inbound)
04:01:32 2015-12-08 [INF] BMGR: New valid peer 10.0.30.10:35851 (inbound) (/btcwire:0.3.0/btcd:0.12.0/)
04:01:32 2015-12-08 [ERR] PEER: Can't read message from 10.0.30.10:35851 (inbound): read tcp4 10.0.30.11:18333->10.0.30.10:35851: read: connection reset by peer
04:01:32 2015-12-08 [INF] BMGR: Syncing to block height 617134 from peer 10.0.30.10:35851
04:01:32 2015-12-08 [INF] BMGR: Lost peer 10.0.30.10:35851 (inbound)
04:01:37 2015-12-08 [INF] BMGR: New valid peer 10.0.30.10:35853 (inbound) (/btcwire:0.3.0/btcd:0.12.0/)
```

restarting the internet facing node fixes it, but the problem comes back and the walled off node will fall behind on blocks.

Hope this helps and can provide more logs / test things.  Thanks!

**Comment by davecgh** [comment]
@tuxcanfly: Can you take a look at this please?

**Comment by tuxcanfly** [comment]
Thanks, will do.

**Comment by T909** [comment]
Hi, adding some log data on these network issues.

This may be a slightly different problem but seems clearly related; with the above btcd.conf, I often lose sync with the network and need to restart btcd.  I've done that a number of times but this time I've got better logs.

With debug peer logs, I'm getting this:
```
00:41:13 2015-12-19 [DBG] PEER: Sending ping to 122.18.83.210:18333 (outbound)
00:41:58 2015-12-19 [DBG] PEER: Sending ping to na:18333 (outbound)
00:41:58 2015-12-19 [DBG] PEER: Received pong from na:18333 (outbound)
00:41:58 2015-12-19 [DBG] PEER: Received ping from na:18333 (outbound)
00:41:58 2015-12-19 [DBG] PEER: Sending pong to na:18333 (outbound)
00:43:13 2015-12-19 [DBG] PEER: Sending ping to 122.18.83.210:18333 (outbound)
00:43:58 2015-12-19 [DBG] PEER: Sending ping to na:18333 (outbound)
00:43:58 2015-12-19 [DBG] PEER: Received pong from na:18333 (outbound)
00:43:58 2015-12-19 [DBG] PEER: Received ping from na:18333 (outbound)
00:43:58 2015-12-19 [DBG] PEER: Sending pong to na:18333 (outbound)
00:45:13 2015-12-19 [DBG] PEER: Sending ping to 122.18.83.210:18333 (outbound)
00:45:58 2015-12-19 [DBG] PEER: Sending ping to na:18333 (outbound)
00:45:58 2015-12-19 [DBG] PEER: Received pong from na:18333 (outbound)
00:45:58 2015-12-19 [DBG] PEER: Received ping from na:18333 (outbound)
00:45:58 2015-12-19 [DBG] PEER: Sending pong to na:18333 (outbound)
```
na is a machine on the LAN which only connects to this btcd node, and that connection works fine.  The 122 node is no longer responding, but btcd doesn't seem to be bothered by that, hmm.
Looking at netstat:

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp    25164      0 10.0.30.10:49371        122.18.83.210:18333     ESTABLISHED
```
The TCP connection is still open with 122, but has a recv-Q that's not going down.  

A few minutes later:
```
00:53:13 2015-12-19 [DBG] PEER: Sending ping to 122.18.83.210:18333 (outbound)
00:53:58 2015-12-19 [DBG] PEER: Sending ping to na:18333 (outbound)
00:53:58 2015-12-19 [DBG] PEER: Received pong from na:18333 (outbound)
00:53:58 2015-12-19 [DBG] PEER: Received ping from na:18333 (outbound)
00:53:58 2015-12-19 [DBG] PEER: Sending pong to na:18333 (outbound)
```
Logs look the same, but TCP connection state is now CLOSE_WAIT, recv-q still there. 
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp    25319     32 10.0.30.10:49371        122.18.83.210:18333     CLOSE_WAIT 
```

And a few minutes later:
```
01:07:13 2015-12-19 [DBG] PEER: Sending ping to 122.18.83.210:18333 (outbound)
01:07:58 2015-12-19 [DBG] PEER: Sending ping to na:18333 (outbound)
01:07:58 2015-12-19 [DBG] PEER: Received pong from na:18333 (outbound)
01:07:58 2015-12-19 [DBG] PEER: Received ping from na:18333 (outbound)
01:07:58 2015-12-19 [DBG] PEER: Sending pong to na:18333 (outbound)
01:09:13 2015-12-19 [DBG] PEER: Sending ping to 122.18.83.210:18333 (outbound)
01:09:58 2015-12-19 [DBG] PEER: Sending ping to na:18333 (outbound)
01:09:58 2015-12-19 [DBG] PEER: Received pong from na:18333 (outbound)
01:09:58 2015-12-19 [DBG] PEER: Received ping from na:18333 (outbound)
01:09:58 2015-12-19 [DBG] PEER: Sending pong to na:18333 (outbound)
01:11:58 2015-12-19 [DBG] PEER: Sending ping to na:18333 (outbound)
01:11:58 2015-12-19 [DBG] PEER: Received pong from na:18333 (outbound)
01:11:58 2015-12-19 [DBG] PEER: Received ping from na:18333 (outbound)
01:11:58 2015-12-19 [DBG] PEER: Sending pong to na:18333 (outbound)
```
122 stops appearing in the logs, (01:09:13 is the last ping) and doesn't show up in netstat.  Btcd stays connected only to na:18333, and I need to kill / restart it to get back on the network.

I'm not exactly sure what the expected behaviour is here but I think it's supposed to drop the connections as soon as pings are not responded to.  I've only encountered this problem when using connect= hosts specified in btcd.conf.  Will keep looking at it and if I have time get into the server.go code.  Hope these logs are helpful.

**Comment by tuxcanfly** [comment]
@T909 Thanks for the logs. Let me try to repro and get to the root of this.

**Comment by T909** [comment]
Related to the network connections issues, I now have several computers running btcd connected to each other.  Running without addpeer= and connect= seems to work OK, but I still get some bugs.

Here's an interesting one I found.  The two machines' clocks are off by 10 seconds but it should be clear that they're both talking about the same events.

10.0.30.10:
```
14:03:27 2015-12-25 [DBG] PEER: Received inv (size 2) from 10.0.30.10:41652 (inbound)
14:03:27 2015-12-25 [DBG] PEER: Sending getdata (size 2) to 10.0.30.10:41652 (inbound)
14:03:27 2015-12-25 [DBG] PEER: Received tx (hash 68e2e0b7185abefd1c07ca6c6cf285acafc1ddce5bb84236dd76315f1c24b4ac, 5 inputs, 1 outputs, lock height 0) from 10.0.30.10:41652 (inbound)
14:03:27 2015-12-25 [DBG] PEER: Received tx (hash 03f97cc67c0f00836ed5a07506a728c7128513c290508fdc9cabff9a781f4b29, 5 inputs, 1 outputs, lock height 0) from 10.0.30.10:41652 (inbound)
14:03:32 2015-12-25 [DBG] PEER: Received inv (size 2) from 10.0.30.11:53920 (inbound)
14:03:32 2015-12-25 [INF] BMGR: Lost peer 10.0.30.10:41652 (inbound)
```
10.0.30.5 (prbx) (ahead by 10 sec):
```
14:03:37 2015-12-25 [DBG] PEER: Sending inv (size 2) to prbx:18333 (outbound)
14:03:37 2015-12-25 [DBG] PEER: Received getdata (size 2) from prbx:18333 (outbound)
14:03:37 2015-12-25 [DBG] PEER: Sending tx (hash 68e2e0b7185abefd1c07ca6c6cf285acafc1ddce5bb84236dd76315f1c24b4ac, 5 inputs, 1 outputs, lock height 0) to prbx:18333 (outbound)
14:03:37 2015-12-25 [DBG] PEER: Sending tx (hash 03f97cc67c0f00836ed5a07506a728c7128513c290508fdc9cabff9a781f4b29, 5 inputs, 1 outputs, lock height 0) to prbx:18333 (outbound)
14:03:42 2015-12-25 [DBG] PEER: Peer prbx:18333 (outbound) appears to be stalled or misbehaving, inv timeout -- disconnecting
14:03:42 2015-12-25 [INF] BMGR: Lost peer prbx:18333 (outbound)
```

**Comment by davecgh** [comment]
For reference, the part of this related to stalled peer due to not receiving an addr message is resolved by PR #586.

**Comment by Dirbaio** [comment]
I am also experiencing the maxpeers error. 

I think it's related to #586 as @davecgh says, however I think this seems a separate issue: somehow stall-kicked peers are not properly cleaned up. #586 fixes it for me simply because I see no more stall-kicks.

My setup:

Node A: desktop machine in my LAN, connected to no one. (dnsseeds removed)
Node B: My laptop, in the same LAN, with --connect to node A.

Node B would repeatedly connect to A then stallkick it due to #586, only to retry later. When it got to maxpeers (125 by default), it stopped retrying.

**Comment by davecgh** [comment]
Aye.  I agree there is another issue at play here and is why I left this one open.  Based on the described behavior and logs, I suspect the current peer count isn't being adjusted properly when a peer is forcefully disconnected.  Hopefully the additional details will help @tuxcanfly track it down.

**Comment by davecgh** [comment]
@tuxcanfly: FYI @Dirbaio was able to track this down and fix it via #587, so no need for you to spend any time on it.

**Comment by tuxcanfly** [comment]
Thanks for the fix @Dirbaio

**Comment by janschejbal** [comment]
I believe this issue is still present. With a client built from source mid-January, I'm getting the maxpeers message in the log with `netstat -tpen | grep btcd` returning 11 connections. Running on an ARM machine behind 1:1 NAT using `--externalip` and seeing both incoming and outgoing connections.

I believe #614 may help triggering this.
