### ISSUE TITLE
hang on shutdown caused by peer

### ISSUE THREAD

**Issue by dajohi** [btcsuite/btcd#583]
Perhaps @tuxcanfly can take a look.

Sending a SIGINT to btcd causes it to shutdown, and then it hangs after shutting down the block manager.

A trace shows thousands of these:

```text
goroutine 3791753 [chan send, 280 minutes]:
main.(*server).peerHandler.func4()
        /home/dhill/.go/src/github.com/btcsuite/btcd/server.go:1739 +0x3f
created by time.goFunc
        /home/dhill/git/go/src/time/sleep.go:129 +0x3a
```

**Comment by tuxcanfly** [comment]
Thanks, looking into it.

**Comment by jcvernaleo** [comment]
I've hit this too once or twice (but always in a situation where I couldn't get much debug info).

**Comment by tuxcanfly** [comment]
Trying to repro this but looking at the code I think it's an edge case where `peerHandler` is done but a new peer's `OnVersion` callback is fired. This would lead to hang on send to `newPeers` chan as it is no longer being received from `peerHandler`.

**Comment by jcvernaleo** [comment]
I've seen it more on very slow machines if that helps you reproduce it.

**Comment by tuxcanfly** [comment]
Thanks, will try that.
