### ISSUE TITLE
Half-node example

### ISSUE THREAD

**Issue by donovanhide** [btcsuite/btcd#6]
Hi,

apologies for this not really being an issue, but it might be an interesting exercise to replicate this example using your library packages:

https://raw.github.com/jgarzik/pynode/mini-node/node.py 

I'd like to mostly just listen to the bitcoin network with a mind to writing a mining pool in go (obviously a new block solution would have to be submitted back...). There's a lot of code in btcd, and was wondering if you could show an example of a "barebones" approach like jgarzik has?

Also, is it fully the case that btcd does not currently support multiple peers? Do you advise a personal instance of bitcoind to connect to for the moment? Should the peer management be a separate library package?

Thanks for the great code! Have learnt a lot about Bitcoin reading through it!

Cheers,
Donovan.

**Comment by davecgh** [comment]
For reference, the btcd peer code has now been refactored into a [separate package](https://godoc.org/github.com/btcsuite/btcd/peer).  It makes it much easier to do the type of things this issue is referring to.

**Comment by shazow** [comment]
:sparkles: :custard: :sparkles:
