### ISSUE TITLE
Bitcoin Classic compatibility

### ISSUE THREAD

**Issue by jzbz** [btcsuite/btcd#607]
Will btcd align with Bitcoin Classic and support the one time bump to 2MB blocks? I would like to continue running btcd on several of my nodes while supporting the increased block size. Thanks.

**Comment by davecgh** [comment]
Our general feeling about the block size debate is that the developers shouldn't be the ones dictating economic policy, rather the choice should be up to each individual stake holder.

Given that, I personally don't have any issues with a flag which allows classic rules.  However, in addition to bumping the block size, the flag would need to make sure it's user friendly in the sense once it's enabled it's not possible to disable without a full chain redownload because the rules are incompatible.  An alternative would be to store the chain for each rule set in a different directory.

**Comment by jzbz** [comment]
Thanks for elucidating your position on this. A flag as you have proposed would seem to be a fair method of implementation which would empower users. My preference with regards to blockchain storage would be a warning message and storage in the default directory as it would keep things simpler. Anyone who would set the classic flag and read the warning would likely be fully aware of the implications. Again thanks for taking the time to answer.

**Comment by rickw** [comment]
Thanks this is good. Are you planning on everything in https://github.com/gavinandresen/bips/blob/92e1efd0493c1cbde47304c9711f13f413cc9099/bip-bump2mb.mediawiki ?

**Comment by raedah** [comment]
> An alternative would be to store the chain for each rule set in a different directory.

How about logic that recognizes that point of divergence, stores that data once for before the fork, and separately for after the fork.

**Comment by ashmoran** [comment]
An idea just popped into my head over a coffee. This might be simplistic and naive, but could btcd not simply be changed to allow 2MB blocks, and leave it at that? 

btcd is not yet being used to mine (I don't think?!), so it would not be creating any blocks that would be rejected. And nobody is currently creating blocks >1MB, so it would not be trying to relay any in futility. In the event the network forks to a 2MB limit, btcd would be ready, and in the event it doesn't, it would continue to not relay the non-existent blocks. In the strange event the network starts mining >1MB blocks and then reverts, this would be presumably be handled as a normal re-org when the small-block chain overtook the big-block fork again. (In summary, it looks to me like a non-mining node can safely operate with any blocksize limit >= that of the miners.)

The more complex issue is that if a 2MB block is seen, it will be a Classic block, and therefore have a sighash limit set by https://github.com/bitcoinclassic/bitcoinclassic/commit/52caa87bb5a3074c4888d6afad8b292659f9acef … and that is, I presume, a very important thing for nodes to agree on. (I don't know how implicit numerical limits compare from Core to Classic based on this addition.)

I've no doubt overlooked innumerable things that I'm oblivious to or don't understand.

**Comment by gappleto97** [comment]
Tracking it Unlimited-style would negate the issue (not that I want to dictate how you run your project).

**Comment by rickw** [comment]
The SIGOP and SIGHASH limits are to prevent a CPU exhaustion attack, which would be easier with a 2MB bock. Gaven adjusted the limits to prevent this kind of attack.

**Comment by Roasbeef** [comment]
Bitcoin classic is dead.
