### ISSUE TITLE
SPV & Micropayment channels?

### ISSUE THREAD

**Issue by pobri19** [btcsuite/btcd#615]
Does this support SPV & Micropayment channels? If not, is there any plan to add support for this in the near future? Are there any other projects that do have support for this (written in Go)?

**Comment by davecgh** [comment]
btcd is a full node and has full support for bloom filters, so it does support SPV nodes connecting to it.

However, I think what you're after is whether or not there is library code for SPV.  There are packages for some of the fundamental pieces of SPV such as the [peer](https://github.com/btcsuite/btcd/tree/master/peer) and [bloom](https://github.com/btcsuite/btcutil/tree/master/bloom) packages.  However, there isn't a package for SPV chain handling and such yet.  @tuxcanfly is currently working toward adding SPV support to the wallet which will make more code of this nature available.

There is no code for micropayment channels.

**Comment by T909** [comment]
I have preliminary SPV functionality using the btcd libraries at https://github.com/LightningNetwork/lnd/tree/uspvdev/uspv
it's not quite done but is getting there, and hopefully can save you a lot of work if you're looking to use something like that yourself.

**Comment by davecgh** [comment]
@T909 Nice, I wasn't aware of that code.  Should be quite useful.

I'm going to close this since the question has been answered.
