### ISSUE TITLE
Blockchain stops processing after a while when the RPC server isn't used.

### ISSUE THREAD

**Issue by jongillham** [btcsuite/btcd#642]
I can recreate this problem if I set `btcd --norpc --maxpeers=4`. (Setting `--maxpeers` to something small like 4 makes the issue occur quicker.)

The cause seems to be that [`rebroadcastHandler`](https://github.com/btcsuite/btcd/blob/master/server.go#L2060) is not started so the buffered channel [`relayNtfnChan`](https://github.com/btcsuite/btcd/blob/master/server.go#L1968) never gets drained. The `relayNtfnChan` is populated by the mempool's [`ProcessTransaction`](https://github.com/btcsuite/btcd/blob/master/mempool.go#L976) method. `relayNtfnChan` is buffered by `MaxPeers` amount so when the buffer is full it blocks the main `btcd` processing loop.

Looking into this I noticed a couple of potential problems in the current code that would also need to be addressed:

1. `RelayNtfnChan` is never nil and some code paths bogusly rely on detecting if `RelayNtfnChan` is nil or not.
2. When the RPC server is disabled I believe transactions aren't relayed to other peers because [`rebroadcastHandler`](https://github.com/btcsuite/btcd/blob/master/server.go#L1960) isn't started. I feel it would be cleaner for the rebroadcasting of inventory and relaying of transactions functionality should be separated out our `rebroadcastHandler`.

This issue might be related to #605 which is what I initially looked into and how I stumbled on this. My dev computer and test server are ancient and always under high load just running the operating system and so far I've *never* managed to run `btcd` more than a couple of hours (with the RPC server running) without it stalling. Fixing this issue will hopefully help track down the root cause of #605.

I'm happy to look further into this and provide a fix but my analysis to this point has just been visual inspection of the code and using `pprof`. Can anyone else recreate this issue? Do you have any thoughts on the best fix?

**Comment by dajohi** [comment]
I believe you are on the right track..

1. mempool will become its own subpkg, so RelayNtfnChan could be nil as things other than btcd may use the package.

2. Yes, this is a bug and should be fixed.

**Comment by jongillham** [comment]
@dajohi I created pull request #643 that fixes this issue before your reply about RelayNtfnChan nil. The request removes the check for nil. I feel this is probably the appropriate thing to do with the codebase as it stands but am happy to change it back if you want.

**Comment by dajohi** [comment]
Please put the nil checks back.  The checks will be needed once mempool subpkg PR shows up making the diff bigger.

**Comment by jongillham** [comment]
Done.

**Comment by davecgh** [comment]
Fixed by #643.
