### ISSUE TITLE
Kernel killed process: out of memory while syncing

### ISSUE THREAD

**Issue by braydonf** [btcsuite/btcd#644]
syslog shows that btcd was killed:
```
Out of memory: Kill process 3988 (btcd) score 966 or sacrifice child
Killed process 3988 (btcd) total-vm:33018140kB, anon-rss:15721956kB, file-rss:0kB
```

This was before block height 247049 on livenet with v0.12.0-beta (https://github.com/btcsuite/btcd/commit/5c59b685e68b22adc2eaa258fe02a6d2e9fc3584), with configuration option `addrindex=1`.

**Comment by dajohi** [comment]
Can you try with the diff in
https://github.com/btcsuite/btcd/pull/686?

**Comment by dajohi** [comment]
@braydonf Can you try latest master?

**Comment by braydonf** [comment]
Yeah, pulled in the updates and syncing now. The height at 210949 and memory is around 200MB.

**Comment by braydonf** [comment]
Looks like this is no longer an issue, height is at 301892 with memory at 323MB
