### ISSUE TITLE
Implement BIP0068 and BIP0113

### ISSUE THREAD

**Issue by cjepson** [btcsuite/btcd#645]
BIP0068 and BIP113 are nearing merge in Core and should be implemented for btcd.

https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0113.mediawiki

**Comment by davecgh** [comment]
As I commented on #628, these will also also require [BIP0009](https://github.com/bitcoin/bips/blob/master/bip-0009.mediawiki).
