### ISSUE TITLE
Looking for more information on installing btcd and running a miner on a Mac

### ISSUE THREAD

**Issue by johnwhitton** [btcsuite/btcd#646]
Hi all,

I'm fairly new to the bitcoin world, have a little experience in Go and the Google Cloud Platform.
I'm trying to install btcd and create a Miner on my Mac as an educational exercise.
I've read the[ readme in docs](https://github.com/btcsuite/btcd/blob/master/docs/README.md).
I've downloaded and started btcd and it's currently downloading the blockchain.
I'm wondering if there are 
a) Any other reading material (e.g. a tutorial or video on setting up btcd as a miner)
b) The best slack or IRC channel for asking these sort of questions (I've joined [Bitcoin Core on slack](https://bitcoincore.slack.com/) and was recommended #bitcoin-dev or #bitcoin-wizards on https://webchat.freenode.net/)
Any advice is appreciated.

Regards,

John

**Comment by davecgh** [comment]
Closing this.  @johnwhitton joined IRC and discussions commenced there.
