### ISSUE TITLE
chainio.go assumes 64-bit ints

### ISSUE THREAD

**Issue by T909** [btcsuite/btcd#664]
Compiling for linux/arm7 I get:
```
# github.com/btcsuite/btcd/blockchain
blockchain/chainio.go:627: constant 4294967295 overflows int
```
The comparison numBitmapBytes > maxUint32 uses the output from utxoEntryHeaderCode:
```
func utxoEntryHeaderCode(entry *UtxoEntry, highestOutputIndex uint32) (uint64, int, error) {
```
which is an 'int' and depends on CPU architecture.  I tried replacing it but there's a bunch of functions and I don't know this code, so figured I'd just make the issue.

(Personally I don't even like that golang HAS arch-dependent ints but that's another story :)

**Comment by davecgh** [comment]
Thanks for the head up.  I agree that I don't like that is has arch dependent integers either.  I'll submit a PR to fix this shortly.

**Comment by davecgh** [comment]
I've submitted PR #665 to resolve this.
