### ISSUE TITLE
Conversion from leveldb to ffldb

### ISSUE THREAD

**Issue by rngadam** [btcsuite/btcd#672]
I've been spending a couple days trying to catch up to downloading the testnet blockchain. Upon rsync'ing what I had to another machine and installing a fresh version of btcd, I see the following:

```
23:10:27 2016-04-18 [WRN] BTCD: WARNING: There are multiple block chain databases using different database types.
You probably don't want to waste disk space by having more than one.
Your current database is located at [$HOME/.btcd/data/testnet/blocks_ffldb].
The additional database is located at [$HOME/.btcd/data/testnet/blocks_leveldb]
```

I see that the new version was pushed 6 days ago. 

How do I convert from blocks_leveldb to blocks_ffldb? Or do I have to start over?

**Comment by jrick** [comment]
There is no way to convert from one database format to another.  You will need to resync.

You can use a btcd running with the old database to serve blocks for another btcd with the new database, but the old database was especially slow at serving blocks, so this might not be any faster than downloading from remote peers.

**Comment by rngadam** [comment]
Here's what I tried:

leveldb:

```
cd ~/go/src/github.com/btcsuite/btcd
git reset --hard 123ff368f4cb0c0a9125e5450dfb806b9ec85efc
git build
rm $HOME/.btcd/data/testnet/peers.json
./btcd --testnet --listen 127.0.0.1 --nodnsseed --limitfreerelay=99999999
```

ffldb:

```
mkdir ~/go2
go get -u -v github.com/btcsuite/btcd/...
~/go2/bin/btcd --connect 127.0.0.1 --testnet  --norpc --nolisten
```

...but seems to have no effect, just cycles through "New valid peer, no sync peer, lost peer" without the ffldb btcd ever making progress.

the source shows:

```
00:51:19 2016-04-19 [INF] BMGR: New valid peer 127.0.0.1:33584 (inbound) (/btcwire:0.4.0/btcd:0.12.0/)
00:51:19 2016-04-19 [WRN] BMGR: No sync peer candidates available
00:53:04 2016-04-19 [INF] BMGR: Lost peer 127.0.0.1:33584 (inbound)
00:53:09 2016-04-19 [INF] BMGR: New valid peer 127.0.0.1:33586 (inbound) (/btcwire:0.4.0/btcd:0.12.0/)
00:53:09 2016-04-19 [WRN] BMGR: No sync peer candidates available
00:54:54 2016-04-19 [INF] BMGR: Lost peer 127.0.0.1:33586 (inbound)
00:54:59 2016-04-19 [INF] BMGR: New valid peer 127.0.0.1:33588 (inbound) (/btcwire:0.4.0/btcd:0.12.0/)
00:54:59 2016-04-19 [WRN] BMGR: No sync peer candidates available
```

**Comment by rngadam** [comment]
There's a way to import from bootstrap.dat, but no way to export to bootstrap.dat? In places where the network suck (China), it would be really useful to transfer the blockchain in alternative ways to encourage node creation. USB key for example... Or just when I when to create multiple nodes locally quickly.

**Comment by davecgh** [comment]
I was able to get this working with the following commands.  However, do keep in mind that `btcd` will ignore requests to serve block headers if the chain is not current, which is what I suspect you experienced based on your output.  That means you will either need to let the old database catch up completely before attempting to use it to serve or modify the code manually for the one serving (I added a diff at the bottom of this message with what to modify for that).

Old version (leveldb):

```
$ cd ~/go/src/github.com/btcsuite/btcd
$ git checkout -b pre_ffldb 123ff368f4cb0c0a9125e5450dfb806b9ec85efc
$ ....Optionally apply the diff to allow headers to be served when not synced....
$ go build -o btcdold
$ ./btcdold --testnet --connect=0.0.0.0 --listen=127.0.0.1
```

New version (ffldb):

```
$ cd ~/go/src/github.com/btcsuite/btcd
$ git checkout master
$ go build
$ ./btcd --testnet --connect 127.0.0.1 --norpc
```

```
00:37:15 2016-04-19 [INF] CHAN: Chain state (height 0, hash 000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943, totaltx 1, work 4295032833)
...
00:37:15 2016-04-19 [INF] BMGR: New valid peer 127.0.0.1:18333 (outbound) (/btcwire:0.4.0/btcd:0.12.0/)
00:37:15 2016-04-19 [INF] BMGR: Syncing to block height 722995 from peer 127.0.0.1:18333
00:37:15 2016-04-19 [INF] BMGR: Downloading headers for blocks 1 to 546 from peer 127.0.0.1:18333
00:37:15 2016-04-19 [INF] BMGR: Verified downloaded block header against checkpoint at height 546/hash 000000002a936ca763904c3c35fce2f3556c559c0214345d31b1bcebf76acb70
00:37:15 2016-04-19 [INF] BMGR: Received 546 block headers: Fetching blocks
00:37:15 2016-04-19 [INF] CHAN: Verified checkpoint at height 546/block 000000002a936ca763904c3c35fce2f3556c559c0214345d31b1bcebf76acb70
00:37:15 2016-04-19 [INF] BMGR: Reached the final checkpoint -- switching to normal mode
00:37:27 2016-04-19 [INF] BMGR: Processed 4110 blocks in the last 12.17s (7639 transactions, height 4110, 2012-05-26 14:25:28 -0500 CDT)
```

If you are willing to modify the source, you can force it to serve the headers when the chain isn't currently by modifying the `OnGetHeaders` function in `server.go` to comment out the check as follows.

```diff
$ git diff
diff --git a/server.go b/server.go
index 27ae18f..e86294c 100644
--- a/server.go
+++ b/server.go
@@ -692,9 +692,9 @@ func (sp *serverPeer) OnGetBlocks(p *peer.Peer, msg *wire.MsgGetBlocks) {
 // message.
 func (sp *serverPeer) OnGetHeaders(p *peer.Peer, msg *wire.MsgGetHeaders) {
        // Ignore getheaders requests if not in sync.
-       if !sp.server.blockManager.IsCurrent() {
-               return
-       }
+       //if !sp.server.blockManager.IsCurrent() {
+       //      return
+       //}
```

**Comment by davecgh** [comment]
I'm going to close this as the previous answer provides the means to do this.
