### ISSUE TITLE
Two btcd instanced on same machine keep losing connection

### ISSUE THREAD

**Issue by stevenroose** [btcsuite/btcd#697]
I setup one daemon that was synced up and listening to 8335 and another one with `connect=127.0.0.1:8335` that started from scratch.

However, they kept losing connection:

```
00:02:56 2016-05-19 [INF] BMGR: Syncing to block height 412025 from peer localhost:8335
00:02:56 2016-05-19 [INF] BMGR: Downloading headers for blocks 1 to 11111 from peer localhost:8335
00:04:41 2016-05-19 [INF] BMGR: Lost peer localhost:8335 (outbound)
```

I found this in the debug logs and the probable cause:

```
00:56:30 2016-05-19 [DBG] PEER: Peer 127.0.0.1:8335 (outbound) appears to be stalled or misbehaving, headers timeout -- disconnecting
```

That message occurred on the new (connecting) instance.

I talked about it with @davecgh and he could not immediately identify the issue. The receiving instance does not mention anything special about the other instance, just that it received a `getheaders` message.

Here are some more possibly relevant logs:
https://gist.github.com/stevenroose/5b69ed22d8fd35d8c04c564c0f3733b7
https://gist.github.com/stevenroose/a06184820c7b44c96d9728072ae2886a
https://gist.github.com/stevenroose/7e6265c06b505b4e51733b6b15eae883

**Comment by dajohi** [comment]
using different datadir's?

**Comment by dajohi** [comment]
Can you run with this diff on the server that has the blockchain?  See if any more logs pop up...

```
diff --git a/server.go b/server.go
index 008bb9a..d974ad5 100644
--- a/server.go
+++ b/server.go
@@ -691,6 +691,7 @@ func (sp *serverPeer) OnGetBlocks(p *peer.Peer, msg *wire.MsgGetBlocks) {
 func (sp *serverPeer) OnGetHeaders(p *peer.Peer, msg *wire.MsgGetHeaders) {
        // Ignore getheaders requests if not in sync.
        if !sp.server.blockManager.IsCurrent() {
+               peerLog.Warnf("Peer %v sent getheaders, but we are not current", p)
                return
        }
 
@@ -709,6 +710,7 @@ func (sp *serverPeer) OnGetHeaders(p *peer.Peer, msg *wire.MsgGetHeaders) {
                // to do.  Just return.  This behavior mirrors the reference
                // implementation.
                if endIdx == math.MaxInt32 {
+                       peerLog.Warnf("Peer %v sent getheaders, but endIdx == math.maxInt32", p)
                        return
                }
 
@@ -737,6 +739,7 @@ func (sp *serverPeer) OnGetHeaders(p *peer.Peer, msg *wire.MsgGetHeaders) {
                headersMsg := wire.NewMsgHeaders()
                headersMsg.AddBlockHeader(&header)
                p.QueueMessage(headersMsg, nil)
+               peerLog.Infof("Queued headers for peer %v", p)
                return
        }
 
@@ -792,6 +795,7 @@ func (sp *serverPeer) OnGetHeaders(p *peer.Peer, msg *wire.MsgGetHeaders) {
        }
 
        p.QueueMessage(headersMsg, nil)
+       peerLog.Infof("Queued headers for peer %v", p)
 }
 
 // OnFilterAdd is invoked when a peer receives a filteradd bitcoin
```

**Comment by davecgh** [comment]
I'm pretty sure that @dajohi is correct.  I know from IRC that the particular node in question was not in sync because it was building an address index for catchup.

**Comment by stevenroose** [comment]
@dajohi What branch did you make that patch on? I tried `git apply` but it gave me this:
```
# git apply /tmp/btcddiff
error: patch failed: server.go:691
error: server.go: patch does not apply
```

**Comment by stevenroose** [comment]
For the sake of trying I made the new node sync a little from other nodes (I ran without `connect=`), then I closed it and tried again with `connect=`. But still it fails receiving headers.

**Comment by davecgh** [comment]
I'm pretty sure it has to do with this.  Would you try commenting out [these](https://github.com/btcsuite/btcd/blob/f893558d782396f10c2fe49a8bc73deff4a36d14/server.go#L692-L695) lines.

**Comment by stevenroose** [comment]
@davecgh I commented out those lines and it works now.

**Comment by stevenroose** [comment]
Now I got this:
```
17:09:36 2016-05-21 [WRN] PEER: Misbehaving peer 127.0.0.1:59022 (inbound): getdata -- ban score increased to 66
```
right after the syncing client did this:
```
17:09:34 2016-05-21 [INF] BMGR: Received 33556 block headers: Fetching blocks
```

**Comment by davecgh** [comment]
@stevenroose:  Thanks for confirming.  Yes, that's because it's requesting data extremely quickly.

There are the `--nobanning` and `--banthreshold` options you can use to adjust it.
