### ISSUE TITLE
Normalizing bug with field.go when the number > P but the first word is less than P's first word.

### ISSUE THREAD

**Issue by jimmysong** [btcsuite/btcd#706]
Currently, for the normalization function in field.go, there is a final step for subtracting P from the number. This step should occur if and only if the number is greater than P. However, on closer inspection, this only happens if the first and second words of the number being normalized are BOTH greater than or equal to the first and second numbers of P. The situation where the first word is actually less but the second word is larger results in a normalized number that's greater than P, yet not properly modulo'ed.

This issue is a lot easier to demonstrate than describe. I am adding a pull request which adds two test cases to TestNormalize one of which fails with the current implementation.

**Comment by davecgh** [comment]
Thanks for the report.  I've confirmed this issue.  I'll push a PR shortly with a fix that is constant time.  I'll also squash and pull in your commits from #707 as a part of that PR so master stays green once merged.
