### ISSUE TITLE
extensible transaction validation engine

### ISSUE THREAD

**Issue by ggeorgiev** [btcsuite/btcd#714]
I need to implement an engine that supports the transaction protocol but is extensible. The current design of the library does not allow me to be able to do that due to lack if needed interfaces and/or having a lot of the implementation in private structures.

There are 3 main changes that I have to do:
1. Dynamic limits - I need to be able to set the limits per transaction
2. I need to be able to enable at least some of the disabled operations
3. I need the engine to be able to run scripts out of the context of a whole message (obviously depending operation will be disabled)

I can do all this in my own fork, but I am curious if you will be open if I contribute some changes to allow this or reduce the needed differences with the original.

Few examples of relatively low-risk changes that will make my task simple: rollback the conversion of the stack to a private structure to be able to use it from other packages or API to replace the opfunc in the opcode table.

Please let me know if this sounds like something that you are open for.

**Comment by davecgh** [comment]
Others are free to chime in, but my personal feeling is that I wouldn't want to modify the existing engine for these types of things.  The engine is intended to be a Bitcoin-specific scripting engine and therefore it's extremely important for it to conform exactly to the rules enforced by distributed consensus.  All of these cases mentioned here would put the onus on the caller to avoid breaking consensus.

**Comment by ggeorgiev** [comment]
Thanks, Dave

This makes sense. In your place, I would have done the same but I had to ask.
