### ISSUE TITLE
gopkg.io compatible release tags

### ISSUE THREAD

**Issue by ggeorgiev** [btcsuite/btcd#722]
Is there an important reason for the BTCD_ prefix over just v? It will be nice if the versioning tags are gopkg.in compatible. http://labix.org/gopkg.in

**Comment by jrick** [comment]
I also think we should be using the 'v' prefix, since that is what glide expects as well.

**Comment by jcvernaleo** [comment]
Based on this, are my decred tags wrong also or are they okay?

**Comment by jrick** [comment]
@jcvernaleo the decred tags look fine

**Comment by davecgh** [comment]
There is no reason other than existing convention.  We can change it on next release.

**Comment by onyb** [comment]
This can be closed, as we have moved to [semver](https://semver.org) tags since [**`v0.13.0-beta`**](https://github.com/btcsuite/btcd/releases/tag/v0.13.0-beta).
