### ISSUE TITLE
connect/disconnect cycling

### ISSUE THREAD

**Issue by jadeblaquiere** [btcsuite/btcd#725]
I have a test network (based off a fork of btcd) where I'm seeing frequent connect/disconnect cycling. I am able to replicate that condition using the current btcd and testnet. Simply starting two isolated nodes (--nodnsseed) on different networks I see the pattern: 
- Connect new inbound peer
- Lose connection to outbound peer
- Request getblocks from inbound peer
- Receive getblocks from inbound peer
- Connect to new outbound peer
- Disconnect inbound peer (timeout from request)
- Request getblocks from outbound peer
- Receive getblocks from outbound peer

Digging in a bit (see detailed logs attached from both nodes) it seems the peer disconnects because it didn't receive a response to the getblocks request. The nodes are in sync and no miners are connected so there aren't any new blocks to send. And that appears to create a problem as the peer doesn't reply because it checks for n > 0 and silently swallows the response ( see : https://github.com/btcsuite/btcd/blob/master/server.go#L675 )

So... this seems broken to me, but there are two logical fixes... either the inv response should be optional (i.e. don't disconnect the peer if we got nothing back because it could be an empty list) or the peer should always send a response, even if it is an empty list. 

I like the second approach better as ultimately it does make sense to disconnect unresponsive peers and it is more consistent. I've tested by taking the conditional out and that seems to resolve the issue. 

Is that the right solution? does this affect bitcoind compatibility?

Logs attached here for reference:

[loga.txt](https://github.com/btcsuite/btcd/files/402231/loga.txt)
[logb.txt](https://github.com/btcsuite/btcd/files/402237/logb.txt)

**Comment by dajohi** [comment]
I guess https://github.com/btcsuite/btcd/blob/master/peer/peer.go#L1202-L1238 needs more review.  MemPool should go for sure.

**Comment by dajohi** [comment]
@jadeblaquiere can you test https://github.com/btcsuite/btcd/pull/726 please?

**Comment by jadeblaquiere** [comment]
#726 works nicely to resolve that issue. Thanks!
