### ISSUE TITLE
Clean up rpctest temporary directories

### ISSUE THREAD

**Issue by chris-martin** [btcsuite/btcd#762]
Running `go test` seems to produce some temporary directories that never get deleted.

```
> ll -t /run/user/1000 | grep rpc
drwx------ 2 chris users  80 Sep 13 15:42 rpctest-0021673300
drwx------ 2 chris users  40 Sep 13 15:42 rpctest-data081335459
drwx------ 2 chris users  40 Sep 13 15:42 rpctest-logs628692902
drwx------ 2 chris users  40 Sep 13 15:40 rpctest-data718448051
drwx------ 2 chris users  40 Sep 13 15:40 rpctest-logs076466550
drwx------ 2 chris users  80 Sep 13 15:40 rpctest-0977415844
drwx------ 2 chris users  80 Sep 13 15:38 rpctest-0757085544
drwx------ 2 chris users  40 Sep 13 15:38 rpctest-data474711463
drwx------ 2 chris users  40 Sep 13 15:38 rpctest-logs877606618
drwx------ 2 chris users  80 Sep 13 15:34 rpctest-0081097919
drwx------ 2 chris users  40 Sep 13 15:34 rpctest-data539915026
drwx------ 2 chris users  40 Sep 13 15:34 rpctest-logs180238665
```

**Comment by davecgh** [comment]
Hmmm.  Is this with the latest code?  Does it happen on every run for you?

I ask because there is definitely code to remove the temp directories as seen [here](https://github.com/btcsuite/btcd/blob/0ddd10add60683ce24cafcc1d9b38832ad1920ef/rpctest/node.go#L166-L179).  Also, there was a [commit](bfe2ba41910873aa84bc896ae09ca0dad97e5ddd) that addressed teardown after the initial code went in.  Finally, I just tested it locally and see that it cleaned them up:

> $ go test
> PASS
> ok      github.com/btcsuite/btcd        0.995s
> $ ls -ald /tmp/rpctest*
> ls: no se puede acceder a /tmp/rpctest*: No such file or directory

**Comment by chris-martin** [comment]
On further inspection, it looks like it doesn't happen normally, but just happened when I briefly had my `PATH` set wrong, which leads to this result

```
unable to setup test chain:  exec: "btcd": executable file not found in $PATH
exit status 1
FAIL    github.com/btcsuite/btcd        0.069s
```

in which case cleanup doesn't seem to occur.

**Comment by davecgh** [comment]
Ok, yeah that makes sense.  I see that it doesn't try to tear down the harnesses unless they were fully and successfully setup.  However, the directories are created before the failure point, so they aren't being cleaned up in that case.

**Comment by davecgh** [comment]
Would you mind trying #763 with an invalid `PATH` to ensure it resolves the issue for you?  I have confirmed it works properly locally for me, but I prefer to have a second confirmation.

**Comment by chris-martin** [comment]
It isn't working for me.

The error message I'm getting is identical message from `rpcserver_test.go` - perhaps this fix needs to be added there as well?

**Comment by davecgh** [comment]
Did you run `go install` from the rpctest directory?  I noticed I had to do that so the test would use the new version.

**Comment by davecgh** [comment]
Alright, I updated the PR to address the main directory as well.

**Comment by chris-martin** [comment]
Looks good now!

**Comment by davecgh** [comment]
Great!  Thanks for confirming.
