### ISSUE TITLE
Nondeterministic test failure - "unable to setup test chain:  the client has been disconnected"

### ISSUE THREAD

**Issue by chris-martin** [btcsuite/btcd#766]
When I run the tests, sometimes they pass, but about 2/3 of the time they fail like this:

```
unable to setup test chain:  the client has been disconnected
FAIL    github.com/btcsuite/btcd        0.633s
ok      github.com/btcsuite/btcd/addrmgr        0.187s
ok      github.com/btcsuite/btcd/blockchain     0.558s
ok      github.com/btcsuite/btcd/blockchain/indexers    0.063s
ok      github.com/btcsuite/btcd/btcec  2.442s
ok      github.com/btcsuite/btcd/btcjson        0.027s
ok      github.com/btcsuite/btcd/chaincfg       0.010s
ok      github.com/btcsuite/btcd/chaincfg/chainhash     0.032s
?       github.com/btcsuite/btcd/cmd/addblock   [no test files]
?       github.com/btcsuite/btcd/cmd/btcctl     [no test files]
?       github.com/btcsuite/btcd/cmd/findcheckpoint     [no test files]
?       github.com/btcsuite/btcd/cmd/gencerts   [no test files]
ok      github.com/btcsuite/btcd/database       0.079s
?       github.com/btcsuite/btcd/database/cmd/dbtool    [no test files]
ok      github.com/btcsuite/btcd/database/ffldb 1.705s
ok      github.com/btcsuite/btcd/database/internal/treap        0.047s
?       github.com/btcsuite/btcd/limits [no test files]
ok      github.com/btcsuite/btcd/mempool        0.112s
?       github.com/btcsuite/btcd/mining [no test files]
ok      github.com/btcsuite/btcd/peer   0.039s
unable to setup test chain:  the client has been disconnected
FAIL    github.com/btcsuite/btcd/rpctest        0.538s
ok      github.com/btcsuite/btcd/txscript       0.653s
ok      github.com/btcsuite/btcd/wire   0.586s
```

**Comment by davecgh** [comment]
Are you running them in rapid succession?  If so, I would imagine it's because the tests are setting up btcd instances using the same ports, so if the previous one isn't completely shutdown yet, it'll end up failing due to being unable to bind on the ports.

**Comment by chris-martin** [comment]
> Are you running them in rapid succession?

No, I'm not.

**Comment by chris-martin** [comment]
Actually, I guess I'm not sure what you mean. I *am* running all of the tests at once, as in

    go test ./...

**Comment by davecgh** [comment]
Right, so there are tests in the main package that setup a test harness (`rpcserver_test.go`) and then the `rpctest` package tests themselves also setup the harness.  Since the tests often run in parallel, I would imagine you're hitting the case.

@Roasbeef and I have already discussed in IRC that we need to better handle the case of simultaneous users of the `rpctest` harness to prevent these type of spurious failures.

**Comment by Roasbeef** [comment]
@chris-martin running the `go test` command actually runs the tests for _each_ package in _parallel_. I ran into a similar issue with [`lnd`](https://github.com/lightningnetwork/lnd) as we use `rpctest` ourselves across several packages. The solution I ended up going with was just to [force the tests to be executed serially across all the packages](https://github.com/lightningnetwork/lnd/commit/803b66fd6d8b7aa1c4970b65375583fed6c4082e).

**Comment by chris-martin** [comment]
Thanks - maybe worth adding a note to the readme as well?

**Comment by chris-martin** [comment]
`-p 1` doesn't seem to have any effect, though just looping through the packages is good enough for my purposes:

    for pkg in $(go list ./...); do
      go test $pkg
    done

**Comment by davecgh** [comment]
Thanks for following up.  I'm going to go ahead an re-open this until the `rpctest` package itself is modified to allow parallel execution as I mentioned in #767 for tracking purposes.

**Comment by Roasbeef** [comment]
Hmmm that's odd, if you tack on the `-x` flag to the end of your `go test ./...` command you can see that  all the commands are being executing in parallel. While if one adds a `-p 1`, then they all flow serially. 

Taking a closer look at your initial post, it looks like the client connects, but then some error causes the connection to be severed, either by `btcd` or due to a client side error. 

Have you made any local modifications? Your current bash fragment should be equivalent to running all the tests recursively with the `-p 1` flag.

**Comment by davecgh** [comment]
@chris-martin: Would you mind giving your setup a try with #768?

**Comment by chris-martin** [comment]
@davecgh Seems to be working well for me.

**Comment by chris-martin** [comment]
It looks like I was misled by some intermittent successes - The test failures do still occur sometimes.

**Comment by davecgh** [comment]
Yes, it will still randomly happen depending on whatever other ports you have in use on your system as well as just luck of the draw so to speak.  However, it should still definitely be much better than previously where it was guaranteed to fail when run in parallel.

**Comment by chris-martin** [comment]
It doesn't seem to be much better.

**Comment by chris-martin** [comment]
All of the tests within a single invocation of `go test` seem to run with the same PID, so I'm not sure how this could make a difference.

**Comment by chris-martin** [comment]
Using a random port, however, seems to fix it.

**Comment by chris-martin** [comment]
Nevermind, I finally got a failure there too. So... I'm starting to think this has nothing to do with ports after all.

**Comment by chris-martin** [comment]
Is there any way I can get a more meaningful error message to debug instead of continuing to speculate?

**Comment by Roasbeef** [comment]
Is the error message you get always: 
> unable to setup test chain:  the client has been disconnected 

?



Also, can you provide us any additional (possibly relevant) details concerning your local environment? I'm still puzzled as to why running with `-p 1` didn't resolve the issue entirely for you locally. 

If you apply this diff locally, is the issue resolved?
```diff
diff --git a/rpctest/node.go b/rpctest/node.go
index c076a83..d2db7b6 100644
--- a/rpctest/node.go
+++ b/rpctest/node.go
@@ -149,12 +149,11 @@ func (n *nodeConfig) command() *exec.Cmd {
 // to the btcd process that is launched via Start().
 func (n *nodeConfig) rpcConnConfig() rpc.ConnConfig {
 	return rpc.ConnConfig{
-		Host:                 n.rpcListen,
-		Endpoint:             n.endpoint,
-		User:                 n.rpcUser,
-		Pass:                 n.rpcPass,
-		Certificates:         n.certificates,
-		DisableAutoReconnect: true,
+		Host:         n.rpcListen,
+		Endpoint:     n.endpoint,
+		User:         n.rpcUser,
+		Pass:         n.rpcPass,
+		Certificates: n.certificates,
 	}
 }
```

**Comment by chris-martin** [comment]
It is always that same output, yes.

I've tried enabling auto reconnect before - it causes the test to hang indefinitely instead of failing.

**Comment by chris-martin** [comment]
I am making modifications, but for the sake of this discussion I'm always talking about a branch that has no code changes - the only thing I've added here is a Nix shell configuration to assemble the GOPATH and run the tests.

**Comment by davecgh** [comment]
See #771 which was just merged.  @dajohi and I spent some time tracking it down and this is why the new dynamic port code was still failing for you periodically.

I plan to continue making improvements to the `rpctest` package error handling to hopefully make it a little easier to track down test failures like this.

**Comment by chris-martin** [comment]
#771 doesn't fix the failures for me, and I still really doubt this issue has anything to do with port selection.

**Comment by Roasbeef** [comment]
What do the logs look like on failure if you try this patch (with `git apply`)?

```diff
diff --git a/rpcserver_test.go b/rpcserver_test.go
index 1042292..c7551c5 100644
--- a/rpcserver_test.go
+++ b/rpcserver_test.go
@@ -124,6 +124,13 @@ func TestMain(m *testing.M) {
 		// ignored since this is already an error path and nothing else
 		// could be done about it anyways.
 		_ = primaryHarness.TearDown()
+
+		logs, err := primaryHarness.DumpLogs()
+		if err != nil {
+			fmt.Println("unable to grab logs: ", err)
+		} else {
+			fmt.Println(logs)
+		}
 		os.Exit(1)
 	}
 
diff --git a/rpctest/node.go b/rpctest/node.go
index c076a83..72555bd 100644
--- a/rpctest/node.go
+++ b/rpctest/node.go
@@ -166,7 +166,7 @@ func (n *nodeConfig) String() string {
 // cleanup removes the tmp data and log directories.
 func (n *nodeConfig) cleanup() error {
 	dirs := []string{
-		n.logDir,
+		//n.logDir,
 		n.dataDir,
 	}
 	var err error
diff --git a/rpctest/rpc_harness.go b/rpctest/rpc_harness.go
index 6fba7fc..431a996 100644
--- a/rpctest/rpc_harness.go
+++ b/rpctest/rpc_harness.go
@@ -393,6 +393,17 @@ func (h *Harness) GenerateAndSubmitBlock(txns []*btcutil.Tx, blockVersion int32,
 	return newBlock, nil
 }
 
+func (h *Harness) DumpLogs() (string, error) {
+	logFile := fmt.Sprintf("%v/simnet/btcd.log", h.node.config.logDir)
+
+	buf, err := ioutil.ReadFile(logFile)
+	if err != nil {
+		return "", err
+	}
+
+	return string(buf), nil
+}
+
 // generateListeningAddresses returns two strings representing listening
 // addresses designated for the current rpc test. If there haven't been any
 // test instances created, the default ports are used. Otherwise, in order to
```
