### ISSUE TITLE
Stall detection should only really happen for the sync peer

### ISSUE THREAD

**Issue by jrick** [btcsuite/btcd#776]
Right now btcd has no multipeer syncing support, so there is exactly one syncpeer that it might be syncing from at any time.

It is important to have stall detection for this sync peer.  If the peer stalls, it should be kicked so another peer can be chosen.  Failing to do so can result in your node getting stuck because the sync peer is stuck.

However, it is not nearly as important to apply this same stall detection to other peers that are not your sync peer.  These nodes can be kept connected for far longer, and this should prevent many of the issues with disconnecting peers that take too long to respond to some request.

I'm unsure if the stall detection should be completely removed for these non-sync peers, or if it should be applied with a longer timeout.  Investigation and analysis is required.

**Comment by stevenroose** [comment]
I'd favor full multipeer support instead of improving the current design.

**Comment by jrick** [comment]
@stevenroose we want multipeer as well.  This is a temporary improvement until it can be supported.  If it's not to much work to complete, it should be considered.
