### ISSUE TITLE
need new rpc command .. addnode <ip> remove .. does not remove from dns list as well as persistent list

### ISSUE THREAD

**Issue by toddfries** [btcsuite/btcd#79]
<pre>
104939 &lt;@davec&gt; ok so it's only looking in peers that we added
104950 &lt;@davec&gt; actually I think it's persistent peers in general
104952 &lt; todd&gt; the getpeerinfo rpc command can list all peers regardless of rpc list or dns list
105011 &lt; todd&gt; but the rpc 'addnode &lt;ip&gt; remove' cannot remove something from the dns list, only the rpc list
105036 &lt;@davec&gt; right    case delNodeMsg:
105036 &lt; todd&gt; so from what you said, 's/rpc list/persistent list/'
105036 &lt;@davec&gt;         found := false
105037 &lt;@davec&gt;         for e := state.persistentPeers.Front(); e != nil; e = e.Next() {
105044 &lt;@davec&gt; yep, that's wrong
105048 &lt;@davec&gt; ticket please
...
111339 &lt;@davec&gt; todd: oga just informed me that addnode is only *supposed* to work on persistent peers to be compatible with bitcoind
111410 &lt;@davec&gt; I rather agree that isn't very smart, but I guess we'll just provide an extension command that does it
111432 &lt;@davec&gt; not being able to remove any connection doesn't make sense

</pre>

**Comment by davecgh** [comment]
This will be implemented via the new `node` command once #341 is merged.
