### ISSUE TITLE
Why CoinbaseValue of GetBlockTemplateResult is *int64 not int64?

### ISSUE THREAD

**Issue by sbwdlihao** [btcsuite/btcd#866]
I am a bit puzzled about the type of CoinbaseValue

**Comment by stevenroose** [comment]
At the places where they set the value, they also create the pointer, so it makes little sense to me either :p

**Comment by davecgh** [comment]
It's a pointer because it's an optional field in the JSON result.   Without it being a pointer, there would be no way to tell the difference between an unset (as in don't include it in the results) result and the zero value (as in include it, but set it to zero).

```Go
package main

import (
	"encoding/json"
	"fmt"
)

type foo struct {
	CoinbaseValue int64 `json:"coinbasevalue,omitempty"`
}

type foo2 struct {
	CoinbaseValue *int64 `json:"coinbasevalue,omitempty"`
}

func main() {
	// Result is omitted even though it's zero.
	b, _ := json.Marshal(foo{0})
	fmt.Println(string(b))

	// Result is NOT omitted even though it's zero.
	val := int64(0)
	b2, _ := json.Marshal(foo2{&val})
	fmt.Println(string(b2))

	// Result is omitted specifically when requested by using nil.
	b3, _ := json.Marshal(foo2{nil})
	fmt.Println(string(b3))
}
```
Output:
```
{}
{"coinbasevalue":0}
{}
```

**Comment by stevenroose** [comment]
What makes it an optional field? I'd say `omitempty` makes them optional but the `SigOpLimit` and `SizeLimit` fields also have `omitempty` but are not there as being references..

**Comment by davecgh** [comment]
Yes, it's the `omitempty` tag that makes it optional.  However, it depends on what you want the behavior to be.  The code in there is really just a reflection of what is required by the Core API for compatibility.  There are many choices that don't really make a lot of sense to be honest.

That said, there are different scenarios where you might want to omit the result.  One is the case where you always omit it when it's a zero value independent of other fields.  That is the case for `SigOpLimit` and `SizeLimit`.  They are included in the result regardless of other fields, but their absence is assumed to mean they are 0.

Another case is when the result is to be omitted based on some other information such as the case for `CoinbaseValue`.  The caller can specifically request an already created coinbase transaction as part of the `getblocktemplate` request and, in that case, the `CoinbaseValue` (and `CoinbaseAux`) must be omitted.  However, if the caller doesn't request a premade coinbase transaction, they must be included regardless of their being the zero value or not.

The semantics for the `getblocktemplate` fields all come out of the BIP by the way!

**Comment by sbwdlihao** [comment]
I understand it, thanks very much!
