### ISSUE TITLE
Is btcd ready for SegWit?

### ISSUE THREAD

**Issue by PirosB3** [btcsuite/btcd#869]
Hi!

I'm running a full node and I'm concerned that btcd does not implement SegWit. Is the `btcsuite` team opinionated against SegWit or is it in the roadmap? I'd be happy to review or contribute to such implementation if it's underway :)

Thanks for all your amazing work

**Comment by Beldur** [comment]
I think this pull request tracks SegWit: #656

**Comment by davecgh** [comment]
As @Beldur notes, that PR is in progress and is pretty close.  It involves major changes to many aspects of Bitcoin and the code base however, so we are being extra vigilant and intentionally going slowly and carefully with it.

**Comment by afk11** [comment]
bump

**Comment by stevenroose** [comment]
Citing from IRC:
```
<roasbeef> afk11: i'm working on finishing up the last bits of my segwit PR, more segwit 
related policy was added since i last touched it, implenenting thos now and pullingin the 
latest script+tx+sighash json tests 
<davec> roasbeef: thanks.  I will be joining you on btcd again soon.  About to get this 
release out that I've been so engrossed with
```

**Comment by ysangkok** [comment]
Seems like that PR is getting finished now, I think it will get merged very soon now.

**Comment by davecgh** [comment]
Segwit is now supported as #656 has been merged.
