### ISSUE TITLE
Port new rescan RPC from dcrd

### ISSUE THREAD

**Issue by jrick** [btcsuite/btcd#882]
This will be used by upcoming changes to btcwallet (backported from dcrwallet).

In order to not destroy backwards compatibility, this RPC can be added under a new method name (thinking `rescanblocks`, since it takes hashes of blocks to rescan as parameters).

The block hashes in dcrd's rescan RPC are also passed as a single concatenated non-byte-reversed hexadecimal string.  We should discuss whether to continue using this or to switch to using a JSON array of byte-reversed block hash strings.

**Comment by jrick** [comment]
Discussed with @davecgh on zkc and will use a JSON array of strings for the hashes.

**Comment by aakselrod** [comment]
I'm taking this issue.
