### ISSUE TITLE
Port getheaders RPC from dcrd

### ISSUE THREAD

**Issue by jrick** [btcsuite/btcd#883]
This will be used by upcoming changes to btcwallet (backported from dcrwallet).

The block locator hashes in dcrd's getheaders RPC are also passed as a single concatenated non-byte-reversed hexadecimal string. We should discuss whether to continue using this or to switch to using a JSON array of byte-reversed block hash strings.

**Comment by jrick** [comment]
Discussed with @davecgh on zkc and will use a JSON array of strings for the hashes.

**Comment by aakselrod** [comment]
I'm taking this issue.

**Comment by davecgh** [comment]
This has been resolved by #890.
