### ISSUE TITLE
Port loadtxfilter RPC from dcrd and add filtered transactions to blockconnected notification

### ISSUE THREAD

**Issue by jrick** [btcsuite/btcd#884]
This will be used by upcoming changes to btcwallet (backported from dcrwallet).  loadtxfilter is also a requirement to implement the new rescan RPC.

I would also like to start some discussion on whether to remove the existing recvtx and redeemingtx notifications, which are duplicates of the new transaction filter functionality and, unlike rescan which we have elected to keep because the new version will be massively different, are trivial to update to.  Removing them would help a lot to improve the overall code quality of the notification system.

**Comment by davecgh** [comment]
I'm kind of torn on this one as well.  I'd prefer to hear from actual users of the API prior to making a final decision on it.

That said, I personally lean towards keeping the existing API and marking it deprecated.  This will help provide consumers with time to update their code for the latest API.  Then the deprecated code can be removed in two release versions.

**Comment by jrick** [comment]
at this rate 2 release versions will be 2 years later :p

**Comment by Roasbeef** [comment]
I currently use the `OnRedeemingTx` is a few areas within `lnd`. Switching away from usage of the call on my side would be pretty trivial. However, I may be an exception as we haven't yet done a proper release so we don't have any dependent users. I also lean towards leaving it in and marking the API as deprecated. A clear downside to this approach is that we'll have to maintain essentially "dead" code for another release or two.

**Comment by stevenroose** [comment]
On the other side, considering Segwit, the next release will be one that 
requires devs to update their dependent software too. So the release 
implicitly already contains "breaking changes" in some way.

**Comment by aakselrod** [comment]
I'm taking this issue.
