### ISSUE TITLE
Port version RPC from dcrd

### ISSUE THREAD

**Issue by jrick** [btcsuite/btcd#886]
In dcrd the json-rpc API is versioned and can be queried with the version rpc.  I'd like that same functionality in btcd so that btcwallet and other clients can test for compatibility with the server.

https://github.com/decred/dcrd/blob/da8a0334fa1f08b9d7e37a0ba3355c45e7694f30/rpcserver.go#L5731

**Comment by aakselrod** [comment]
I'm taking this issue.

**Comment by jrick** [comment]
Thanks. Please do this before the other backports, and then increment the version for each of those.

**Comment by jrick** [comment]
This has been implemented on master.
