### ISSUE TITLE
Unable to start server on [:18333]: unexpected EOF

### ISSUE THREAD

**Issue by stevenroose** [btcsuite/btcd#918]
I recently restarted a running btcd on testnet (ctrl-C, relaunch) and I got this error. Even after rebooting and pulling the latest version from master, it persists. It is not present on main chain.

```
$ btcd --testnet --txindex
01:01:40 2017-02-02 [INF] BTCD: Version 0.12.0-beta
01:01:40 2017-02-02 [INF] BTCD: Loading block database from '/media/data/bitcoin/btcd/data/testnet/blocks_ffldb'
01:01:40 2017-02-02 [INF] BTCD: Block database loaded
01:01:40 2017-02-02 [INF] INDX: Transaction index is enabled
01:01:40 2017-02-02 [ERR] BTCD: Unable to start server on [:18333]: unexpected EOF
01:01:40 2017-02-02 [INF] BTCD: Gracefully shutting down the database...
01:01:40 2017-02-02 [INF] BTCD: Shutdown complete
```

Listen interface is default.

`$ netstat --listen | grep 18333` gives nothing, so nothing else is using the port. (Right?)

I don't know if this matters, but for testnet, I have ran @Roasbeef's fork from time to time to use lnd. But I assumed both versions could be used interchangeably.

**Comment by davecgh** [comment]
Well that error isn't very useful, but I would start by specifying a bogus config file to see if it persists.

```
$ btcd --testnet --txindex -C bogus.conf
```

**Comment by stevenroose** [comment]
```
$ cat ~/.btcd/btcd.conf 
datadir=/media/data/bitcoin/btcd/data
logdir=/media/data/bitcoin/btcd/logs

rpcuser=rpcuser
rpcpass=rpcpass
```

What do you mean with a bogus config file?

**Comment by davecgh** [comment]
I meant pointing it to an intentionally invalid config file, but I see there is nothing special in yours.  Try changing the datadir on the CLI to see if starts up.

**Comment by stevenroose** [comment]
Aha, it does. That's weird. 
Does that mean Roasbeef's fork corrupted the file? 
Let me try and build from their again and try to run..

**Comment by stevenroose** [comment]
It works if I build roasbeef's version again. This is weird.

**Comment by davecgh** [comment]
That probably means the database isn't compatible for some reason.  I have not used roasbeef's fork, so I'm not sure why, but clearly the databases are not compatible in some way.

**Comment by stevenroose** [comment]
I'll report it there, it's more something they should be concerned about.

**Comment by Roasbeef** [comment]
The databases aren't compatible as blocks with witness data have their transactions stored using the new format for encoding transactions (if they have witness data). As a result, it isn't possible (with the way my fork handles this case) to _downgrade_ to a pre-segwit release after you've process blocks on a chain which has activated segwit. However, it is possible to _upgrade_ from a pre-segwit release and properly sync blocks in a chain that has activated segwit. 

There're a few workarounds (like adding additional indexes and storing witness data in a unique key/bucket) that we could pursue to allow downgrades. As a bonus, if later we _do_ store witness data independently, that would pave a path for during witness-only pruning. 

Alternatively, we can just explicitly _disallow_ downgrades to a pre-segwit version from a post-segwit (and chain actived) version.

**Comment by stevenroose** [comment]
I thought testnet3 had segwit activated as well..

**Comment by Roasbeef** [comment]
Yes it does. Correct me if I'm wrong, but from my reading of the issue you downgraded to the `master` branch of btcd (mainline) from my fork?

**Comment by davecgh** [comment]
I'm glad to hear it is known that you can't downgrade and that makes sense.  I would like for that error to be a bit nicer though because it is completely unclear why it's failing.  I'm going to go ahead and close this though since it's not really an issue on main.

Might want to link the segwit PR to this though.

**Comment by stevenroose** [comment]
@Roasbeef oh yeah, btcd master doesn't have segwit pulled yet :) makes sense, thanks!
