### ISSUE TITLE
Getrawtransaction & gettransaction always faild

### ISSUE THREAD

**Issue by Demontf** [btcsuite/btcd#926]
I used getrawtransation like this.
ws.send('{"jsonrpc":"1.0","id":"getrawtransaction","method":"getrawtransaction","params":["11584a73f9a6274c3efaa39e5b26bec48a12f0d70eabbe0035049f8ff9fd3acd",0]}');

the results always error, please help me.
{ 
result: null,
  error: 
   { code: -5,
     message: 'The transaction index must be enabled to query the blockchain (specify --txindex)' },
  id: 'getrawtransaction' }

**Comment by dajohi** [comment]
run btcd with --txindex  or txinde=1 in your btcd.conf

**Comment by liyue201** [comment]
soga

**Comment by liyue201** [comment]
搞了半天，原来如此
