### ISSUE TITLE
Inquiry 

### ISSUE THREAD

**Issue by cloudkitsch** [btcsuite/btcd#928]
Hi, 
The documentation says that it properly relays newly mined bitcoin however I'm wondering if this is compatible with [https://github.com/cbuchner1/CudaMiner cbuchner1/CudaMiner]?

**Comment by davecgh** [comment]
Sorry for the late response.  I missed it somehow.  I'm not familiar with that particular miner, but as long as it uses `getblocktemplate` to retrieve the work, it is compatible since `btcd` follows the specification for it.
