### ISSUE TITLE
This BTCD is still updated?

### ISSUE THREAD

**Issue by senlinms** [btcsuite/btcd#929]
This BTCD is still updated?

**Comment by jcvernaleo** [comment]
btcd is still active.  Most of the developers are spending time of decred so we aren't always updating as quickly as previously, but we have not abandoned btcd.

**Comment by senlinms** [comment]
thank you very much！
发自网易邮箱大师
On 03/03/2017 21:08, John C. Vernaleo wrote:

btcd is still active. Most of the developers are spending time of decred so we aren't always updating as quickly as previously, but we have not abandoned btcd.
