### ISSUE TITLE
"[ERR] BTCD: file missing: file missing" is stopping my node from starting

### ISSUE THREAD

**Issue by jongillham** [btcsuite/btcd#937]
I'm using the most recent code 4b348c1d3 and my node has been running for weeks. It suddenly stopped syncing at block 463064.

Now when I try and restart the node I get the following log message:

```
22:23:06 2017-04-22 [WRN] BTCD: open /home/btcd/.btcd/btcd.conf: no such file or directory
22:23:06 2017-04-22 [INF] BTCD: Version 0.12.0-beta
22:23:06 2017-04-22 [INF] BTCD: Loading block database from '/mnt/disks/mainnet/data/mainnet/blocks_ffldb'
22:23:07 2017-04-22 [ERR] BTCD: file missing: file missing
22:23:07 2017-04-22 [INF] BTCD: Shutdown complete
```

Does anyone know why this could have happened and how I can prevent it happening in the future? Is there any way of restarting my node without having to resync the entire blockchain?

Here's the log output from `data/mainnet/blocks_ffldb/metadata/LOG`:

```
=============== Apr 22, 2017 (UTC) ===============
22:23:06.948003 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
22:23:07.170682 version@stat F·[3 48 786 5740 12555] S·-1674234649B[3MiB 63MiB 986MiB 1GiB -358730686B] Sc·[0.75 0.63 0.99 1.00 0.16]
22:23:07.201727 db@open opening
22:23:07.322822 journal@recovery F·1
22:23:07.334291 journal@recovery recovering @43674725
22:23:07.351548 version@stat F·[3 48 786 5740 12555] S·-1674234649B[3MiB 63MiB 986MiB 1GiB -358730686B] Sc·[0.75 0.63 0.99 1.00 0.16]
22:23:07.573175 db@janitor table missing @43673237
22:23:07.573367 db@janitor table missing @43673238
```

**Comment by stevenroose** [comment]
What's the command you run with, your config file location and the datadir value in your config file?

Did you check if there is free space left on the partition that data folder is on?

**Comment by jongillham** [comment]
This is the command:

```
./btcd --txindex \
        --externalip=$EXTERNAL_IP \
        --datadir=$DISK_MOUNT_POINT/data \
        --logdir=$DISK_MOUNT_POINT/log 
```

There is space on the partition. I tested again with a purposefully small partition to see what would happen and there is a specific 'out of space' type of error when the disk is full and `btcd` tries to write to it.

For the time being I guess I'll have to keep snapshots of my data more regularly so that I don't need to resync massive portions of the chain if/when it happens again.

**Comment by davecgh** [comment]
In my experience this has always been related to corruption.  Typically due to either hardware issues, experimental filesystems, network filesystems not properly syncing, etc.

**Comment by jongillham** [comment]
I'll close this for now and reopen/recreate the issue if it repeats.
