### ISSUE TITLE
failed to open ldb transaction: leveldb/table: corruption on data-block

### ISSUE THREAD

**Issue by stevenroose** [btcsuite/btcd#938]
I got this panic just now. Some things that might have corrupted data:
 - I recently moved all my data files from an Arch installation to an Alpine Linux one/
 - I used OpenRC to stop the daemon, it should gracefully stop it instead of killing it though.
 - I tried to setup a VPN that did eventually not work, so there might have been issues that interrupted a download or whatever.

https://gist.github.com/stevenroose/254ad131524f9849ddf31cdaed590199

**Comment by stevenroose** [comment]
I keep having them. I have an SSD drive connected through a SATA-USB adapter to my machine. What are the odds this is due to a bad link with that adapter?

I have a mainnet and testnet btcd running together and they crash both around the same time consistently.
![](https://i.imgur.com/ImTaS5G.png)

**Comment by jrick** [comment]
It's definitely a nonzero chance.  USB is also your bottleneck here (might as well use a HDD).  Are you unable to connect it over SATA III?

**Comment by stevenroose** [comment]
It's USB 3.0, [this is the adapter](https://www.amazon.es/gp/product/B01H1I9X60/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1).

I tried to run it yesterday night on the local hard drive (testnet), so I can let you know tonight when I get home if it is related.

**Comment by stevenroose** [comment]
So no. It also happens on the local hard drive. This is weird. What could this possibly be? It happens consistently within 12 hours.

**Comment by jrick** [comment]
Can you run a memory check overnight?

**Comment by stevenroose** [comment]
@jrick Uhm, no idea how. If you point me to some references, I certainly can try. I have all the time and the box isn't doing anything else than this.
What cases in general can cause this? I started from a fresh install (btcsuite/btcd#master), fresh directory. Seems like it must be disk or network.

**Comment by jrick** [comment]
memtest86 would be a good starting point

**Comment by dajohi** [comment]
What go version?

**Comment by stevenroose** [comment]
`go version go1.7.3 linux/amd64`

**Comment by jrick** [comment]
Is this hardware running alpine the same hardware you were using with arch? If so was the corruption ever seen on arch?

**Comment by stevenroose** [comment]
@jrick my bad, had to mention. No, I moved it from my Arch laptop to the Alpine server. Will try to do the memtest86 this weekend.

**Comment by jrick** [comment]
@stevenroose reported many memory errors in IRC after performing the memory test.
