### ISSUE TITLE
script length not checked properly for bip16

### ISSUE THREAD

**Issue by benma** [btcsuite/btcd#941]
Hi

During execution, a new script is pushed for execution:

https://github.com/btcsuite/btcd/blob/89728419b084566ec52b97fb61d381f6c487cbad/txscript/engine.go#L341

If I'm not mistaken, the check that the script is <=10'000 bytes doesn't happen anywhere. The script size check only happens once in the beginning (https://github.com/btcsuite/btcd/blob/89728419b084566ec52b97fb61d381f6c487cbad/txscript/engine.go#L675), but not new scripts are added.

Would it make sense to put the check right in `parseScript()`?

**Comment by davecgh** [comment]
It is correct as is for pre-segwit code.  The script has already been checked to be <= the maximum size and since the script is all encompassing, it's not possible to extract a subscript that is longer than the containing script.

Things change a bit with segwit, but master does not yet support it.

**Comment by benma** [comment]
That makes sense, thanks!
