### ISSUE TITLE
OP_RETURN transaction

### ISSUE THREAD

**Issue by GaetanCathelain** [btcsuite/btcd#942]
Hi,

I've been looking into btcd lately and I can't seem to find a way to create a transaction with an OP_RETURN script. Am I just blind or you didn't/don't plan to add this feature in the RPC client ?

Edit: The method I use with the default bitcoin client is createRawTransaction with a second output with a "data" field containing the wanted data, but it seems that your createRawTransaction only takes addresses and amounts as outputs.

**Comment by jrick** [comment]
Sorry, this issue is unclear.  Are you trying to use bitcoin-cli with the btcd JSON-RPC server?

**Comment by GaetanCathelain** [comment]
Sorry, I'm trying to use the btcrpcclient with bitcoind, I shall post the issue on the appropriate repo :)
