### ISSUE TITLE
Blockchain storage compatibility

### ISSUE THREAD

**Issue by abitrolly** [btcsuite/btcd#950]
Does `btcd` store blockchain on the disk in the same structure as official Bitcoin full node?
If I switch from official full node to `btcd`, will I have to redownload or reindex existing blockchain files?

Is there any blockchain storage specification that requires full nodes to comply?

**Comment by tb00** [comment]
Bitcoin node implementations are not required to use the same structures to persist data on disk. Data stored on disk uses a different format. There is a way to bootstrap `btcd` using a binary file containing the blockchain, you will find details [here](https://github.com/btcsuite/btcd/blob/master/docs/using_bootstrap_dat.md).

Having said that, I would rather let `btcd` process the initial download, using your current up-to-date node as the peer to download from. This way the download will be quick and smooth and you can cut external network traffic - assuming the two nodes run on the LAN.

**Comment by abitrolly** [comment]
That answers the question. Thanks.

Is there a documentation about `btcd` storage format? Maybe there is an explanation of the reasons why `btcd` chose its own format and what are advantages and drawbacks compared to official bitcoin client storage?

**Comment by jcvernaleo** [comment]
I believe we did the on-disk format based just on the database we used (so leveldb) since we need to get it into and out of that database quickly.  Check out `database/ffldb` for more details on it.

**Comment by abitrolly** [comment]
(database)[https://github.com/btcsuite/btcd/tree/master/database#readme] supports different backend. That's neat.

**Comment by davecgh** [comment]
I'm going to close this since the question has been answered.

**Comment by abitrolly** [comment]
Yes. Thanks for the prompt response.
