### ISSUE TITLE
btcd archtecture diagram

### ISSUE THREAD

**Issue by abitrolly** [btcsuite/btcd#951]
Is there an uptodate architecture diagram in this repository or official docs. The one at https://blog.conformal.com/btcd-not-your-moms-bitcoin-daemon/ looks awesome,  but probably too outdated from 2013.

![](https://blog.conformal.com/wp-content/uploads/2013/10/btcd_arch.png)

**Comment by davecgh** [comment]
There isn't an updated one, but that one is actually still accurate with the exception of the package name changes.

`btcchain` -> `blockchain`
`btcwire` -> `wire`
`btcdb` -> `database`
`btcscript` -> `txscript`

**Comment by abitrolly** [comment]
@davecgh is there an SVG of this image? It could be fixed then.

**Comment by abitrolly** [comment]
Clickable.
[`btcchain`](https://github.com/btcsuite/btcchain) -> [`blockchain`](https://github.com/btcsuite/btcd/tree/master/blockchain#readme)
[`btcwire`](https://github.com/btcsuite/btcwire) -> [`wire`](https://github.com/btcsuite/btcd/tree/master/wire#readme)
[`btcdb`](https://github.com/btcsuite/btcdb) -> [`database`](https://github.com/btcsuite/btcd/tree/master/database#readme)
[`btcscript`](https://github.com/btcsuite/btcscript) -> [`txscript`](https://github.com/btcsuite/btcd/tree/master/txscript#readme)

**Comment by davecgh** [comment]
There isn't an SVG for it, although that would be ideal.
