### ISSUE TITLE
regression - even go get does not work

### ISSUE THREAD

**Issue by ggeorgiev** [btcsuite/btcd#961]
$ go get github.com/btcsuite/btcd
# github.com/btcsuite/btcd/database
../../../btcsuite/btcd/database/log.go:53: undefined: btclog.LogLevelFromString
../../../btcsuite/btcd/database/log.go:58: undefined: btclog.NewLoggerFromWriter
# github.com/btcsuite/btcd/txscript
../../../btcsuite/btcd/txscript/log.go:46: undefined: btclog.LogLevelFromString
../../../btcsuite/btcd/txscript/log.go:51: undefined: btclog.NewLoggerFromWriter

**Comment by jrick** [comment]
see the install instructions in the README.  You need to update your deps (and this should be manually run every time you git pull).

**Comment by ggeorgiev** [comment]
this does not seem right - there must be a way to organize your project without complicating the process for everybody else that depend on it

**Comment by jrick** [comment]
we have discussed the tradeoffs vs gains of various vendoring approaches internally and came to the conclusion that the current one works the best for us.  It's not even my favorite approach (personally i would rather dump the `go` tool for `gb` since it has no `GOPATH`), but it solves our problems with locking dependencies to exact commits without bloating the repo.

If anything, blame the `go` tool for being "too simple" and not working with the various vendoring tools to automatically checkout new deps from the lockfile after being updated.

**Comment by davecgh** [comment]
You don't have to use glide either.  You can simply update your deps appropriately.

`go get -u github.com/btcsuite/btclog`
`go get -u github.com/btcsuite/btcrpcclient`

**Comment by davecgh** [comment]
Closing this since it's a dependency issue in the submitter's build environment as opposed to an issues with the code.

**Comment by davecgh** [comment]
I should also add the `go get` does in fact work properly.  You simply need to make sure you include the update flag (`-u`) if you're dealing with an existing `GOPATH`.  For example, here is a fresh checkout:

```
$ export GOPATH=/d/gotmp; go get -v github.com/btcsuite/btcd/...
github.com/btcsuite/btcd (download)
github.com/btcsuite/btclog (download)
github.com/btcsuite/btcutil (download)
...
github.com/btcsuite/btcd/mempool
github.com/btcsuite/btcd/cmd/addblock
github.com/btcsuite/btcd
$ $ ls $GOPATH/bin/btcd
/d/gotmp/bin/btcd*
```

**Comment by ggeorgiev** [comment]
I have a go file in my project with the following imports:

	"github.com/btcsuite/btcd/btcjson"
	"github.com/btcsuite/btcd/chaincfg/chainhash"
	"github.com/btcsuite/btcd/txscript"
	"github.com/btcsuite/btcd/wire"
	"github.com/btcsuite/btcrpcclient"
	"github.com/btcsuite/btcutil"


when I `go get ./...` for my project I get the error that I explained. There is nothing wrong with my environment.  By the way if I `go get -v github.com/btcsuite/btcd/...` first it works, but that does not seem to be expected from any other dependency I have.

**Comment by jrick** [comment]
Looking closer, you have an updated btclog version (without `LogLevelFromString`, `NewLoggerFromWriter`, and others) but your btcd repo is *not* updated and still trying to call these methods, and that is causing the failures.

This is absolutely an issue with your environment or the commands you are using to update deps.  Lock your dependencies (e.g. using glide, like we do) if you don't want this happening in the future.
