### ISSUE TITLE
always get "unable to generate payment script for unsupported address type *btcutil.AddressPubKeyHash"

### ISSUE THREAD

**Issue by compasses** [btcsuite/btcd#971]
i have run the following code with all correct params, but always get the error as the per title.
and the address is right. so any something i missing?
func main() {
    // Parse the address to send the coins to into a btcutil.Address
    // which is useful to ensure the accuracy of the address and determine
    // the address type.  It is also required for the upcoming call to
    // PayToAddrScript.
    addressStr := "12gpXQVcCL2qhTNQgyLVdCFG2Qs2px98nV"
    address, err := btcutil.DecodeAddress(addressStr, &chaincfg.MainNetParams)
    if err != nil {
        fmt.Println(err)
        return
    }

    // Create a public key script that pays to the address.
    script, err := txscript.PayToAddrScript(address)
    if err != nil {
        fmt.Println(err)
        return
    }
    fmt.Printf("Script Hex: %x\n", script)

    disasm, err := txscript.DisasmString(script)
    if err != nil {
        fmt.Println(err)
        return
    }
    fmt.Println("Script Disassembly:", disasm)
}

**Comment by davecgh** [comment]
That means you have a dependency/vendoring issue with your build environment such that either your code or the btcsuite code is using a different version of `btcutil`.

I would guess the code your testing with is running against `GOPATH` while the btcd packages you're calling into are using a vendored version.

```Go
package main

import (
	"fmt"

	"github.com/btcsuite/btcd/chaincfg"
	"github.com/btcsuite/btcd/txscript"
	"github.com/btcsuite/btcutil"
)

func main() {
	// Parse the address to send the coins to into a btcutil.Address
	// which is useful to ensure the accuracy of the address and determine
	// the address type. It is also required for the upcoming call to
	// PayToAddrScript.
	addressStr := "12gpXQVcCL2qhTNQgyLVdCFG2Qs2px98nV"
	address, err := btcutil.DecodeAddress(addressStr, &chaincfg.MainNetParams)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Create a public key script that pays to the address.
	script, err := txscript.PayToAddrScript(address)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Printf("Script Hex: %x\n", script)

	disasm, err := txscript.DisasmString(script)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println("Script Disassembly:", disasm)
}
```

Output:
```
Script Hex: 76a914128004ff2fcaf13b2b91eb654b1dc2b674f7ec6188ac
Script Disassembly: OP_DUP OP_HASH160 128004ff2fcaf13b2b91eb654b1dc2b674f7ec61 OP_EQUALVERIFY OP_CHECKSIG
```
