### ISSUE TITLE
Private key address/hash (?)

### ISSUE THREAD

**Issue by nihiluis** [btcsuite/btcd#974]
how do I get a private key (hash or address what ever it is) like this from WIF?
5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip4nEB3kEtpNrZq5HZU

I found this: https://godoc.org/github.com/btcsuite/btcd/btcec#PrivateKey which should represent the private key, but no further info on how to get the format above.

from my understanding I should be able to calc something with D (from PrivateKey)?

**Comment by davecgh** [comment]
To decode the WIF: https://godoc.org/github.com/btcsuite/btcutil#DecodeWIF
To create an address from the associated pubkey: https://godoc.org/github.com/btcsuite/btcutil#NewAddressPubKey

Example:
```Go
package main

import(
	"fmt"
	
	"github.com/btcsuite/btcd/chaincfg"
	"github.com/btcsuite/btcutil"
)


func main(){
	wif, err := btcutil.DecodeWIF("5HpHagT65TZzG1PH3CSu63k8DbpvD8s5ip4nEB3kEtpNrZq5HZU")
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Printf("privkey: %x\n", wif.PrivKey.Serialize())
	fmt.Printf("pubkey: %x\n", wif.SerializePubKey())

	addr, err := btcutil.NewAddressPubKey(wif.SerializePubKey(),
		&chaincfg.MainNetParams)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Printf("addr: %v", addr.AddressPubKeyHash())
}```

Output:
```
privkey: 0000000000000000000000000000000000000000000000000000000000195bb9
pubkey: 04c220e76ba61898d2fb5176b54093a945c8446d6a267c3f5239ba0e0cd0f025d2be337b090b6482345b59172af5ff81ec83eccd17666b69ffad4441968374b4ab
addr: 1EW5WV8PD6QAFUgKdEEXJ4J6BVtfsj5X5N
```
